const fs = require('fs');
let content = fs.readFileSync('d:/github-repository/CyberPoker2077/src/logic/itemsEffect.js', 'utf8');

const replaces = [
  ['스태미나 회복', 'Stamina Regen'],
  ['라운드 시작시 스테미나 회복', 'Restores Stamina '],
  ['스테미나 회복', 'Stamina Regen'],
  ['쿨타임', 'Cooldown:'],
  ['라운드)', 'rounds)'],
  ['도파민 중독', 'Dopamine Addiction'],
  ['올인 쇼다운에서 승리 또는 패배시 스테미나 +', 'Restores +${this.value} Stamina upon winning or losing an All-In Showdown. (Cooldown:'],
  ['입장 권한', 'Entry Pass'],
  ['입장권한', 'Entry Pass'],
  ['구매시 "지하 바" 이용가능.', 'Grants access to the "Underground Bar".'],
  ['구매시 "오르빗" 이용가능.', 'Grants access to "Orbit".'],
  ['구매시 "H.B.D 클럽" 이용가능.', 'Grants access to the "H.B.D Club".'],
  ['블랙 컨슈머', 'Black Consumer'],
  ['구매시 암상인 뇌물 레벨이 ${this.value}가 됩니다.(1회성)', 'Sets Black Market bribe level to ${this.value} upon purchase. (One-time use)'],
  ['구매시 "더 벙커" 이용가능.', 'Grants access to "The Bunker".'],
  ['구매시 "홀덤 하우스" 이용가능.', 'Grants access to "Hold\'em House".'],
  ['구매시 "로얄 프라이빗 룸" 이용가능.', 'Grants access to "Royal Private Room".'],
  ['경험치 부스트', 'XP Boost'],
  ['승리시 경험치 +', 'Grants +${Math.floor(this.value * 100)}% XP upon winning'],
  ['손실 보존', 'Loss Preservation'],
  ['쇼다운 패배 시 손실액 ${Math.floor(this.value * 100)} % 환급', 'Refunds ${Math.floor(this.value * 100)}% of lost chips upon losing a Showdown'],
  ['LT 회복량 증가', 'Enhanced LT Regen'],
  ['LT 회복', 'LT Recovery'],
  ['승리시 LT +', 'Restores +${this.value} LT upon winning'],
  ['타임 뱅크 추가', 'Time Bank Expansion'],
  ['생각 시간 +', 'Increases decision time by +'],
  ['초`', ' seconds.`'],
  ['잔돈 모으기', 'Spare Change'],
  ['승리 시 본인 배팅 총액을 ${Math.pow(10, this.value)}단위로 올림하여 획득합니다.', 'Rounds up your total bet amount to the nearest ${Math.pow(10, this.value)} units when winning.'],
  ['초기 자금 보너스', 'Initial Bankroll Bonus'],
  ['파산 시 다음 초기 자금 +', 'Increases next starting bankroll by +'],
  ['수수료 감면', 'Rake Reduction'],
  ['카지노 레이크 수수료 -', 'Reduces casino rake by -'],
  ['라운드시 시작시 LT +', 'Restores +'],
  ['회복 (쿨타임:', 'LT at the start of a round (Cooldown:'],
  ['바이인 배수', 'Buy-In Multiplier'],
  ['바이인 배수 +', 'Increases buy-in multiplier by +'],
  ['블라인드 할인', 'Blind Discount'],
  ['블라인드 비용 -', 'Reduces blind cost by -'],
  ['단골 우대', 'Loyalty Card'],
  ['암상인 취급 최대 물품수 +', 'Increases the maximum number of items offered by the Black Market dealer by +'],
  ['보너스 배당', 'Pot Bonus'],
  ['승리 시 본인 지분의 ', 'Deposits amount equal to '],
  ['% 만큼 뱅크롤로 입금', '% of your pot share directly into your bankroll upon winning'],
  ['인슈어런스', 'Insurance'],
  ['올인 쇼다운 시점 승률이 75% 이상일때, 패배시 승률의 ', 'Refunds CR equal to '],
  ['% 만큼 CR 보전`', '% of your equity if you lose an All-In Showdown while having over 75% equity.`'],
  ['마이더스의 손', 'Midas Touch'],
  ['획득하는 경험치의 ', 'Adds CR equivalent to '],
  ['% 만큼의 CR이 뱅크롤에 추가됩니다.', '% of the XP you gain directly to your bankroll.'],
  ['양자 행운', 'Quantum Luck'],
  ['올인 쇼다운 시점 승률이 50% 미만일때 발동되며, 승리시 부족한 승률 만큼의 팟 보너스 ', 'Activates in an All-In Showdown with under 50% equity. Upon winning, grants a pot bonus of '],
  ['다이아 수집가', 'Diamond Collector'],
  ['하트 수집가', 'Heart Collector'],
  ['스페이드 수집가', 'Spade Collector'],
  ['클럽 수집가', 'Club Collector'],
  ['럭키 7 수집가', 'Lucky 7 Collector'],
  ['승리시 본인 지분의 팟 보너스 ', 'Upon winning, grants a pot bonus of '],
  ['* (보드+핸드 다이아 문양 수)%', '* the number of Diamonds in your hand and the board%'],
  ['* (보드+핸드 하트 문양 수)%', '* the number of Hearts in your hand and the board%'],
  ['* (보드+핸드 스페이드 문양 수)%', '* the number of Spades in your hand and the board%'],
  ['* (보드+핸드 클럽 문양 수)%', '* the number of Clubs in your hand and the board%'],
  ['* (보드+핸드 7의 개수)%', '* the number of 7s in your hand and the board%'],
  ['징조', 'The Omen'],
  ['패배시 본인 지분의 팟 보너스 ', 'Upon losing, grants a refund of '],
  ['* (보드+핸드 6의 개수)%', '* the number of 6s in your hand and the board%'],
  ['플러시 전문가', 'Flush Master'],
  ['플러시로 승리시 경험치 보너스 +', 'Grants +'],
  ['%`', '% XP bonus when winning with a Flush.`'],
  ['풀 옵션 펜트하우스', 'Full Option Penthouse'],
  ['풀하우스로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Full House.`'],
  ['스트레이트 플러시 전문가', 'Straight Flush Master'],
  ['스트레이트 플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Straight Flush.`'],
  ['포카드 전문가', 'Quads Master'],
  ['포 카드로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'Grants +${Math.floor(this.value * 100)}% XP bonus when winning with Four of a Kind.`'],
  ['왕의 물내림', 'Royal Execution'],
  ['로열 플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Royal Flush.`'],
  ['블랙잭 전문가', 'Blackjack Master'],
  ['내 핸드가 AJ인 경우, 다음 승리시 까지 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'If your hand is AJ, grants a +${Math.floor(this.value * 100)}% XP bonus that persists until your next win.`'],
  ['페어 전문가', 'Pair Master'],
  ['원페어 또는 투페어로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'Grants +${Math.floor(this.value * 100)}% XP bonus when winning with One Pair or Two Pair.`'],
  ['세트 메뉴', 'Set Menu'],
  ['세트로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'Grants +${Math.floor(this.value * 100)}% XP bonus when winning with Three of a Kind.`'],
  ['쿨러', 'Cooler'],
  ['쇼다운에서 풀하우스 이상의 족보로 패배시, 다음 승리 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'If you lose a Showdown with a Full House or better, grants +${Math.floor(this.value * 100)}% XP bonus on your next win.`'],
  ['아, 킥커 차이..', 'Outkicked...'],
  ['쇼다운에서 같은 족보로 패배시, 다음 승리 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'If you lose a Showdown to the same hand rank (kicker disadvantage), grants +${Math.floor(this.value * 100)}% XP bonus on your next win.`'],
  ['실패는 성공의 어머니', 'Failure is the Mother of Success'],
  ['쇼다운에서 승리시 경험치 보너스 +${Math.floor(this.value * (this.stack + 1) * 100)}%\\n(이 효과는 쇼다운에서 패배할 때마다 누적되며, 승리할때 초기화.)`', 'Grants +${Math.floor(this.value * (this.stack + 1) * 100)}% XP bonus upon winning a Showdown.\\n(This effect accumulates each time you lose a Showdown and resets upon winning.)`'],
  ['틸트 회복', 'Tilt Recovery'],
  ['쇼다운 패배 시 스테미나 +', 'Restores +'],
  ['더블 다운', 'Double Down'],
  ['스트레이트 족보로 승리 시 경험치 보너스 +${Math.floor(this.value * 100)}%`', 'Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Straight.`'],
  ['유령 배팅', 'Ghost Bet'],
  ['배팅 시 ${Math.floor(this.value * 100)}% 확률로 배팅 금액을 환급`', 'Grants a ${Math.floor(this.value * 100)}% chance to refund your bet amount when betting.`'],
  ['승리의 기쁨', 'Joy of Victory'],
  ['쇼다운에서 승리시 스테미나 +', 'Restores +'],
  ['배수의 진', 'Last Stand'],
  ['라운드 시작시, 보유 칩이 25BB 이하일 때 LT +${this.value} 회복`', 'Restores +${this.value} LT at the start of a round if your chip stack is 25 BB or less.`'],
  ['연승 마스터', 'Streak Master'],
  ['승리할때 마다 경험치 보너스 +${Math.floor(this.value * (this.stack + 1) * 100)}% (이 효과는 승리할때 마다 누적되며, 쇼다운 패배시 초기화.)`', 'Grants +${Math.floor(this.value * (this.stack + 1) * 100)}% XP bonus for each win. (This effect accumulates with every win and resets upon losing a Showdown.)`'],
  ['양자 폴드', 'Quantum Fold'],
  ['프리플랍에서 폴드 시 배팅한 칩의 ${Math.floor(this.value * 100)}% 환급 (쿨타임: ${this.maxCooldown} 라운드)`', 'Refunds ${Math.floor(this.value * 100)}% of your wagered chips when folding Pre-Flop. (Cooldown: ${this.maxCooldown} rounds)`'],
  ['시냅스 리딩', 'Synapse Reading'],
  ['해당 라운드에서 CPU 플레이어들의 생각을 훔쳐볼 수 있다. (쿨타임: ${this.maxCooldown} 라운드)`', 'Allows you to intercept the thoughts of CPU players during the current round. (Cooldown: ${this.maxCooldown} rounds)`'],
];

replaces.forEach(([from, to]) => {
  content = content.replaceAll(from, to);
});

fs.writeFileSync('d:/github-repository/CyberPoker2077/src/logic/itemsEffect.js', content, 'utf8');
console.log('Items replaced successfully.');
