import { store } from './store.js';
import { PLAY_RECORD_STATS_TYPE } from './playRecordStats.js';
import { ITEM_EFFECT_ID } from './constants.js';

export const MODULE_EFFECT_TYPE = {
  ...ITEM_EFFECT_ID,
  XP_BOOST: 'xp_boost',
  ADD_BANKROLL: 'add_bankroll',
  HAND_HUD_ACTIVE: 'hand_hud_active',
  HUD_ACTIVE: 'hud_active',
  PENALTY_AMOUNT: 'penalty_amount',
  SPAWN_RATE_MUL: 'spawn_rate_mul',
  RAKE_DISCOUNT_RND_MUL: 'rake_discount_rnd_mul',
  MAX_STAMINA_BOOST: 'max_stamina_boost',
  SPAWN: 'spawn',
  PAID_REFUND: 'paid_refund',
  UNLOCK_ZONE: 'unlock_zone',
  LOW_PROFILE: 'low_profile',
  IDENTITY_FORGERY: 'identity_forgery',
  SUSPICION_HUD_ACTIVE: 'suspicion_hud_active',
};

export const MODULE_ACTION_TYPE = {
  ACCEPT_INVITE: 'ACCEPT_INVITE',
};

// Full Unified Agent Module Data List (Merged from legacy aiAgentTaskData & new specs)
export const AGENT_MODULE_DATA = [
  {
    id: 'module_hand_hud',
    tier: 'T1',
    price: 2500,
    name_ko: "족보 오버레이 모듈",
    name_en: "Hand Overlay Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: `자신이 현재 완성한 족보를 실시간으로 확인 할 수 있는 오버레이를 활성화 합니다.`,
    desc_en: `Activates an overlay to check the poker hand you've made in real-time.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '자신이 무슨 족보를 만들었는지 조차 모르는 초짜들한테 유용합니다!',
    desc_detail_en: 'Perfect for rookies who can\'t tell a Straight from a Flush. Stop guessing and start grinding.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 0,
    probability: 1,
    duration: 1 * 24 * 60,
    cooldown: 0,
    effect: [{ type: MODULE_EFFECT_TYPE.HAND_HUD_ACTIVE, amount: 1 }],
  },
  {
    id: 'module_suspicion_hud',
    tier: 'T2',
    price: 8000,
    name_ko: "의심도 오버레이 모듈",
    name_en: "Suspicion Overlay Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: `현재 테이블에서의 의심도를 실시간으로 확인 할 수 있는 인터페이스를 활성화 합니다.`,
    desc_en: `Activates a real-time monitor to track your current suspicion level at the table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '그들이 알아차리기 전에 자리를 뜨는게 현명하죠.',
    desc_detail_en: 'Better to cash out and vanish before the house catches on to your "luck."',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 0,
    probability: 1,
    duration: 1 * 24 * 60,
    cooldown: 0,
    effect: [{ type: MODULE_EFFECT_TYPE.SUSPICION_HUD_ACTIVE, amount: 1 }],
  },
  {
    id: 'module_status_hud',
    tier: 'T1',
    price: 4500,
    name_ko: "HUD 프로토콜 모듈",
    name_en: "HUD Protocol Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: '활성화 시 상대의 vPIP, PFR, 3BET, AF 수치를 실시간으로 분석합니다.',
    desc_en: 'Analyze opponents\' vPIP, PFR, 3BET, and AF in real-time.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '테이블에서 외부 연산 장치를 사용하는 건 엄격히 금지되어 있습니다. 하지만 들키지만 않는다면 무슨 상관일까요?',
    desc_detail_en: 'Using external calculation devices is strictly prohibited on the table. But then again, is it really a crime if you don\'t get caught?',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 3,
    probability: 1,
    duration: 60,
    cooldown: 0,
    effect: [{ type: MODULE_EFFECT_TYPE.HUD_ACTIVE, amount: 1 }],
  },
  {
    id: 'module_low_profile',
    tier: 'T3',
    price: 15000,
    name_ko: "익명성 감쇄 모듈",
    name_en: "Low Profile Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `해당 효과가 활성화 되어 있는 동안 생성되는 의심도가 50% 감소합니다.`,
    desc_en: `While this effect is active, the suspicion generated is reduced by 50%.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '쥐도 새도 모르게 하세요.',
    desc_detail_en: 'The best ghost is the one you never knew was there.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 15,
    probability: 0.05,
    duration: 4 * 60,
    cooldown: 0,
    effect: [{ type: MODULE_EFFECT_TYPE.LOW_PROFILE, amount: 0.5 }],
  },
  {
    id: 'module_identity_forgery',
    tier: 'T5',
    price: 45000,
    name_ko: "신분 위조 모듈",
    name_en: "Identity Forgery Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'HACKING',
    desc_ko: `가장 높은 의심도를 가진 구역의 의심도와 악명를 50% 감소시킵니다.`,
    desc_en: `Reduces the suspicion and infamy of the area with the highest suspicion level by 50%.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '필터 챙기는 거 잊지 마시고요.',
    desc_detail_en: 'Just don\'t forget your filter.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 25,
    probability: 0.03,
    duration: 60,
    cooldown: 7 * 24 * 60,
    effect: [{ type: MODULE_EFFECT_TYPE.IDENTITY_FORGERY, amount: 0.5 }],
  },
  {
    id: 'module_shadow_work_1',
    tier: 'T1',
    price: 3500,
    name_ko: "서브넷 섀도우 워크 I",
    name_en: "Sub-net Shadow Work I",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: '활성화 되있는 동안 매시간마다 8% 확률로 1,000~2,000CR을 얻습니다.',
    desc_en: 'While this is active, 8% chance to earn 1,000~2,000 CR every hour.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '유휴 연산력을 놀리는 건 자원 낭비입니다. 푼돈이라도 긁어모아야죠',
    desc_detail_en: 'Leaving idle computing power unused is a waste of resources. We must scrape together even the smallest amounts.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 5,
    probability: 0.08,
    duration: 60,
    cooldown: 0,
    effect: [{ type: MODULE_EFFECT_TYPE.ADD_BANKROLL, amount: 1000, maxMultiple: 2 }],
  },
  {
    id: 'module_shadow_work_2',
    tier: 'T2',
    price: 9000,
    name_ko: "서브넷 섀도우 워크 II",
    name_en: "Sub-net Shadow Work II",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: '활성화 되있는 동안 매시간마다 8% 확률로 2,500~5,000CR을 얻습니다.',
    desc_en: 'While this is active, 8% chance to earn 2,500~5,000 CR every hour.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 10,
    probability: 0.08,
    duration: 60,
    cooldown: 0,
    effect: [{ type: MODULE_EFFECT_TYPE.ADD_BANKROLL, amount: 2500, maxMultiple: 2 }],
  },
  {
    id: 'module_bandwidth_siphon',
    tier: 'T3',
    price: 22000,
    name_ko: "대역폭 탈취 모듈",
    name_en: "Bandwidth Siphon Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: '활성 상태 동안 매시간 10% 확률로 5,000~25,000CR을 탈취합니다.',
    desc_en: 'Siphons 5,000~25,000 CR every hour with a 10% success rate.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 15,
    probability: 0.1,
    duration: 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: MODULE_EFFECT_TYPE.ADD_BANKROLL, amount: 5000, maxMultiple: 5 }],
  },
  {
    id: 'module_hand_review',
    tier: 'T1',
    price: 3000,
    name_ko: "핸드 리뷰 가속 모듈",
    name_en: "Hand Review Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `경험치(XP) 획득량이 10% 증가합니다.`,
    desc_en: `Increases Experience (XP) gain by 10%.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 3,
    probability: 0.15,
    duration: 1 * 24 * 60,
    cooldown: 0,
    effect: [{ type: MODULE_EFFECT_TYPE.XP_BOOST, amount: 0.10 }],
  },
  {
    id: 'module_poker_coach',
    tier: 'T2',
    price: 12000,
    name_ko: "포커 코치 연산 모듈",
    name_en: "Poker Coach Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `경험치(XP) 획득량이 20% 증가합니다.`,
    desc_en: `Increases Experience (XP) gain by 20%.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 5,
    probability: 0.07,
    duration: 1 * 24 * 60,
    cooldown: 1 * 24 * 60,
    effect: [{ type: MODULE_EFFECT_TYPE.XP_BOOST, amount: 0.20 }],
  },
  {
    id: 'module_fish_finder',
    tier: 'T2',
    price: 10000,
    name_ko: "피쉬 탐지기 (Fish Finder)",
    name_en: "Fish Finder Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'NETWORKING',
    desc_ko: `테이블 내 [Fish] 성향 플레이어의 등장 확률이 2배 증가합니다.`,
    desc_en: `Doubles the spawn rate of [Fish] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 5,
    probability: 0.1,
    duration: 4 * 60,
    cooldown: 12 * 60,
    effect: [{ type: MODULE_EFFECT_TYPE.SPAWN_RATE_MUL, id: 'fish', amount: 2 }],
  },
  {
    id: 'module_maniac_attractor',
    tier: 'T3',
    price: 28000,
    name_ko: "매니악 유인 모듈",
    name_en: "Maniac Attractor Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'NETWORKING',
    desc_ko: `입장한 테이블에 [Maniac] 성향 플레이어의 등장 확률이 3배 증가합니다.`,
    desc_en: `Triples the spawn rate of [Maniac] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 8,
    probability: 0.05,
    duration: 4 * 60,
    cooldown: 12 * 60,
    effect: [{ type: MODULE_EFFECT_TYPE.SPAWN_RATE_MUL, id: 'maniac', amount: 3 }],
  },
  {
    id: 'module_rich_guy_hunter',
    tier: 'T4',
    price: 65000,
    name_ko: "자산가 추적 모듈 (Rich Guy Hunter)",
    name_en: "Rich Guy Hunter Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'NETWORKING',
    desc_ko: `입장한 테이블에 [Rich_Guy] 성향 플레이어의 등장 확률이 2배 증가합니다.`,
    desc_en: `Doubles the spawn rate of [Rich_Guy] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 20,
    probability: 0.05,
    duration: 4 * 60,
    cooldown: 12 * 60,
    effect: [{ type: MODULE_EFFECT_TYPE.SPAWN_RATE_MUL, id: 'rich_guy', amount: 2 }],
  },
  {
    id: 'module_grinders_mindset',
    tier: 'T4',
    price: 50000,
    name_ko: "그라인더의 정신 모듈",
    name_en: "Grinder's Mindset Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `최대 스태미나(Max Stamina)가 25 증가합니다.`,
    desc_en: `Increases Max Stamina by 25.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 30,
    probability: 0.15,
    duration: 1 * 24 * 60,
    cooldown: 0,
    effect: [{ type: MODULE_EFFECT_TYPE.MAX_STAMINA_BOOST, amount: 25 }],
  },
  {
    id: 'module_house_always_wins',
    tier: 'T5',
    price: 120000,
    name_ko: "하우스 해킹 모듈 (House Always Wins)",
    name_en: "The House Always Wins Module",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'HACKING',
    desc_ko: '1일 동안 자신이 속한 카지노 테이블에서 발생하는 모든 플레이어의 레이크를 당신이 가져갑니다.',
    desc_en: 'For 1 day, you take all the rake generated by all players at the casino table.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    cost: 40,
    probability: 0.03,
    duration: 24 * 60,
    cooldown: 7 * 24 * 60,
    effect: [{ type: MODULE_EFFECT_TYPE.PAID_REFUND, amount: 1.0 }],
  }
];
