
// Task Definitions
export const AI_TASK_DATA = [
  {
    id: 'neighborhood_game',
    tier: 1,
    name: 'Neighborhood Game',
    type: 'NETWORKING',
    desc: 'Host a rake-free home game with local fish.\n(RAKE 0% / SB 5 / BB 10 / base buy-in 200BB)',
    desc_detail: '집에 동네 지인들 불러서 게임을 진행합니다. 레이크도 아끼고, 친목도 다지는 유익한 (아마도?) 시간을 보낼 수 있습니다!',
    cost: 1, // LT per hour
    probability: 0.1, // 10% per hour
    duration: 4 * 60, // 4 hours in minutes after expired
    cooldown: 3 * 24 * 60,
    action: {
      type: 'ACCEPT_INVITE', zone: 'micro', location_id: 'micro_safe_house', available: 6 // only 6max
    }, // for MessageSystem
  },
  {
    id: 'fish_finder',
    tier: 2,
    name: 'Fish Finder',
    type: 'BOOST',
    desc: `Increase [Fish] persona spawn rate by 2x.`,
    desc_detail: '피쉬들이 많이 모이는 장소를 파악하여 정보를 수집합니다!',
    cost: 3,
    probability: 0.1,
    duration: 4 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'fish', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'fish', count: 25 }
  },
  {
    id: 'hand_review',
    tier: 1,
    name: "Hand Review",
    type: 'BOOST',
    desc: `Increase XP gain by 15%.`,
    cost: 2,
    probability: 0.15,
    duration: 1 * 24 * 60,
    cooldown: 0,
    effect: [{ type: 'xp_boost', amount: 0.15 }],
    unlock: { type: 'played_hand', count: 1000 }
  },
  {
    id: 'rake_discount_micro',
    tier: 1,
    name: 'Rake Discount [Micro]',
    type: 'BOOST',
    desc: `[마이크로 스테이크] 카지노 중 무작위 한 곳의 레이크가 3일 동안 50%가 됩니다.`,
    desc_detail: '레이크를 절약하기 위해 이벤트를 진행중인 카지노 정보를 수집합니다!',
    cost: 1,
    probability: 0.1,
    duration: 3 * 24 * 60, // 3 days
    cooldown: 0,
    effect: [{ id: 'micro', type: 'rake_discount_rnd_mul', amount: 0.5 }],
    unlock: { type: 'paid_rake', amount: 5000 }
  },
  {
    id: 'rake_discount_low',
    tier: 2,
    name: 'Rake Discount [Low]',
    type: 'BOOST',
    desc: `[로우 스테이크] 카지노 중 무작위 한 곳의 레이크가 3일 동안 50%가 됩니다.`,
    desc_detail: '하위 범죄 조직들의 구역 다툼 연산 데이터를 분석했습니다. 가장 경비가 취약해진 로우 스테이크 카지노의 수수료망 우회 코드를 확보했습니다!',
    cost: 2,
    probability: 0.1,
    duration: 3 * 24 * 60, // 3 days
    cooldown: 0,
    effect: [{ id: 'low', type: 'rake_discount_rnd_mul', amount: 0.5 }],
    unlock: { type: 'paid_rake', amount: 50000 }
  },
  {
    id: 'gambler_attractor',
    tier: 2,
    name: 'Gambler Attractor',
    type: 'BOOST',
    desc: `Increase [Gambler] persona spawn rate by 2x (If available at the table)`,
    desc_detail: '인근 도박꾼들의 뇌파 자극 패드에 오늘이 "그날"이라는 맞춤형 스팸 광고를 살포합니다. 한탕을 노리는 불나방들이 몰려듭니다!',
    cost: 4,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'gambler', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'gambler', count: 25 }
  },
  {
    id: 'maniac_attractor',
    tier: 2,
    name: 'Maniac Attractor',
    type: 'BOOST',
    desc: `Increase [Maniac] persona spawn rate by 3x (If available at the table)`,
    desc_detail: '테이블의 칩 잔량과 액션 빈도를 딥웹에 생중계합니다. 피 냄새를 맡고 이성을 잃은 매니악들이 묻고 더블로 가기 위해 입장합니다.',
    cost: 4,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'maniac', amount: 3 }],
    unlock: { type: 'Bust_enemy', id: 'maniac', count: 25 }
  },
  {
    id: 'maniac_attractor_2',
    tier: 3,
    name: 'Mad Max',
    type: 'BOOST',
    desc: `Increase [Maniac] persona spawn rate by 6x (If available at the table)`,
    desc_detail: '"분노 조절 장애 치료제 품귀 현상" 가짜 뉴스를 지역망에 뿌립니다. 약 기운이 떨어져 눈이 뒤집힌 중독자들이 테이블을 아수라장으로 만듭니다.',
    cost: 8,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'maniac', amount: 6 }],
    unlock: { type: 'Bust_enemy', id: 'maniac', count: 250 }
  },
  {
    id: 'gambler_attractor_2',
    tier: 4,
    name: 'No Gamble, No Future',
    type: 'BOOST',
    desc: `Increase [Gambler] persona spawn rate by 4x (If available at the table)`,
    desc_detail: '합법과 불법을 넘나드는 딥 다이브 도박 시뮬레이션 광고를 무차별 전송합니다. "내일이 없는" 진성 갬블러들의 자금이 끊임없이 수혈됩니다.',
    cost: 8,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'gambler', amount: 4 }],
    unlock: { type: 'Bust_enemy', id: 'gambler', count: 25 }
  },
  {
    id: 'rake_discount_mid',
    tier: 3,
    name: 'Rake Discount [Mid]',
    type: 'BOOST',
    desc: `[미드 스테이크] 카지노 중 무작위 한 곳의 레이크가 3일 동안 50%가 됩니다.`,
    desc_detail: '레이크를 절약하기 위해 이벤트를 진행중인 카지노 정보를 수집합니다!',
    cost: 6,
    probability: 0.1,
    duration: 3 * 24 * 60, // 3 days
    cooldown: 0,
    effect: [{ id: 'mid', type: 'rake_discount_rnd_mul', amount: 0.5 }],
    unlock: { type: 'paid_rake', amount: 500000 }
  },
  {
    id: 'rich_guy_hunter',
    tier: 3,
    name: 'Rich Guy Hunter',
    type: 'BOOST',
    desc: `Increase [Rich_Guy] persona spawn rate by 2x (If available at the table)`,
    desc_detail: '최고급 사이버 임플란트 카탈로그 구독자 명단을 해킹해 프라이빗 초청장을 발송합니다. 지갑은 두껍고 수읽기는 얕은 호구들이 타겟입니다.',
    cost: 8,
    probability: 0.05,
    duration: 4 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'rich_guy', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'rich_guy', count: 25 }
  },
  {
    id: 'fish_finder_2',
    tier: 4,
    name: 'Fish Finder',
    type: 'BOOST',
    desc: `Increase [Fish] persona spawn rate by 4x (If available at the table), but Always following a [Quant_Pro]`,
    desc_detail: '피쉬들이 더 많이 모이는 장소를 파악하여 정보를 수집합니다!',
    cost: 6,
    probability: 0.1,
    duration: 4 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'fish', amount: 4 }, { type: 'spawn', id: 'Quant_Pro', amount: 1 }],
    unlock: { type: 'Bust_enemy', id: 'fish', count: 25 }
  },
  {
    id: 'enhance_security',
    tier: 4,
    name: 'Enhance Security',
    type: 'BOOST',
    desc: `Decrease [Gangster] persona spawn rate by 50% (If available at the table)`,
    desc_detail: '가상의 사설 보안 업체의 패트롤 신호를 송출합니다. 번거로운 갱스터들의 출입이 눈에 띄게 줄어듭니다.',
    cost: 8,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn_rate_mul', id: 'gangster', amount: 0.5 }],
    unlock: { type: 'Bust_enemy', id: 'gangster', count: 125 }
  },
  {
    id: 'maniac_attractor_3',
    tier: 4,
    name: 'Furiosa',
    type: 'BOOST',
    desc: `Add 3 [Maniac] persona to table`,
    desc_detail: '이 테이블의 판돈은 칩이 아니라 목숨값이 될지도 모릅니다. 안전벨트 매세요!',
    cost: 12,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn', id: 'maniac', amount: 3 }],
    unlock: { type: 'Bust_enemy', id: 'maniac', count: 2500 }
  },
  {
    id: 'rich_guy_hunter_2',
    tier: 4,
    name: 'Someone with a nose for money',
    type: 'BOOST',
    desc: `Increase [Rich_Guy] persona spawn rate by 3x (If available at the table)`,
    desc_detail: '블랙 마켓의 은밀한 자금 세탁 루트 정보를 미끼로 메가코프 VVIP들을 낚아 올립니다. 리스크를 두려워하지 않는 졸부들을 털어먹을 시간입니다.',
    cost: 12,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'rich_guy', amount: 3 }],
    unlock: { type: 'Bust_enemy', id: 'rich_guy', count: 250 }
  },
  {
    id: 'grinders_mindset',
    tier: 4,
    name: "Grinder's Mindset",
    type: 'BOOST',
    desc: `Increase XP gain by 30% for 3 days.`,
    desc_detail: '그라인더인 당신은 항상 이 마음가짐을 새겨야합니다.',
    cost: 6,
    probability: 0.15,
    duration: 3 * 24 * 60,
    cooldown: 0,
    effect: [{ type: 'xp_boost', amount: 0.3 }],
    unlock: { type: 'played_hand', count: 100000 }
  },
  {
    id: 'rake_discount_high',
    tier: 4,
    name: 'Rake Discount [High]',
    type: 'BOOST',
    desc: `[하이 스테이크] 카지노 중 무작위 한 곳의 레이크가 3일 동안 50%가 됩니다.`,
    desc_detail: '레이크를 절약하기 위해 이벤트를 진행중인 카지노 정보를 수집합니다!',
    cost: 8,
    probability: 0.1,
    duration: 3 * 24 * 60, // 3 days
    cooldown: 0,
    effect: [{ id: 'high', type: 'rake_discount_rnd_mul', amount: 0.5 }],
    unlock: { type: 'paid_rake', amount: 5000000 }
  },
  {
    tier: 5,
    name: 'A bunch of Vagabonds',
    type: 'BOOST',
    desc: 'Always following a [BROKE] x3 to your joined table.',
    desc_detail: '',
    cost: 20,
    probability: 0.1,
    cooldown: 3 * 24 * 60,
    duration: 24 * 60,
    effect: [{ type: 'spawn', id: 'broke', amount: 3 }],
    unlock: { type: 'Bust_enemy', id: 'broke', count: 250 }
  },
  {
    id: 'heavy_security',
    tier: 5,
    name: 'Heavy Security',
    type: 'BOOST',
    desc: `Decrease [Gangster] and [Mafia_Boss] persona spawn rate by 50% (If available at the table)`,
    desc_detail: '뒷골목 보스들도 이 살벌한 보안 앞에서는 알아서 발길을 돌릴 것입니다.',
    cost: 24,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn_rate_mul', id: 'gangster', amount: 0.50 }, { type: 'spawn_rate_mul', id: 'mafia_boss', amount: 0.50 }],
    unlock: { type: 'Bust_enemy', id: 'mafia_boss', count: 125 }
  },
  {
    id: 'rich_guy_hunter_3',
    tier: 5,
    name: 'Money-scenter',
    type: 'BOOST',
    desc: `Add 2 [Rich_Guy] and 1 [Shark] persona to table`,
    desc_detail: '상위 1%를 위한 이벤트로 위장합니다. 눈먼 돈을 들고 온 부자들과, 그 부자들의 돈을 노리는 최상위 포식자 상어가 함께 입장합니다.',
    cost: 32,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn', id: 'rich_guy', amount: 2 }, { type: 'spawn', id: 'shark', amount: 1 }],
    unlock: { type: 'Bust_enemy', id: 'rich_guy', count: 1000 }
  },
  {
    tier: 5,
    name: 'Shark Rival',
    type: 'BOOST',
    desc: 'Always following a [Shark] to your joined table.',
    desc_detail: '테이블에서 가장 위험한 실력자의 옆자리는 항상 당신 차지입니다.',
    cost: 10,
    probability: 0.1,
    duration: 3 * 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn', id: 'shark', amount: 1 }],
    unlock: { type: 'Bust_enemy', id: 'shark', count: 25 }
  },
  {
    id: 'shark_cage',
    tier: 5,
    name: "Shark's Cage",
    type: 'NETWORKING',
    desc: "Host a high-roller game with sharks.\n(Buy-in 2.5M / SB 5k / BB 10k)",
    desc_detail: '이곳의 유일한 규칙은 "살아남아라" 뿐입니다.',
    cost: 30,
    probability: 0.05,
    duration: 4 * 60,
    cooldown: 3 * 24 * 60,
    persona_pools: ['Shark'],
    action: {
      type: 'ACCEPT_INVITE', zone: 'high', location_id: 'high_safe_house', available: 6 // only 6max
    },
    unlock: { type: 'Bust_enemy', id: 'shark', count: 125 }
  },
  {
    id: 'whale_hunter',
    tier: 6,
    name: 'Whale Hunter',
    type: 'BOOST',
    desc: `Increase [Whale] persona spawn rate by 2x (If available at the table)`,
    desc_detail: '초거대 다국적 기업의 비자금 계좌 변동을 실시간으로 감지합니다. 돈을 공기처럼 취급하는 거대한 고래들이 움직이는 물길을 정확하게 짚어냅니다.',
    cost: 24,
    probability: 0.03,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn_rate_mul', id: 'whale', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'whale', count: 50 }
  },
  {
    id: 'house_always_wins',
    tier: 6,
    name: "The 'House' Always Wins?",
    type: 'HACKING',
    desc: 'Players paid rake are in your bankroll for 1 day.',
    desc_detail: '카지노의 메인 프레임 백도어를 뚫고 레이크 징수 계좌를 당신의 암호화 지갑으로 우회시킵니다! 단 하루 동안 당신이 곧 "하우스"가 됩니다.',
    cost: 75,
    probability: 0.03,
    duration: 24 * 60,
    cooldown: 7 * 24 * 60,
    unlock: { type: 'paid_rake', amount: 50000000 },
    effect: [{ type: 'unlock_zone', id: 'special_orbit_lounge' }, { type: 'penalty_amount', id: 'SECURITY_DETECTION', probability: 0.01, amount: 100000 }]
  },
  {
    tier: 6,
    name: 'War of the Gods',
    type: 'NETWORKING',
    desc: "Host a Super high-roller game with [Named_Pro].\n(Buy-in 20M / SB 50K / BB 100K)",
    desc_detail: '신들의 전쟁에에서 살아남을 배짱이 있다면 시도하세요.',
    cost: 100,
    probability: 0.03,
    cooldown: 14 * 24 * 60,
    duration: 4 * 24 * 60,
    unlock: { type: 'Bust_enemy', id: 'Named_Pro', count: 50 },
    action: {
      type: 'ACCEPT_INVITE', zone: 'high', location_id: 'war_of_the_gods', available: 6 // only 6max
    },
  },
  {
    tier: 6,
    name: 'Becoming a Legend',
    type: 'BOOST',
    desc: 'Always following a [Named_Pro] to your joined table.',
    desc_detail: '이미 당신은 전설이 되었습니다. 이제 그들이 당신과 함께 할 껍니다.',
    cost: 15,
    probability: 0.1,
    cooldown: 3 * 24 * 60,
    duration: 1 * 24 * 60,
    unlock: { type: 'Bust_enemy', id: 'Named_Pro', count: 250 },
    effect: [{ type: 'spawn', id: 'Named_Pro', amount: 1 }],
  },
  // For end game (Maybe useful..?)
  {
    id: 'orbit_network_hack',
    tier: 6,
    name: 'Orbit Network Hack',
    type: 'HACKING',
    desc: 'You can join [The Orbit] table. (Only at once)',
    desc_detail: '가장 강력한 ICE로 보호받는 전용 위성 회선, "오르빗 네트워크"를 해킹을 시도합니다. (발각 시 끔찍한 대가를 치르겠지만요)',
    cost: 100,
    probability: 0.03,
    duration: 24 * 60,
    cooldown: 7 * 24 * 60,
    unlock: { type: 'reach_credit', credit: 100000000000 },
    effect: [{ type: 'unlock_zone', id: 'special_orbit_lounge' }, { type: 'penalty_amount', id: 'SECURITY_DETECTION', probability: 0.02, amount: 1000000 }],
  },
];