
import { store } from './store.js';

// Task Definitions
export const AI_TASK_DATA = [
  {
    id: 'neighborhood_game',
    tier: 1,
    name_ko: 'Neighborhood Game',
    name_en: 'Neighborhood Game',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    desc_ko: '동네 호구들을 모아 레이크 없는 홈 게임을 엽니다.\n(레이크 0% / SB 5 / BB 10 / 기본 바이인 200BB)',
    desc_en: 'Gather the neighborhood fish and open a rake-free home game.\n(0% Rake / SB 5 / BB 10 / Min Buy-in 200BB)',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '동네 지인들을 불러서 게임을 진행합니다. 수수료도 아끼고 친목도 다지는 유익한 (아마도?) 시간을 보낼 수 있습니다!',
    desc_detail_en: 'Host a game with your local acquaintances. You can save on fees and enjoy a productive (perhaps?) time socializing!',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 2, // LT per hour
    probability: 0.1, // 10% per hour
    duration: 4 * 60, // 4 hours in minutes after expired
    cooldown: 3 * 24 * 60,
    action: {
      type: 'ACCEPT_INVITE', zone: 'free', location_id: 'free_safe_house', available: 6 // only 6max
    }, // for MessageSystem
  },
  {
    id: 'hand_review',
    tier: 1,
    name_ko: "Hand Review",
    name_en: "Hand Review",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `경험치(XP) 획득량이 10% 증가합니다.`,
    desc_en: `Increases Experience (XP) gain by 10%.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '당신의 지난 플레이를 분석하여 성장을 가속화합니다.',
    desc_detail_en: 'Analyzes your past plays to accelerate your growth.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 3,
    probability: 0.15,
    duration: 1 * 24 * 60,
    cooldown: 0,
    effect: [{ type: 'xp_boost', amount: 0.10 }],
    unlock: { type: 'played_hand', count: 100 }
  },
  {
    id: 'shadow_work',
    tier: 1,
    name_ko: "Sub-net Shadow Work",
    name_en: "Sub-net Shadow Work",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: '이 기능이 활성화 되있는 동안 Agent가 일정 확률로 500CR을 얻습니다.',
    desc_en: 'While this is active, the Agent has a chance to earn 500 CR.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '유휴 연산력을 놀리는 건 자원 낭비입니다. 푼돈이라도 긁어모아야죠',
    desc_detail_en: 'Leaving idle computing power unused is a waste of resources. We must scrape together even the smallest amounts.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 2,
    probability: 0.1,
    duration: 60,
    cooldown: 0,
    effect: [{ type: 'add_bankroll', amount: 500 }],
  },
  {
    id: 'shadow_work_2',
    tier: 3,
    name_ko: "Sub-net Shadow Work Advanced",
    name_en: "Sub-net Shadow Work Advanced",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: '이 기능이 활성화 되있는 동안 Agent가 일정 확률로 2500CR을 얻습니다.',
    desc_en: 'While this is active, the Agent has a chance to earn 2500 CR.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '투입되는 연산 자원에 비해 돈이 되는지 의심이 들기 시작하네요..',
    desc_detail_en: 'It starts making you wonder if the payout is worth the computing power investment...',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 12,
    probability: 0.1,
    duration: 60,
    cooldown: 0,
    effect: [{ type: 'add_bankroll', amount: 2500 }],
    unlock: { type: 'cost_lt', amount: 1000 }
  },
  {
    id: 'shadow_work_3',
    tier: 5,
    name_ko: "Sub-net Shadow Work Master",
    name_en: "Sub-net Shadow Work Master",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'AGENT_WORK',
    desc_ko: '이 기능이 활성화 되있는 동안 Agent가 일정 확률로 10000CR을 얻습니다.',
    desc_en: 'While this is active, the Agent has a chance to earn 10000 CR.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '이게 정녕 최선인지 정말 모르겠지만 일단 돈이 급하니...',
    desc_detail_en: 'I genuinely don\'t know if this is the best idea, but I need the money to flow right now...',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 18,
    probability: 0.05,
    duration: 60,
    cooldown: 0,
    effect: [{ type: 'add_bankroll', amount: 10000 }],
    unlock: { type: 'cost_lt', amount: 10000 }
  },
  {
    id: 'rake_discount_micro',
    tier: 1,
    name_ko: 'Rake Discount [Micro]',
    name_en: 'Rake Discount [Micro]',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `3일 동안 [마이크로 스테이크] 카지노 중 무작위 한 곳의 레이크가 50% 할인됩니다.`,
    desc_en: `For 3 days, applies a 50% rake discount to one random [Micro Stakes] casino.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '레이크를 획기적으로 절약할 수 있는 카지노 이벤트 정보를 찾아냅니다!',
    desc_detail_en: 'Uncovers casino event info that dramatically reduces the rake you pay!',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 3,
    probability: 0.1,
    duration: 3 * 24 * 60, // 3 days
    cooldown: 0,
    effect: [{ id: 'micro', type: 'rake_discount_rnd_mul', amount: 0.5 }],
    unlock: { type: 'paid_rake', amount: 5000 }
  },
  {
    id: 'fish_finder',
    tier: 2,
    name_ko: 'Fish Finder',
    name_en: 'Fish Finder',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `테이블 내 [Fish] 성향 플레이어의 등장 확률이 2배 증가합니다.`,
    desc_en: `Doubles the spawn rate of [Fish] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '호구들이 많이 모이는 장소를 파악하여 은밀히 정보를 수집합니다!',
    desc_detail_en: 'Secretly gathers information to locate where the fish gather the most!',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 5,
    probability: 0.1,
    duration: 4 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'fish', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'fish', count: 25 }
  },
  {
    id: 'rake_discount_low',
    tier: 2,
    name_ko: 'Rake Discount [Low]',
    name_en: 'Rake Discount [Low]',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `3일 동안 [로우 스테이크] 카지노 중 무작위 한 곳의 레이크가 50% 할인됩니다.`,
    desc_en: `For 3 days, applies a 50% rake discount to one random [Low Stakes] casino.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '하위 범죄 조직들의 구역 다툼 데이터를 분석했습니다. 가장 경비가 취약해진 카지노의 수수료망 우회 코드를 확보했습니다!',
    desc_detail_en: 'Analyzes territorial disputes of lower gangs, securing bypass codes for the casino networks with the weakest security at the moment!',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 6,
    probability: 0.1,
    duration: 3 * 24 * 60, // 3 days
    cooldown: 0,
    effect: [{ id: 'low', type: 'rake_discount_rnd_mul', amount: 0.5 }],
    unlock: { type: 'paid_rake', amount: 50000 }
  },
  {
    id: 'mr_call_attractor',
    tier: 2,
    name_ko: 'MR_CALL Attractor',
    name_en: 'MR_CALL Attractor',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [MR_CALL] 성향 플레이어의 등장 확률이 2배 증가합니다.`,
    desc_en: `Doubles the spawn rate of [MR_CALL] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '소위 "패 떠먹기"를 사랑하는 콜링 스테이션들에게 딱 맞는 소프트한 테이블 소문을 흘려 유인합니다.',
    desc_detail_en: 'Spreads rumors of a "soft table" perfectly suited to lure calling stations who love trying to hit their lucky cards.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 6,
    probability: 0.1,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'mr_call', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'mr_call', count: 25 }
  },
  {
    id: 'broke_attractor',
    tier: 2,
    name_ko: 'Broke Attractor',
    name_en: 'Broke Attractor',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Broke] 성향 플레이어의 등장 확률이 2배 증가합니다.`,
    desc_en: `Doubles the spawn rate of [Broke] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '인근 부랑자들에게 맞춤형 스팸 번개를 무차별 살포합니다. 인생 역전을 노리는 불쌍한 영혼들이 모여듭니다.',
    desc_detail_en: 'Indiscriminately spams custom flash-mob invitations to nearby drifters. Poor souls hoping to turn their lives around will gather.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 8,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'broke', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'broke', count: 25 }
  },
  {
    id: 'gambler_attractor',
    tier: 2,
    name_ko: 'Gambler Attractor',
    name_en: 'Gambler Attractor',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Gambler] 성향 플레이어의 등장 확률이 2배 증가합니다.`,
    desc_en: `Doubles the spawn rate of [Gambler] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '인근 도박꾼들에게 특급 도박장 오픈 광고를 살포합니다. 한탕을 노리는 불나방들이 앞다투어 몰려듭니다!',
    desc_detail_en: 'Distributes exclusive gambling ads to nearby gamblers. Moths looking for a quick buck will flock in droves!',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 8,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'gambler', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'gambler', count: 25 }
  },
  {
    id: 'hand_review_2',
    tier: 2,
    name_ko: "Poker Coach",
    name_en: "Poker Coach",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `경험치(XP) 획득량이 20% 증가합니다.`,
    desc_en: `Increases Experience (XP) gain by 20%.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '승률을 높여줄 고급 포커 전략 강의 정보를 수집하고 체계화하여 역량을 한 단계 끌어올립니다.',
    desc_detail_en: 'Collects and organizes advanced poker strategy lectures to take your skills to the next level.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 5,
    probability: 0.07,
    duration: 1 * 24 * 60,
    cooldown: 0,
    effect: [{ type: 'xp_boost', amount: 0.20 }],
    unlock: { type: 'played_hand', count: 1000 }
  },
  {
    id: 'rake_discount_mid',
    tier: 3,
    name_ko: 'Rake Discount [Mid]',
    name_en: 'Rake Discount [Mid]',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `3일 동안 [미드 스테이크] 카지노 중 무작위 한 곳의 레이크가 50% 할인됩니다.`,
    desc_en: `For 3 days, applies a 50% rake discount to one random [Mid Stakes] casino.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '수수료를 덜 떼가는 혜자 프로모션이 진행 중인 미드 스테이크 구장 정보를 수집합니다.',
    desc_detail_en: 'Collects info on mid-stakes venues currently running generous promotions with lower rake.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 12,
    probability: 0.1,
    duration: 3 * 24 * 60, // 3 days
    cooldown: 0,
    effect: [{ id: 'mid', type: 'rake_discount_rnd_mul', amount: 0.5 }],
    unlock: { type: 'paid_rake', amount: 500000 }
  },
  {
    id: 'rich_guy_hunter',
    tier: 3,
    name_ko: 'Rich Guy Hunter',
    name_en: 'Rich Guy Hunter',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Rich_Guy] 성향 플레이어의 등장 확률이 2배 증가합니다.`,
    desc_en: `Doubles the spawn rate of [Rich_Guy] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '지갑은 두껍고 수읽기는 얕은 벼락부자들이 타겟입니다.',
    desc_detail_en: 'Targets nouveau riche players with thick wallets and shallow reading skills.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 20,
    probability: 0.05,
    duration: 4 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'rich_guy', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'rich_guy', count: 25 }
  },
  {
    id: 'maniac_attractor',
    tier: 3,
    name_ko: 'Maniac Attractor',
    name_en: 'Maniac Attractor',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Maniac] 성향 플레이어의 등장 확률이 3배 증가합니다.`,
    desc_en: `Triples the spawn rate of [Maniac] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '"묻고 더블로 가"는 것에 환장한 매니악들을 위한 특별 입장권을 배포합니다.',
    desc_detail_en: 'Distributes special entry passes for maniacs who are crazy about going double or nothing.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 8,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'maniac', amount: 3 }],
    unlock: { type: 'Bust_enemy', id: 'maniac', count: 25 }
  },
  {
    id: 'hand_strategy_plan',
    tier: 3,
    name_ko: "전략 수립",
    name_en: "Strategy Building",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `경험치(XP) 획득량이 30% 증가합니다.`,
    desc_en: `Increases Experience (XP) gain by 30%.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '수많은 지난 플레이 데이터를 복기하고 치밀한 승리 전략을 수립합니다.',
    desc_detail_en: 'Reviews countless past play data and formulates a meticulous winning strategy.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 10,
    probability: 0.05,
    duration: 3 * 24 * 60,
    cooldown: 0,
    effect: [{ type: 'xp_boost', amount: 0.3 }],
    unlock: { type: 'played_hand', count: 100000 }
  },
  {
    id: 'kbt_leader_challenge',
    tier: 3,
    name_ko: "KBT 리더와의 승부",
    name_en: "KBT Leader Challenge",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'NETWORKING',
    desc_ko: `KBT 기지(KBT Base)에서 열리는 특별 게임에 초대받았습니다.`,
    desc_en: `You're invited to a special game held at the KBT Base.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: 'KBT 조직에 당신의 악명이 닿았습니다. 이제 그들의 본거지로 찾아가 조직의 리더와 헤즈업 승부를 벌일 차례입니다.',
    desc_detail_en: 'Your infamy has reached the KBT organization. It is time to head to their stronghold and face their leader in a heads-up match.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 10,
    probability: 0.6,
    duration: 3 * 24 * 60,
    cooldown: 3 * 24 * 60,
    action: {
      type: 'ACCEPT_INVITE', zone: 'middle', location_id: 'middle_kbt_base', available: 2 // only 2max
    },
    unlock: { type: 'Bust_enemy', id: 'gangster', count: 50 }
  },
  {
    id: 'maniac_attractor_2',
    tier: 4,
    name_ko: 'Mad Max',
    name_en: 'Mad Max',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Maniac] 성향 플레이어의 등장 확률이 6배 증가합니다.`,
    desc_en: `Increases the spawn rate of [Maniac] players at your table by 6 times.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '테이블을 아수라장으로 만들 준비 되셨나요?',
    desc_detail_en: 'Are you ready to turn the table into a slaughterhouse?',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 15,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'maniac', amount: 6 }],
    unlock: { type: 'Bust_enemy', id: 'maniac', count: 250 }
  },
  {
    id: 'fish_finder_2',
    tier: 4,
    name_ko: 'Fish Finder II',
    name_en: 'Fish Finder II',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `[Fish] 성향 확률이 4배 증가하지만, 항상 [Quant_Pro] 플레이어가 1명 난입합니다.`,
    desc_en: `Quadruples [Fish] spawn rate, but 1 [Quant_Pro] player will always intrude.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '피쉬들이 득실거리는 꿀통 장소를 알아냈습니다! ...그런데 눈치 빠른 불청객도 냄새를 맡은 모양이군요.',
    desc_detail_en: 'You found a honey pot swarming with fish! ...But it seems a sharp uninvited guest caught the scent as well.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 20,
    probability: 0.05,
    duration: 4 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'fish', amount: 4 }, { type: 'spawn', id: 'Quant_Pro', amount: 1 }],
    unlock: { type: 'Bust_enemy', id: 'fish', count: 25 }
  },
  {
    id: 'enhance_security',
    tier: 4,
    name_ko: 'Enhance Security',
    name_en: 'Enhance Security',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Gangster] 성향 플레이어의 등장 확률이 50% 감소합니다.`,
    desc_en: `Halves the spawn rate of [Gangster] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '가상의 최고급 사설 보안 업체의 패트롤 신호를 송출합니다. 무식한 갱스터들의 헛발질이 눈에 띄게 줄어듭니다.',
    desc_detail_en: 'Broadcasts a patrol signal of a virtual top-tier private security firm. The reckless actions of ignorant gangsters noticeably decrease.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 30,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'gangster', amount: 0.5 }],
    unlock: { type: 'Bust_enemy', id: 'gangster', count: 125 }
  },
  {
    id: 'gambler_attractor_2',
    tier: 4,
    name_ko: 'No Gamble, No Future',
    name_en: 'No Gamble, No Future',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Gambler] 성향 플레이어의 등장 확률이 4배 증가합니다.`,
    desc_en: `Quadruples the spawn rate of [Gambler] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '합법과 불법을 넘나드는 딥 다이브 도박 시뮬레이션 광고를 무차별 전송합니다. "내일이 없는" 진성 갬블러들의 자금이 끊임없이 수혈됩니다.',
    desc_detail_en: 'Indiscriminately sends out deep dive gambling simulation ads that blur the line between legal and illegal. The funds of hardcore gamblers with "no tomorrow" are endlessly funneled in.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 15,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn_rate_mul', id: 'gambler', amount: 4 }],
    unlock: { type: 'Bust_enemy', id: 'gambler', count: 25 }
  },
  {
    id: 'rich_guy_hunter_2',
    tier: 4,
    name_ko: 'Someone with a nose for money',
    name_en: 'Someone with a nose for money',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Rich_Guy] 성향 플레이어의 등장 확률이 3배 증가합니다.`,
    desc_en: `Triples the spawn rate of [Rich_Guy] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '블랙 마켓의 은밀한 자금 세탁 루트 정보를 미끼로 메가코프 VVIP들을 낚아 올립니다. 리스크를 두려워하지 않는 졸부들을 털어먹을 시간입니다.',
    desc_detail_en: 'Uses covert money laundering routes in the black market as bait to reel in megacorp VVIPs. It\'s time to fleece the nouveau riche who aren\'t afraid of a little risk.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 25,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn_rate_mul', id: 'rich_guy', amount: 3 }],
    unlock: { type: 'Bust_enemy', id: 'rich_guy', count: 250 }
  },
  {
    id: 'grinders_mindset',
    tier: 4,
    name_ko: "그라인더의 마음가짐",
    name_en: "Grinder's Mindset",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `최대 스태미나(Max Stamina)가 25 증가합니다.`,
    desc_en: `Increases Max Stamina by 25.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '그라인더인 당신은 항상 이 마음가짐을 가슴 깊이 새겨야 합니다.',
    desc_detail_en: 'As a grinder, you must always engrave this mindset deep in your heart.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 30,
    probability: 0.15,
    duration: 1 * 24 * 60,
    cooldown: 0,
    effect: [{ type: 'max_stamina_boost', amount: 25 }],
    unlock: { type: 'played_hand', count: 250000 }
  },
  {
    id: 'maniac_attractor_3',
    tier: 5,
    name_ko: 'Furiosa',
    name_en: 'Furiosa',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `자신이 입장하는 테이블에 [Maniac] 성향 플레이어가 무조건 3명 난입합니다.`,
    desc_en: `Three [Maniac] players will unconditionally intrude the table you enter.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '이곳의 판돈은 칩이 아니라 목숨값이 될지도 모릅니다. 단단히 대비하십시오.',
    desc_detail_en: 'The stakes here might not be chips, but your life. Brace yourself.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 30,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn', id: 'maniac', amount: 3 }],
    unlock: { type: 'Bust_enemy', id: 'maniac', count: 2500 }
  },

  {
    id: 'rake_discount_high',
    tier: 4,
    name_ko: 'Rake Discount [High]',
    name_en: 'Rake Discount [High]',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `3일 동안 [하이 스테이크] 카지노 중 무작위 한 곳의 레이크가 50% 할인됩니다.`,
    desc_en: `For 3 days, applies a 50% rake discount to one random [High Stakes] casino.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: 'VIP들만 아는 은밀한 카지노 프로모션 코드를 해킹하여 하이 스테이크 구간의 막대한 수수료를 깎아냅니다!',
    desc_detail_en: 'Hacked into a secret casino promotional code known only to VIPs, slicing away the massive fees in the high stakes rooms!',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 15,
    probability: 0.07,
    duration: 3 * 24 * 60, // 3 days
    cooldown: 0,
    effect: [{ id: 'high', type: 'rake_discount_rnd_mul', amount: 0.5 }],
    unlock: { type: 'paid_rake', amount: 5000000 }
  },
  {
    tier: 5,
    name_ko: 'A bunch of Vagabonds',
    name_en: 'A bunch of Vagabonds',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: '자신이 입장하는 테이블에 무조건 [Broke] 성향 플레이어가 3명 따라붙습니다.',
    desc_en: 'Three [Broke] players will unconditionally trail you to the table you enter.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '거리의 지배자가 된 듯한 묘한 기분을 만끽하세요.',
    desc_detail_en: 'Indulge in the strange sensation of feeling like the ruler of the streets.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 40,
    probability: 0.1,
    cooldown: 3 * 24 * 60,
    duration: 24 * 60,
    effect: [{ type: 'spawn', id: 'broke', amount: 3 }],
    unlock: { type: 'Bust_enemy', id: 'broke', count: 250 }
  },
  {
    id: 'heavy_security',
    tier: 5,
    name: 'Heavy Security',
    type: 'BOOST',
    desc: `입장한 테이블에 [Gangster] 및 [Mafia_Boss] 성향 플레이어가 절대 등장하지 않습니다.`,
    desc_detail: '뒷골목 마피아 보스들도 이 살벌한 최첨단 방벽 앞에서는 점잖게 발길을 돌릴 것입니다.',
    cost: 30,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn_rate_mul', id: 'gangster', amount: 0 }, { type: 'spawn_rate_mul', id: 'mafia_boss', amount: 0 }],
    unlock: { type: 'Bust_enemy', id: 'mafia_boss', count: 125 }
  },
  {
    id: 'rich_guy_hunter_3',
    tier: 5,
    name_ko: 'Money-scenter',
    name_en: 'Money-scenter',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장하는 테이블에 [Rich_Guy] 2명과 [Shark] 1명이 무조건 난입합니다.`,
    desc_en: `Two [Rich_Guy] and one [Shark] players will unconditionally intrude the table you enter.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '상위 1%를 위한 익스클루시브 이벤트로 위장합니다. 눈먼 돈을 들고 온 부자들과, 그 돈을 노리는 최상위 포식자가 한 방에 모입니다.',
    desc_detail_en: 'Disguised as an exclusive event for the top 1%. The rich bringing blind money and the apex predators hunting for it will gather in one room.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 25,
    probability: 0.05,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn', id: 'rich_guy', amount: 2 }, { type: 'spawn', id: 'shark', amount: 1 }],
    unlock: { type: 'Bust_enemy', id: 'rich_guy', count: 1000 }
  },
  {
    tier: 5,
    name_ko: 'Shark Rival',
    name_en: 'Shark Rival',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: '자신이 입장하는 테이블에 무조건 [Shark] 성향 플레이어가 1명 난입합니다.',
    desc_en: 'One [Shark] player will unconditionally intrude the table you enter.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '테이블에서 가장 위험한 실력자의 옆자리는 항상 당신의 차지가 될 것입니다.',
    desc_detail_en: 'The seat next to the most dangerous player at the table will always be yours.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 15,
    probability: 0.1,
    duration: 3 * 24 * 60,
    cooldown: 0,
    effect: [{ type: 'spawn', id: 'shark', amount: 1 }],
    unlock: { type: 'Bust_enemy', id: 'shark', count: 25 }
  },
  {
    id: 'shark_cage',
    tier: 5,
    name_ko: "Shark's Cage",
    name_en: "Shark's Cage",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'NETWORKING',
    desc_ko: "하이 스테이크 샤크들과의 스페셜 딥스택 게임을 개최합니다.\n(바이인 2.5M / SB 5k / BB 10k)",
    desc_en: "Host a special deep-stack game with High Stakes Sharks.\n(Buy-in 2.5M / SB 5k / BB 10k)",
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '이 피비린내 나는 곳의 유일한 규칙은 "살아남아라" 뿐입니다.',
    desc_detail_en: 'The only rule in this blood-soaked place is "Survive".',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 30,
    probability: 0.05,
    duration: 4 * 60,
    cooldown: 3 * 24 * 60,
    persona_pools: ['Shark'],
    action: {
      type: 'ACCEPT_INVITE', zone: 'high', location_id: 'high_safe_house', available: 6 // only 6max
    },
    unlock: { type: 'Bust_enemy', id: 'shark', count: 125 }
  },
  {
    id: 'whale_hunter',
    tier: 6,
    name_ko: 'Whale Hunter',
    name_en: 'Whale Hunter',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'BOOST',
    desc_ko: `입장한 테이블에 [Whale] 성향 플레이어의 등장 확률이 2배 증가합니다.`,
    desc_en: `Doubles the spawn rate of [Whale] players at your table.`,
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '거대 코퍼레이션의 비자금 계좌 흐름을 실시간으로 추적합니다. 돈을 공기처럼 쓰는 고래들의 물길을 정확히 짚어냅니다.',
    desc_detail_en: 'Tracks the slush fund account flows of mega-corporations in real-time. Pinpoints the very streams where whales spend money like air.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 40,
    probability: 0.03,
    duration: 24 * 60,
    cooldown: 3 * 24 * 60,
    effect: [{ type: 'spawn_rate_mul', id: 'whale', amount: 2 }],
    unlock: { type: 'Bust_enemy', id: 'whale', count: 50 }
  },
  {
    id: 'house_always_wins',
    tier: 6,
    name_ko: "The 'House' Always Wins?",
    name_en: "The 'House' Always Wins?",
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'HACKING',
    desc_ko: '1일 동안 자신이 속한 카지노 테이블에서 발생하는 모든 플레이어의 레이크(수수료)를 당신이 가져갑니다.',
    desc_en: 'For 1 day, you take all the rake (fees) generated by all players at the casino table you are seated at.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '카지노의 메인 프레임 백도어를 뚫고 레이크 징수 계좌를 당신의 지갑으로 직통 연결합니다! 오늘 하루만큼은 당신이 곧 "하우스"입니다.',
    desc_detail_en: 'Breaches the casino\'s mainframe backdoor and directly connects the rake collection account to your wallet! For today, you are the "House".',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 40,
    probability: 0.03,
    duration: 24 * 60,
    cooldown: 7 * 24 * 60,
    unlock: { type: 'paid_rake', amount: 50000000 },
    effect: [{ type: 'unlock_zone', id: 'special_orbit_lounge' }, { type: 'penalty_amount', id: 'SECURITY_DETECTION', probability: 0.01, amount: 100000 }]
  },
  {
    tier: 6,
    name_ko: 'War of the Gods',
    name_en: 'War of the Gods',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    type: 'NETWORKING',
    desc_ko: "[Named_Pro]들이 모인 최상위 스페셜 하이롤러 게임을 개최합니다.\n(바이인 20M / SB 50K / BB 100K)",
    desc_en: "Host a top-tier special high-roller game gathered with [Named_Pro]s.\n(Buy-in 20M / SB 50K / BB 100K)",
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    desc_detail_ko: '신들의 테이블에서 살아남을 막강한 배짱이 있다면 지금 당장 시도하세요.',
    desc_detail_en: 'If you have the immense guts to survive the table of the gods, try it right now.',
    get desc_detail() { return store.settings.language === 'en' ? this.desc_detail_en : this.desc_detail_ko; },
    cost: 50,
    probability: 0.03,
    cooldown: 14 * 24 * 60,
    duration: 4 * 24 * 60,
    unlock: { type: 'Bust_enemy', id: 'Named_Pro', count: 50 },
    action: {
      type: 'ACCEPT_INVITE', zone: 'high', location_id: 'war_of_the_gods', available: 6 // only 6max
    },
  },
  {
    tier: 6,
    name: 'Becoming a Legend',
    type: 'BOOST',
    desc: '자신이 입장하는 테이블에 무조건 [Named_Pro] 성향 플레이어가 1명 난입합니다.',
    desc_detail: '당신은 이미 전설이 되었습니다. 이제 전설적인 포커 프로들이 지옥 끝까지 당신의 테이블 냄새를 맡고 쫓아올 것입니다.',
    cost: 30,
    probability: 0.1,
    cooldown: 3 * 24 * 60,
    duration: 1 * 24 * 60,
    unlock: { type: 'Bust_enemy', id: 'Named_Pro', count: 250 },
    effect: [{ type: 'spawn', id: 'Named_Pro', amount: 1 }],
  },
  // For end game (Maybe useful..?)
  {
    id: 'orbit_network_hack',
    tier: 6,
    name: 'Orbit Network Hack',
    type: 'HACKING',
    desc: '초호화 위성 카지노 [The Orbit] 궤도망에 딱 한 번 진입합니다.',
    desc_detail: '가장 강력한 보호 방벽(ICE)을 지닌 전용 위성 회선, "오르빗 네트워크" 해킹을 시도합니다. (발각 시 극악의 대가를 치러야 합니다)',
    cost: 50,
    probability: 0.02,
    duration: 24 * 60,
    cooldown: 7 * 24 * 60,
    unlock: { type: 'reach_credit', credit: 100000000000 },
    effect: [{ type: 'unlock_zone', id: 'special_orbit_lounge' }, { type: 'penalty_amount', id: 'SECURITY_DETECTION', probability: 0.01, amount: 1000000 }],
  },
];