import { AGENT_MODULE_DATA, MODULE_EFFECT_TYPE, MODULE_ACTION_TYPE } from './agentModules.js';

export const TASK_EFFECT_TYPE = MODULE_EFFECT_TYPE;
export const TASK_ACTION_TYPE = MODULE_ACTION_TYPE;
export const AI_TASK_DATA = AGENT_MODULE_DATA;