export const CONTRACT_TYPE = {
  BENEFIT_SHARE: 'BENEFIT_SHARE', // your win and lose net share
  BAILOUT: 'BAILOUT', // rescue bankrupt each other
  A_DATE_WITH_YOU: 'A_DATE_WITH_YOU', // a date with you
  COLLUSION: 'COLLUSION', // with you gambling then session end share net worth
  STAKING: 'STAKING' // 그가 스테이커(Staker)가 되어 플레이어에게 자금을 대주고, 게임결과에 대해 수익을 나눕니다.
};
export const ENEMY_ID = {
  MAX: 'Max',
  FLORENCE: 'Florence',
  KATE: 'Kate',
  Sloan: 'Sloan',
  MR_CALL: 'mr_call',
  FISH: 'fish',
  BROKE: 'broke',
  AN_UNKNOWN_WOMAN: 'an_unknown_woman',
  GAMBLER: 'gambler',
  MANIAC: 'maniac',
  RICH_GUY: 'rich_guy',
  GANGSTER: 'gangster',
  NIT: 'nit',
  QUANT_PRO: 'quant_pro',
  OLD_LION: 'old_lion',
  SHARK: 'shark',
  THE_DON: 'the_don',
  THE_WHALE: 'the_whale',
  NAMED_PRO: 'named_pro',
}

export const TYPE_CHANGE_BANKROLL = {
  GAMBLING: 'GAMBLING',
  CRYPTO_TRADE: 'CRYPTO_TRADE',
  RECEIVE: 'RECEIVE',
  PAY_RENT: 'PAY_RENT',
  PAY_INCOME_TAX: 'PAY_INCOME_TAX',
  PAY_FINE: 'PAY_FINE',
  DEBT_REPAYMENT: 'DEBT_REPAYMENT',
  TRANSFER: 'TRANSFER',
  BUY_ITEM: 'BUY_ITEM',
  SELL_ITEM: 'SELL_ITEM',
  AI_AGENT_SUBSCRIPTION: 'AI_AGENT_SUBSCRIPTION',
  AGENT_TASK: 'AGENT_TASK',
  PARTNER_BENEFIT: 'PARTNER_BENEFIT',
  OTHER: 'OTHER',
  ITEM_EFFECT: 'ITEM_EFFECT',
  BRIBE_DEALER: 'BRIBE_DEALER',
  CONTRACT: 'CONTRACT', // 계약 관련
}
export const CHAT_TRIGGERS = {
  GAME_START: 'GAME_START',
  WIN_HUGE: 'WIN_HUGE', // Pot > 40BB
  WIN_SMALL: 'WIN_SMALL',
  LOSE_HUGE: 'LOSE_HUGE',
  LOSE_SMALL: 'LOSE_SMALL',
  CHOP: 'CHOP',
  BLUFF_CAUGHT: 'BLUFF_CAUGHT',
  ALL_IN: 'ALL_IN',
  FOLD: 'FOLD',
  FOLD_STRONG: 'FOLD_STRONG',
  WAITING: 'WAITING',
  BET: 'BET',
  RAISE: 'RAISE',
  RERAISE: 'RERAISE',
  CALL: 'CALL',
  CALL_WEAK: 'CALL_WEAK',
  CALL_GOOD: 'CALL_GOOD',
  CHECK: 'CHECK',
  CHECK_GOOD: 'CHECK_GOOD',
  ELIMINATED_SELF: 'ELIMINATED_SELF',
  ELIMINATED_ENEMY: 'ELIMINATED_ENEMY',
  WIN_HUGE_FOR_PLAYER: 'WIN_HUGE_FOR_PLAYER',
  LOSE_HUGE_FOR_PLAYER: 'LOSE_HUGE_FOR_PLAYER',
  WIN_SMALL_FOR_PLAYER: 'WIN_SMALL_FOR_PLAYER',
  LOSE_SMALL_FOR_PLAYER: 'LOSE_SMALL_FOR_PLAYER',
  ALL_IN_FOR_PLAYER: 'ALL_IN_FOR_PLAYER',
  FOLD_FOR_PLAYER: 'FOLD_FOR_PLAYER',
  WAITING_FOR_PLAYER: 'WAITING_FOR_PLAYER',
  RAISE_SMALL_FOR_PLAYER: 'RAISE_SMALL_FOR_PLAYER',
  RAISE_MEDIUM_FOR_PLAYER: 'RAISE_MEDIUM_FOR_PLAYER',
  RAISE_BIG_FOR_PLAYER: 'RAISE_BIG_FOR_PLAYER',
  CALL_FOR_PLAYER: 'CALL_FOR_PLAYER',
  CHECK_FOR_PLAYER: 'CHECK_FOR_PLAYER',
  BLUFF_CAUGHT_FOR_PLAYER: 'BLUFF_CAUGHT_FOR_PLAYER',
  BIG_POT_TENSION: 'BIG_POT_TENSION',
  WIN_HERO_CALL: 'WIN_HERO_CALL',
};

export const PARTNER_ID = {
  MAX: 'Max',
  FLORENCE: 'Florence',
  KATE: 'Kate',
  SLOAN: 'Sloan',
};

export const PARTNER_STATUS = {
  GAMBLING: 'GAMBLING', // IN CASINO
  SLEEPING: 'SLEEPING',
  EATING: 'EATING',
  DRINKING: 'DRINKING',
  RESTING: 'RESTING',
  IDLE: 'IDLE',
};
export const LOCATION_ID = {
  FREE_HABITAT: "free_habitat",
  FREE_STREET_SHOP: "free_street_shop",
  FREE_STREET_SHOP_WITH_MAX: "free_street_shop_with_max",
  MICRO_WAREHOUSE: "micro_warehouse",
  MICRO_UNDERGROUND_BAR: "micro_underground_bar",
  LOW_NEON_LOUNGE: "low_neon_lounge",
  LOW_UNDERGROUND_CLUB: "low_underground_club",
  LOW_OLD_CASINO: "low_old_casino",
  MIDDLE_UNDERGROUND_CASINO: "middle_underground_casino",
  MIDDLE_HOLDEM_HOUSE: "middle_holdem_house",
  MIDDLE_CASINO_HOTEL: "middle_casino_hotel",
  HIGH_PRO_HOUSE: "high_pro_house",
  HIGH_GRAND_CASINO: "high_grand_casino",
  SPECIAL_ORBIT_LOUNGE: "special_orbit_lounge",
  MICRO_WAREHOUSE_WITH_MAX: "micro_warehouse_with_max",
  LOW_UNDERGROUND_CLUB_MEET_MAX: "low_underground_club_meet_max",
  LOW_UNDERGROUND_CLUB_VIP_ROOM: "low_underground_club_vip_room",
  FREE_HABITAT: 'free_habitat',
  MIDDLE_KBT_BASE: "middle_kbt_base",
  MIDDLE_KBT_VIP_ROOM: "middle_kbt_vip_room",
}
export const ITEM_EFFECT_ID = {
  OLIVE_BRANCH: 'olive_branch',
  STAMINA_REGEN: 'stamina_regen',
  DOPAMINE_ADDICTION: 'dopamine_addiction',
  UNDERGROUND_BAR_INVITE: 'underground_bar_invite',
  ORBIT_TOUR: 'orbit_tour',
  CLUB_MEMBERSHIP: 'club_membership',
  BLACK_CONSUMER: 'black_consumer',
  THE_BUNKER_KEY: 'the_bunker_key',
  HOLDEM_HOUSE_MEMBERSHIP: 'holdem_house_membership',
  ROYAL_ROOM_INVITE: 'royal_room_invite',
  XP_BOOST: 'xp_boost',
  SHOWDOWN_LOSE_REFUND: 'showdown_lose_refund',
  LT_RECOVERY: 'lt_recovery',
  TIME_BANK_PLUS: 'time_bank_plus',
  CHIP_ROUNDING: 'chip_rounding',
  EMERGENCY_FUND: 'emergency_fund',
  RAKE_REDUCTION: 'rake_reduction',
  LT_REGEN_PLUS: 'lt_regen_plus',
  BUY_IN_MULTIPLY: 'buy_in_multiply',
  BLIND_DISCOUNT: 'blind_discount',
  SMOKE_BREAK: 'smoke_break',
  LOYALTY_CARD: 'loyalty_card',
  SESSION_PROFIT_BONUS: 'session_profit_bonus',
  ALLIN_INSURANCE: 'allin_insurance',
  GOLDEN_TOUCH: 'golden_touch',
  QUANTUM_LUCK: 'quantum_luck',
  DIAMOND_COLLECTOR: 'diamond_collector',
  HEART_COLLECTOR: 'heart_collector',
  SPADE_COLLECTOR: 'spade_collector',
  CLUB_COLLECTOR: 'club_collector',
  LUCKY_7_COLLECTOR: 'lucky_7_collector',
  OMEN: 'omen',
  FLUSH_MASTER: 'flush_master',
  FULL_HOUSE_MASTER: 'full_house_master',
  STRAIGHT_FLUSH_MASTER: 'straight_flush_master',
  FOUR_OF_A_KIND_MASTER: 'four_of_a_kind_master',
  ROYAL_FLUSH_MASTER: 'royal_flush_master',
  BLACKJACK_MASTER: 'blackjack_master',
  PAIR_MASTER: 'pair_master',
  SETS_MASTER: 'sets_master',
  COOLER: 'cooler',
  OUTKICKED: 'outkicked',
  FAILURE_IS_MOTHER_OF_SUCCESS: 'failure_is_mother_of_success',
  TILT_RECOVERY: 'tilt_recovery',
  DOUBLE_DOWN: 'double_down',
  GHOST_BET: 'ghost_bet',
  JOY_OF_VITALITY: 'joy_of_vitality',
  LAST_STAND: 'last_stand',
  WINNER_MASTER: 'winner_master',
  COOLDOWN_REDUCTION: 'cooldown_reduction',
  QUANTUM_FOLD: 'quantum_fold',
  SYNAPSE_READING: 'synapse_reading',
  BORN_VILLAIN: 'born_villain',
  INFAMY_BOOST: 'infamy_boost',
  TACTICAL_MINDSET: 'tactical_mindset',
  GOOD_INFLUENCE: 'good_influence',
  SHOW_ME_YOUR_BLUFF: 'show_me_your_bluff',
  STONK: 'stonk',
  BADBEAT_JACKPOT: 'badbeat_jackpot',
  BOMB_POT: 'bomb_pot',
  RND: 'rnd'
};