import { store } from './store.js';

export const ITEM_EFFECT_ID = {
  OLIVE_BRANCH: 'olive_branch',
  STEMINA_REGEN: 'stemina_regen',
  DOPAMINE_ADDICTION: 'dopamine_addiction',
  UNDERGROUND_BAR_INVITE: 'underground_bar_invite',
  ORBIT_TOUR: 'orbit_tour',
  CLUB_MEMBERSHIP: 'club_membership',
  BLACK_CONSUMER: 'black_consumer',
  THE_BUNKER_KEY: 'the_bunker_key',
  HOLDEM_HOUSE_MEMBERSHIP: 'holdem_house_membership',
  ROYAL_ROOM_INVITE: 'royal_room_invite',
  XP_BOOST: 'xp_boost',
  SHOWDOWN_LOSE_REFUND: 'showdown_lose_refund',
  LT_RECOVERY: 'lt_recovery',
  TIME_BANK_PLUS: 'time_bank_plus',
  CHIP_ROUNDING: 'chip_rounding',
  EMERGENCY_FUND: 'emergency_fund',
  RAKE_REDUCTION: 'rake_reduction',
  LT_REGEN_PLUS: 'lt_regen_plus',
  BUY_IN_MULTIPLY: 'buy_in_multiply',
  BLIND_DISCOUNT: 'blind_discount',
  SMOKE_BREAK: 'smoke_break',
  LOYALTY_CARD: 'loyalty_card',
  SESSION_PROFIT_BONUS: 'session_profit_bonus',
  ALLIN_INSURANCE: 'allin_insurance',
  GOLDEN_TOUCH: 'golden_touch',
  QUANTUM_LUCK: 'quantum_luck',
  DIAMOND_COLLECTOR: 'diamond_collector',
  HEART_COLLECTOR: 'heart_collector',
  SPADE_COLLECTOR: 'spade_collector',
  CLUB_COLLECTOR: 'club_collector',
  LUCKY_7_COLLECTOR: 'lucky_7_collector',
  OMEN: 'omen',
  FLUSH_MASTER: 'flush_master',
  FULL_HOUSE_MASTER: 'full_house_master',
  STRAIGHT_FLUSH_MASTER: 'straight_flush_master',
  FOUR_OF_A_KIND_MASTER: 'four_of_a_kind_master',
  ROYAL_FLUSH_MASTER: 'royal_flush_master',
  BLACKJACK_MASTER: 'blackjack_master',
  PAIR_MASTER: 'pair_master',
  SETS_MASTER: 'sets_master',
  COOLER: 'cooler',
  OUTKICKED: 'outkicked',
  FAILURE_IS_MOTHER_OF_SUCCESS: 'failure_is_mother_of_success',
  TILT_RECOVERY: 'tilt_recovery',
  DOUBLE_DOWN: 'double_down',
  GHOST_BET: 'ghost_bet',
  JOY_OF_VITALITY: 'joy_of_vitality',
  LAST_STAND: 'last_stand',
  WINNER_MASTER: 'winner_master',
  COOLDOWN_REDUCTION: 'cooldown_reduction',
  QUANTUM_FOLD: 'quantum_fold',
  SYNAPSE_READING: 'synapse_reading',
  BORN_VILLAIN: 'born_villain',
  INFAMY_BOOST: 'infamy_boost',
  TACTICAL_MINDSET: 'tactical_mindset',
  GOOD_INFLUENCE: 'good_influence',
  SHOW_ME_YOUR_BLUFF: 'show_me_your_bluff',
  STONK: 'stonk',
  BADBEAT_JACKPOT: 'badbeat_jackpot',
  BOMB_POT: 'bomb_pot',
  RND: 'rnd'
};
export const ITEM_EFFECT_DATA = [
  {
    icon: '🌿',
    id: ITEM_EFFECT_ID.OLIVE_BRANCH,
    name_ko: '화해의 나뭇가지',
    name_en: 'Olive Branch',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() {
      return store.settings.language === 'en' ?
        `Upon purchase, increases relationship with partners who have 25 or lower affinity by ${this.value}-${this.valMax}. (One-time use)`
        : `구매시 관계도가 25이하인 파트너들과의 관계 +${this.value}~${this.valMax} (1회성)`;
    },
    effect_name: 'olive_branch',
    valMax: 25,
    value: 5,
    isStackable: true
  },
  {
    icon: '☕',
    id: ITEM_EFFECT_ID.STEMINA_REGEN,
    name_ko: '스태미나 회복',
    name_en: 'Stamina Regen',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 20,
    trigger: ['round_start'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Restores Stamina +${this.value} at round start (Cooldown: ${this.maxCooldown} rounds)` : `라운드 시작시 스테미나 회복 +${this.value} (쿨타임 ${this.maxCooldown} 라운드)`; },
    value: 5,
    isStackable: true
  },
  {
    icon: '💊',
    id: ITEM_EFFECT_ID.DOPAMINE_ADDICTION,
    name_ko: '도파민 중독',
    name_en: 'Dopamine Addiction',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    maxCooldown: 60,
    trigger: ['winAtShowdownWithAllIn', 'loseAtShowdownWithAllIn'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} Stamina upon winning or losing an All-In Showdown. (Cooldown: ${this.maxCooldown} rounds)` : `올인 쇼다운에서 승리 또는 패배시 스테미나 +${this.value} (쿨타임 ${this.maxCooldown} 라운드)`; },
    value: 50,
    isStackable: true
  },
  {
    icon: '📒',
    id: ITEM_EFFECT_ID.UNDERGROUND_BAR_INVITE,
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Upon purchase, grants access to the "Underground Bar".` : `구매시 "지하 바" 이용가능.`; },
    effect_name: 'underground_bar_invite',
    value: 1,
    isStackable: true
  },
  {
    icon: '🚀',
    id: ITEM_EFFECT_ID.ORBIT_TOUR,
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Upon purchase, grants access to "Orbit".` : `구매시 "오르빗" 이용가능.`; },
    effect_name: 'orbit_tour',
    value: 1,
    isStackable: true
  },
  {
    icon: '🆔',
    id: ITEM_EFFECT_ID.CLUB_MEMBERSHIP,
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Upon purchase, grants access to the "H.B.D Club".` : `구매시 "H.B.D 클럽" 이용가능.`; },
    effect_name: 'club_membership',
    value: 1,
    isStackable: true
  },
  {
    icon: '🤑',
    id: ITEM_EFFECT_ID.BLACK_CONSUMER,
    name_ko: '블랙 컨슈머',
    name_en: 'Black Consumer',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Sets Black Market bribe level to ${this.value}. (One-time use)` : `구매시 암상인 뇌물 레벨이 ${this.value}가 됩니다.(1회성)`; },
    effect_name: 'black_consumer',
    value: -5,
    isStackable: true
  },

  {
    icon: '🔑',
    id: ITEM_EFFECT_ID.THE_BUNKER_KEY,
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Grants access to "The Bunker".` : `구매시 "더 벙커" 이용가능.`; },
    effect_name: 'the_bunker_key',
    value: 1,
    isStackable: true
  },
  {
    icon: '⚜️',
    id: ITEM_EFFECT_ID.HOLDEM_HOUSE_MEMBERSHIP,
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Grants access to "Hold'em House".` : `구매시 "홀덤 하우스" 이용가능.`; },
    effect_name: 'holdem_house_membership',
    value: 1,
    isStackable: true
  },
  {
    icon: '🔱',
    id: ITEM_EFFECT_ID.ROYAL_ROOM_INVITE,
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Grants access to "Royal Private Room".` : `구매시 "로얄 프라이빗 룸" 이용가능.`; },
    effect_name: 'royal_room_invite',
    value: 1,
    isStackable: true
  },
  {
    icon: '⚡',
    id: ITEM_EFFECT_ID.XP_BOOST,
    name_ko: '경험치 부스트',
    name_en: 'XP Boost',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP upon winning` : `승리시 경험치 +${Math.floor(this.value * 100)}%`; },
    effect_name: 'xp_boost',
    value: .1,
    isStackable: true
  },

  {
    icon: '🪬',
    id: ITEM_EFFECT_ID.SHOWDOWN_LOSE_REFUND,
    name_ko: '손실 보존',
    name_en: 'Loss Preservation',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 20,
    editable: false,
    trigger: ['loseAtShowdown', 'loseAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `Refunds ${Math.floor(this.value * 100)}% of lost chips upon losing a Showdown (Cooldown: ${this.maxCooldown} rounds)` : `쇼다운 패배 시 손실액 ${Math.floor(this.value * 100)} % 환급 (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: .1,
    isStackable: true
  },
  {
    icon: '🔋',
    id: ITEM_EFFECT_ID.LT_RECOVERY,
    name_ko: 'LT 회복',
    name_en: 'LT Recovery',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['winAtShowdown', 'winAtShowdownWithAllIn'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} LT win at Showdown` : `쇼다운 승리시 LT +${this.value}`; },
    value: 2,
    isStackable: true
  },
  {
    icon: '⏱️',
    id: ITEM_EFFECT_ID.TIME_BANK_PLUS,
    name_ko: '타임 뱅크 추가',
    name_en: 'Time Bank Expansion',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Increases decision time by +${this.value} seconds` : `생각 시간 +${this.value}초`; },
    value: 10,
    isStackable: true
  },
  {
    icon: '👛',
    id: ITEM_EFFECT_ID.CHIP_ROUNDING,
    name_ko: '잔돈 모으기',
    name_en: 'Spare Change',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['round_end'],
    maxCooldown: 5,
    editable: false,
    get desc() { return store.settings.language === 'en' ? `At the end of the round, rounds up your chips to the next ${Math.pow(100, this.value)} units. (Cooldown: ${this.maxCooldown} rounds)` : `라운드 종료 시, 보유 칩을 ${Math.pow(100, this.value)}단위로 올림합니다.(쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '💵',
    id: ITEM_EFFECT_ID.EMERGENCY_FUND,
    name_ko: '비상 자금',
    name_en: 'Emergency Fund',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    maxCooldown: 300,
    cooldown: 0,
    trigger: ['bankrupt'],
    editable: false,
    get desc() {
      return store.settings.language === 'en'
        ? `Gain +${this.valueCalc} Bankroll when bankrupt (Effect increases as level goes up, Cooldown: ${this.maxCooldown} rounds)`
        : `파산 시 뱅크롤 +${this.valueCalc} (효과는 레벨이 올라갈수록 증가, 쿨타임: ${this.maxCooldown} 라운드)`;
    },
    get valueCalc() {
      return store.level * this.value;
    },
    value: 1000,
    isStackable: true
  },
  {
    icon: '✂️',
    id: ITEM_EFFECT_ID.RAKE_REDUCTION,
    name_ko: '수수료 감면',
    name_en: 'Rake Reduction',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Reduces casino rake by -${Math.floor(this.value * 100)}%` : `카지노 레이크 수수료 -${Math.floor(this.value * 100)}%`; },
    value: .25,
    isStackable: true
  },
  {
    icon: '✨',
    id: ITEM_EFFECT_ID.LT_REGEN_PLUS,
    name_ko: 'LT 회복량 증가',
    name_en: 'Enhanced LT Regen',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 5,
    trigger: ['round_start'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Restores +${Math.floor(this.value)} LT at the start of a round (Cooldown: ${this.maxCooldown} rounds)` : `라운드시 시작시 LT +${Math.floor(this.value)} 회복 (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 2,
    isStackable: true
  },
  {
    icon: '⛃',
    id: ITEM_EFFECT_ID.BUY_IN_MULTIPLY,
    name_ko: '바이인 배수',
    name_en: 'Buy-In Multiplier',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Increases buy-in multiplier by +${Math.floor(this.value * 100)}%` : `바이인 배수 +${Math.floor(this.value * 100)}%`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '⛁',
    id: ITEM_EFFECT_ID.BLIND_DISCOUNT,
    name_ko: '블라인드 할인',
    name_en: 'Blind Discount',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['blind_pay'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Reduces blind cost by -${Math.floor(this.value * 100)}%` : `블라인드 비용 -${Math.floor(this.value * 100)}%`; },
    value: .3,
    isStackable: true
  },
  {
    icon: '🚬',
    id: ITEM_EFFECT_ID.SMOKE_BREAK,
    name_ko: '담배 한 대',
    name_en: 'Smoke Break',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    maxCooldown: 15,
    trigger: ['round_start'],
    editable: false,
    get desc() {
      return store.settings.language === 'en'
        ? `Start of round: stamina +${this.value}, LT -${this.value} (Cooldown: ${this.maxCooldown} rounds)`
        : `라운드 시작시 스테미너가 ${this.value}만큼 회복됩니다. 대신 LT가 ${-this.value} 감소합니다. (쿨타임: ${this.maxCooldown} 라운드)`;
    },
    value: 8,
    isStackable: true
  },
  {
    icon: '💳',
    id: ITEM_EFFECT_ID.LOYALTY_CARD,
    name_ko: '단골 우대',
    name_en: 'Loyalty Card',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['purchase'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Increases the max number of items offered by Black Market by +${Math.floor(this.value)}` : `암상인 취급 최대 물품수 +${Math.floor(this.value)}`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '💰',
    id: ITEM_EFFECT_ID.SESSION_PROFIT_BONUS,
    name_ko: '세션 수익 보너스',
    name_en: 'Session Profit Bonus',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['cashout'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Session end: +${Math.floor(this.value * 100)}% of your total profit` : `세션 종료후 최종 수익 +${Math.floor(this.value * 100)}%`; },
    value: .05,
    isStackable: true
  },
  {
    icon: '🪽',
    id: ITEM_EFFECT_ID.ALLIN_INSURANCE,
    name_ko: '인슈어런스',
    name_en: 'Insurance',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['showdownLoseWithAllIn', 'winAtShowdownWithAllIn'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Refunds CR equal to ${Math.floor(this.value * 100)}% of your equity if you lose an All-In Showdown with >70% equity.` : `올인 쇼다운 시점 승률이 70% 이상일때, 패배시 승률의 ${Math.floor(this.value * 100)}% 만큼 CR 보전`; },
    value: .3,
    isStackable: true
  },
  {
    icon: '🖐️',
    id: ITEM_EFFECT_ID.GOLDEN_TOUCH,
    name_ko: '마이더스의 손',
    name_en: 'Midas Touch',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['cashout'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `End of session: Earn bonus bankroll equal to ${Math.floor(this.value * 100)}% of the XP gained.` : `세션 종료후 얻은 경험치의 ${Math.floor(this.value * 100)}% 만큼 추가 뱅크롤 획득`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '🍀',
    id: ITEM_EFFECT_ID.QUANTUM_LUCK,
    name_ko: '양자 행운',
    name_en: 'Quantum Luck',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    maxCooldown: 100,
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `If you win an All-In Showdown with <50% equity, grants a pot bonus of ${Math.floor(this.value * 100)}% (Cooldown: ${this.maxCooldown} rounds)` : `올인 쇼다운 시점 승률이 50% 미만일때 발동되며, 승리시 부족한 승률 만큼의 팟 보너스 ${Math.floor(this.value * 100)}% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 1.0,
    isStackable: true
  },
  {
    icon: '♦️',
    id: ITEM_EFFECT_ID.DIAMOND_COLLECTOR,
    name_ko: '다이아 수집가',
    name_en: 'Diamond Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of Diamonds)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 다이아 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♥️',
    id: ITEM_EFFECT_ID.HEART_COLLECTOR,
    name_ko: '하트 수집가',
    name_en: 'Heart Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of Hearts)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 하트 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♠️',
    id: ITEM_EFFECT_ID.SPADE_COLLECTOR,
    name_ko: '스페이드 수집가',
    name_en: 'Spade Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of Spades)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 스페이드 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♣️',
    id: ITEM_EFFECT_ID.CLUB_COLLECTOR,
    name_ko: '클럽 수집가',
    name_en: 'Club Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of Clubs)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 클럽 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '7️⃣',
    id: ITEM_EFFECT_ID.LUCKY_7_COLLECTOR,
    name_ko: '럭키 7 수집가',
    name_en: 'Lucky 7 Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of 7s)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 7의 개수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.1,
    isStackable: false
  },
  {
    icon: '6️⃣',
    id: ITEM_EFFECT_ID.OMEN,
    name_ko: '징조',
    name_en: 'The Omen',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['lose'],
    get desc() { return store.settings.language === 'en' ? `Pot refund: ${Math.floor(this.value * 100)} * (Number of 6s)% on loss (Cooldown: ${this.maxCooldown} rounds)` : `패배시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 6의 개수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.1,
    isStackable: false
  },
  {
    icon: '🚽',
    id: ITEM_EFFECT_ID.FLUSH_MASTER,
    name_ko: '플러시 전문가',
    name_en: 'Flush Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Flush.` : `플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 5,
    isStackable: true
  },
  {
    icon: '🏠',
    id: ITEM_EFFECT_ID.FULL_HOUSE_MASTER,
    name_ko: '풀 옵션 펜트하우스',
    name_en: 'Full Option Penthouse',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Full House.` : `풀하우스로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 7,
    isStackable: true
  },
  {
    icon: '🌊',
    id: ITEM_EFFECT_ID.STRAIGHT_FLUSH_MASTER,
    name_ko: '스트레이트 플러시 전문가',
    name_en: 'Straight Flush Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Straight Flush.` : `스트레이트 플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 30,
    isStackable: true
  },
  {
    icon: '4️⃣',
    id: ITEM_EFFECT_ID.FOUR_OF_A_KIND_MASTER,
    name_ko: '포카드 전문가',
    name_en: 'Quads Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with Four of a Kind.` : `포 카드로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 15,
    isStackable: true
  },
  {
    icon: '👑',
    id: ITEM_EFFECT_ID.ROYAL_FLUSH_MASTER,
    name_ko: '왕의 물내림',
    name_en: 'Royal Execution',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Royal Flush.` : `로열 플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 100,
    isStackable: true
  },
  {
    icon: '♠',
    id: ITEM_EFFECT_ID.BLACKJACK_MASTER,
    name_ko: '블랙잭 전문가',
    name_en: 'Blackjack Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win', 'lose'],
    get desc() { return store.settings.language === 'en' ? `If your hand is AJ, grants +${Math.floor(this.value * 100)}% XP bonus that persists until your next win.` : `내 핸드가 AJ인 경우, 다음 승리시 까지 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 2.1,
    isStackable: true
  },
  {
    icon: '👯',
    id: ITEM_EFFECT_ID.PAIR_MASTER,
    name_ko: '페어 전문가',
    name_en: 'Pair Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with One Pair or Two Pair.` : `원페어 또는 투페어로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: .22,
    isStackable: true
  },
  {
    icon: '👨‍👨‍👦',
    id: ITEM_EFFECT_ID.SETS_MASTER,
    name_ko: '세트 메뉴',
    name_en: 'Combo Menu',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Set.` : `세트로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 3,
    isStackable: true
  },
  {
    icon: '🥶',
    id: ITEM_EFFECT_ID.COOLER,
    name_ko: '쿨러',
    name_en: 'Cooler',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    maxCooldown: 60,
    editable: false,
    trigger: ['loseAtShowdown', 'loseAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `If you lose a Showdown with a Two Pair or better, grants ${this.value} stamina.` : `쇼다운에서 투페어 이상으로 패배시, 스테미너 ${this.value} 회복`; },
    value: 50,
    isStackable: true
  },
  {
    icon: '🛼',
    id: ITEM_EFFECT_ID.OUTKICKED,
    name_ko: '아, 킥커 차이..',
    name_en: 'Outkicked...',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['loseAtShowdown'],
    get desc() { return store.settings.language === 'en' ? `If you lose a Showdown to the same rank (kicked out), grants +${Math.floor(this.value * 100)}% XP bonus on your next win.` : `쇼다운에서 같은 족보로 패배시, 다음 승리 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '📉',
    id: ITEM_EFFECT_ID.FAILURE_IS_MOTHER_OF_SUCCESS,
    name_ko: '실패는 성공의 어머니',
    name_en: 'Failure is the Mother of Success',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdown', 'winAtShowdownWithAllIn', 'lose'],
    get desc() {
      return store.settings.language === 'en' ?
        `Each defeat grants a +${this.value * 100}% XP bonus for your next Showdown victory. (Current stack: ${Math.floor(this.stackPerValue)}%. This effect stacks and resets upon winning.)` :
        `패배할 때마다 다음 쇼다운 승리시 경험치 보너스 +${this.value * 100}% (현재 누적량: ${Math.floor(this.stackPerValue)}%. 이 효과는 누적되며, 승리할때 초기화.)`;
    },
    value: .2,
    stack: 0,
    get stackPerValue() { return this.value * this.stack * 100; },
    isStackable: true
  },
  {
    icon: '🤯',
    id: ITEM_EFFECT_ID.TILT_RECOVERY,
    name_ko: '틸트 회복',
    name_en: 'Tilt Recovery',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    // maxCooldown: 10,
    editable: false,
    trigger: ['loseAtShowdown', 'loseAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} Stamina upon losing a Showdown.` : `쇼다운 패배 시 스테미나 +${this.value}`; },
    value: 10,
    isStackable: true
  },
  {
    icon: '🎲',
    id: ITEM_EFFECT_ID.DOUBLE_DOWN,
    name_ko: '더블 다운',
    name_en: 'Double Down',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Straight.` : `스트레이트 족보로 승리 시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 3,
    isStackable: true
  },
  {
    icon: '🎴',
    id: ITEM_EFFECT_ID.GHOST_BET,
    name_ko: '유령 배팅',
    name_en: 'Ghost Bet',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    trigger: ['bet'],
    get desc() { return store.settings.language === 'en' ? `Grants a ${Math.floor(this.value * 100)}% chance to refund your bet amount.` : `배팅 시 ${Math.floor(this.value * 100)}% 확률로 배팅 금액을 환급`; },
    value: 0.25,
    isStackable: false
  },
  {
    icon: '😃',
    id: ITEM_EFFECT_ID.JOY_OF_VITALITY,
    name_ko: '승리의 활력',
    name_en: 'Joy of Vitality',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdown', 'winAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} Stamina upon winning a Showdown.` : `쇼다운에서 승리시 스테미나 +${this.value}`; },
    value: 2,
    isStackable: true
  },
  {
    icon: '🚨',
    id: ITEM_EFFECT_ID.LAST_STAND,
    name_ko: '배수의 진',
    name_en: 'Last Stand',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    // maxCooldown: 0,
    editable: false,
    trigger: ['round_start'],
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} LT at round start if your stack is <= 25BB.` : `라운드 시작시, 보유 칩이 25BB 이하일 때 LT +${this.value} 회복`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '🏆',
    id: ITEM_EFFECT_ID.WINNER_MASTER,
    name_ko: '연승 마스터',
    name_en: 'Streak Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['win', 'lose'],
    get desc() {
      return store.settings.language === 'en' ?
        `Grants +${this.value * 100}% XP bonus per win. (Current total: +${Math.floor(this.stackPerValue)}%. This effect accumulates with wins and resets upon losing a Showdown.)` :
        `승리할때 마다 경험치 보너스 +${this.value * 100}% (현재 누적량: +${Math.floor(this.stackPerValue)}%. 이 효과는 승리할때 마다 누적되며, 쇼다운 패배시 초기화.)`;
    },
    value: .03,
    stack: 0,
    get stackPerValue() { return this.value * this.stack * 100; },
    isStackable: true
  },
  {
    icon: '⏳',
    id: ITEM_EFFECT_ID.COOLDOWN_REDUCTION,
    name_ko: '쿨타임 감소',
    name_en: 'Cooldown Reduction',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    trigger: ['round_start'],
    get desc() {
      return store.settings.language === 'en' ?
        `Reduces cooldown of other effects by ${this.value}.` :
        `다른 효과들의 쿨타임을 ${this.value} 감소.`;
    },
    value: 2,
    isStackable: true
  },
  {
    icon: '⚛️',
    id: ITEM_EFFECT_ID.QUANTUM_FOLD,
    name_ko: '양자 폴드',
    name_en: 'Quantum Fold',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    maxCooldown: 25,
    editable: false,
    trigger: ['fold'],
    get desc() { return store.settings.language === 'en' ? `Refunds ${Math.floor(this.value * 100)}% of your wagered chips when folding Pre-Flop. (Cooldown: ${this.maxCooldown} rounds)` : `프리플랍에서 폴드 시 배팅한 칩의 ${Math.floor(this.value * 100)}% 환급 (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.25,
    isStackable: true
  },
  {
    icon: '🧠',
    id: ITEM_EFFECT_ID.SYNAPSE_READING,
    name_ko: '시냅스 리딩',
    name_en: 'Synapse Reading',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    maxCooldown: 30,
    cooldown: 0,
    isActivated: false,
    editable: false,
    trigger: ['round_start'],
    get desc() { return store.settings.language === 'en' ? `Allows you to intercept the thoughts of CPU players this round. (Cooldown: ${this.maxCooldown} rounds)` : `해당 라운드에서 CPU 플레이어들의 생각을 훔쳐볼 수 있다. (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 1,
    isStackable: false
  },
  {
    icon: '👹',
    id: ITEM_EFFECT_ID.BORN_VILLAIN,
    name_ko: '타고난 악당',
    name_en: 'Born Villain',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    maxCooldown: 0,
    cooldown: 0,
    trigger: [],
    get desc() { return store.settings.language === 'en' ? `Infamy gained +${this.value * 100}%. Suspicion gained or lose -${this.value * 25}%` : `악명 획득량 +${this.value * 100}%, 의심 획득/감소량 +${this.value * 25}%`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '😈',
    id: ITEM_EFFECT_ID.INFAMY_BOOST,
    name_ko: '악명 부스트',
    name_en: 'Infamy Boost',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 0,
    cooldown: 0,
    trigger: [],
    get desc() { return store.settings.language === 'en' ? `Infamy gained +${this.value * 100}%` : `악명 획득량 +${this.value * 100}%`; },
    value: 0.5,
    isStackable: true
  },
  {
    icon: '🪖',
    id: ITEM_EFFECT_ID.TACTICAL_MINDSET,
    name_ko: '전술적 사고',
    name_en: 'Tactical Mindset',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    maxCooldown: 0,
    cooldown: 0,
    trigger: [],
    get desc() { return store.settings.language === 'en' ? `Reduces the size of raises you face by ${this.value * 100}%.` : `상대방의 레이즈 크기를 ${this.value * 100}% 감소시킵니다.`; },
    value: 0.1,
    isStackable: true
  },
  // to-do
  {
    icon: '😇',
    id: ITEM_EFFECT_ID.GOOD_INFLUENCE,
    name_ko: '선한 영향력',
    name_en: 'Good Influence',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    maxCooldown: 0,
    cooldown: 0,
    trigger: [],
    get desc() { return store.settings.language === 'en' ? `Infamy gained -${this.value * 100}%` : `악명 획득량 -${this.value * 100}%`; },
    value: 0.2,
    isStackable: true
  },
  {
    icon: '🧐',
    id: ITEM_EFFECT_ID.SHOW_ME_YOUR_BLUFF,
    name_ko: '블러프를 보여줘!',
    name_en: 'Show me your bluff!',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 20,
    trigger: ['round_end'],
    get desc() { return store.settings.language === 'en' ? `At the end of a round, there's a ${this.value * 100}% chance to expose the winner's hand. (Cooldown: ${this.maxCooldown} rounds)` : `라운드 종료 시 ${this.value * 100}% 확률로 최종 승자의 핸드를 강제로 공개합니다. (재사용 대기시간: ${this.maxCooldown} 라운드)`; },
    value: 0.25,
  },
  {
    icon: '🗠',
    id: ITEM_EFFECT_ID.STONK,
    name_ko: '주쉭',
    name_en: 'Stonk',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['cashout'],
    get desc() { return store.settings.language === 'en' ? `At the end of the session, your profit swings by +-1~${100 * this.value}%. Your W$SD(Showdown win rate) becomes the direct probability of a positive outcome.` : `세션 종료 시 최종 수익에 +-1~${100 * this.value}%의 변동폭이 생깁니다. 세션 중 달성한 W$SD(쇼다운 승률) 수치가 '수익 증가'의 확률이 됩니다.`; },
    value: .25,
    isStackable: true
  },
  {
    icon: '🎰',
    id: ITEM_EFFECT_ID.BADBEAT_JACKPOT,
    name_ko: '배드빗 잭팟',
    name_en: 'Badbeat Jackpot',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    cooldown: 0,
    trigger: ['loseAtShowdown', 'loseAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `If you lose at showdown with a Full House or better, you receive a jackpot worth ${this.value}x your current buy-in.` : `풀 하우스 이상 족보로 패배시 바이인의 ${this.value}배를 뱅크롤로 즉시 보상받습니다.` },
    value: 7,
    isStackable: true
  },
  {
    icon: '💣',
    id: ITEM_EFFECT_ID.BOMB_POT,
    name_ko: '봄 팟',
    name_en: 'Bomb Pot',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    maxCooldown: 30,
    trigger: ['round_start'],
    get desc() {
      return store.settings.language === 'en' ?
        `All players pay a ${this.value}BB ante and skip to the flop. (Cooldown: ${this.maxCooldown} rounds)`
        : `라운드 시작 시 모든 플레이어가 ${this.value}BB 엔티를 지불하며, 프리플랍 없이 즉시 플랍으로 진입합니다. (쿨타임: ${this.maxCooldown} 라운드)`
    },
    value: 2,
    isStackable: true
  },
  {
    icon: '❔',
    id: ITEM_EFFECT_ID.RND,
    name_ko: '랜덤',
    name_en: 'Random',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    maxCooldown: 30,
    trigger: [],
    get desc() {
      return store.settings.language === 'en' ?
        `Random effect.`
        : `무작위 효과.`
    },
    value: 1,
    isStackable: true
  }
];

export const getItemEffect = (id) => {
  return ITEM_EFFECT_DATA.find(item => item.id === id);
}

export const getRndItemBucket = () => {
  const rnd = Math.random();
  if (rnd < 0.4) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Common').sort(() => Math.random() - 0.5)[0];
  } else if (rnd < 0.7) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Uncommon').sort(() => Math.random() - 0.5)[0];
  } else if (rnd < 0.9) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Rare').sort(() => Math.random() - 0.5)[0];
  } else {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Epic').sort(() => Math.random() - 0.5)[0];
  }
}