import { getItemEffect, getRndItemBucket } from "./itemsEffect.js";
import { store } from './store.js';
import { ITEM_EFFECT_ID } from './constants.js';

export const ITEM_ID = {
  ADVANCED_EQUITY_CALC: 'advanced_equity_calc',
  ALGORITHMIC_REBATE_TOOL: 'algorithmic_rebate_tool',
  ALLIN_INSURANCE_PLUS: 'allin_insurance_plus',
  ANCIENT_POT: 'ancient_pot',
  ATOMIC_CLOCK_STABILIZER: 'atomic_clock_stabilizer',
  AURUM_PROCESSOR_Z: 'aurum_processor_z',
  BACKUP_BATTERY_SET: 'backup_battery_set',
  BLACK_CONSUMER: 'black_consumer',
  BLACK_MARKET_COURIER_BAG: 'black_market_courier_bag',
  BLACKJACK_SEAL: 'blackjack_seal',
  BLIND_FOLDED_MONK_STATUE: 'blind_folded_monk_statue',
  BLIND_MAKER: 'blind_maker',
  BROKEN_COMPASS: 'broken_compass',
  CAPITALISTS_TOP_HAT: 'capitalists_top_hat',
  CARD_OF_THE_CARD_SHARK: 'card_of_the_card_shark',
  CASINO_INSIDER: 'casino_insider',
  CASINO_INSIDER_NEMESIS: 'casino_insider_nemesis',
  CASINO_PROMOTION_INFO_COLLECTOR: 'casino_promotion_info_collector',
  CD: 'CD',
  CHIPS: 'chips',
  CLUB_MEMBERSHIP: 'club_membership',
  CODE_OF_CREATION: 'code_of_creation',
  CRYO_MINT_DISPENSER: 'cryo_mint_dispenser',
  CRYPTO_COIN_REPLICA: 'crypto_coin_replica',
  CRYSTAL_WINE_GLASS: 'crystal_wine_glass',
  CYBER_PET_COLLAR: 'cyber_pet_collar',
  DECRYPTED_TAX_FILE: 'decrypted_tax_file',
  DESTINY_SLOT_MACHINE: 'destiny_slot_machine',
  DOUBLE_BUY_IN_TICKET: 'double_buy_in_ticket',
  EIFFEL_TOWER: 'eiffel_tower',
  EMERGENCY_EXIT_HAMMER: 'emergency_exit_hammer',
  EMERGENCY_RESERVES: 'emergency_reserves',
  EQUITY_EMERGENCY_ALARM: 'equity_emergency_alarm',
  EV_RECOVERY_CORE: 'ev_recovery_core',
  FAILURE_PHILOSOPHY: 'failure_philosophy',
  FLOPPY_DISK: 'floppy_disk',
  FLUSH_MASTER_RING: 'flush_master_ring',
  FOLDING_FAN: 'folding_fan',
  FORGED_COUPON: 'forged_coupon',
  FULL_HOUSE_BLUEPRINT: 'full_house_blueprint',
  FUSION_CORE_MINI: 'fusion_core_mini',
  OLD_VHS_TAPE: 'old_vhs_tape',
  GOLDEN_DRAGON_STATUE: 'golden_dragon_statue',
  GOLDEN_HAND_STATUE: 'golden_hand_statue',
  GOLDEN_MIRROR: 'golden_mirror',
  GUARDIAN_ANGEL_PROGRAM: 'guardian_angel_program',
  HIGH_ROLLER_BADGE: 'high_roller_badge',
  HOLDEM_HOUSE_MEMBERSHIP: 'holdem_house_membership',
  HOLO_PROJECTED_FLOWER: 'holo_projected_flower',
  JACKPOT_SEED_DATA: 'jackpot_seed_data',
  KHAMSA: 'khamsa',
  LIFE_SAVER_BUOY: 'life_saver_buoy',
  LIQUID_NITROGEN_COOLING: 'liquid_nitrogen_cooling',
  LOADED_DICE: 'loaded_dice',
  LOAN_SHARK_FUNDING: 'loan_shark_funding',
  LOW_STACK_BATTERY: 'low_stack_battery',
  LUCK_OF_THE_DRAW_COIN: 'luck_of_the_draw_coin',
  LUCKY_CAT_GOLD: 'lucky_cat_gold',
  LUCKY_CHARM: 'lucky_charm',
  MASK_OF_JOY_AND_DESPAIR: 'mask_of_joy_and_despair',
  MERCHANTS_SECRET_HANDSHAKE: 'merchants_secret_handshake',
  MIRACLE_WORKER_SCRIPT: 'miracle_worker_script',
  MONOPOLY_PASS: 'monopoly_pass',
  MOVIE_ROUNDERS_DVD: 'movie_rounders_dvd',
  NEURAL_LINK_V3: 'neural_link_v3',
  NEURO_SYNC_HEADBAND: 'neuro_sync_headband',
  OLD_PHONE: 'old_phone',
  OLD_STOPWATCH: 'old_stopwatch',
  OLIVE_BRANCH: 'olive_branch',
  ORBIT_LOUNGE_NETWORK_HACKING: 'orbit_lounge_network_hacking',
  PHOENIX_PROTOCOL: 'phoenix_protocol',
  PRISMATIC_ACHIEVEMENT_CARD: 'prismatic_achievement_card',
  QUANTUM_CRYPTO_WALLET: 'quantum_crypto_wallet',
  QUANTUM_POCKET_WATCH: 'quantum_pocket_watch',
  QUICK_FOLD_MANUAL: 'quick_fold_manual',
  REINCARNATION_PROTOCOL: 'reincarnation_protocol',
  ROGUE_AI_FRAGMENT: 'rogue_ai_fragment',
  ROLLER_SKATES: 'roller_skates',
  ROSARY: 'rosary',
  ROYAL_FLUSH_CROWN: 'royal_flush_crown',
  ROYAL_ROOM_INVITE: 'royal_room_invite',
  RUSTY_PAIR_PENDANT: 'rusty_pair_pendant',
  SAD_EYES: 'sad_eyes',
  SAILING_YACHT: 'sailing_yacht',
  SCRAP_COLLECTOR_GLOVE: 'scrap_collector_glove',
  SECOND_CHANCE_SCRIPT_V2: 'second_chance_script_v2',
  SMOKE_BREAK: 'smoke_break',
  STAR_OF_AFRICA: 'star_of_africa',
  STATUE_OF_LIBERTY: 'statue_of_liberty',
  STONK: 'stonk',
  SUCKER: 'sucker',
  SYNAPSE_READING_PROTOCOL: 'synapse_reading_protocol',
  SYNTHETIC_COFFEE: 'synthetic_coffee',
  TAX_EVASION_MANUAL: 'tax_evasion_manual',
  TAX_HAVEN_VPN: 'tax_haven_vpn',
  THE_BUNKER_KEY: 'the_bunker_key',
  TITANIUM_INSURANCE_POLICY: 'titanium_insurance_policy',
  TO_THE_MARS_ROCKET: 'to_the_mars_rocket',
  UNDERGROUND_BAR_INVITE: 'underground_bar_invite',
  UNIVERSAL_MEMBERSHIP_CARD: 'universal_membership_card',
  VICTORY_STREAK_FLAG: 'victory_streak_flag',
  VIP_LOUNGE_KEYCARD: 'vip_lounge_keycard',
  WPT_CHAMPIONSHIP_MEDAL: 'wpt_championship_medal',
};

// Refactored Name_Ko and Name_En with Cyberpunk Flair & Natural Fit
export const ITEM_DATA = [
  // --- T1 Modules & Hardware ---
  {
    id: ITEM_ID.TO_THE_MARS_ROCKET,
    name_ko: '화성행 탈출 노드',
    name_en: 'Mars Escape Node',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🚀',
    class: 'Item',
    tier: 'T1',
    price: 1200,
    editable: false,
    desc_ko: '화성으로 떠나지 못한 지구에 남겨진 낙오자들을 위한 작은 위로입니다.',
    desc_en: 'A small consolation for the left behind dropouts who couldn\'t depart for Mars.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.XP_BOOST)]
  },
  {
    id: ITEM_ID.SUCKER,
    name_ko: '블러프 스캐너',
    name_en: 'Bluff Scanner Module',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🧐',
    class: 'Item',
    tier: 'T1',
    price: 2000,
    editable: false,
    desc_ko: '"예림이, 그 패 봐봐. 장이지?" 상대의 블러핑 패를 실시간으로 탐지합니다.',
    desc_en: '"Check the card, Yerim. It\'s a Dime, for sure." Detects opponent bluffs in real-time.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.SHOW_ME_YOUR_BLUFF)]
  },
  {
    id: ITEM_ID.CASINO_PROMOTION_INFO_COLLECTOR,
    name_ko: '카지노 수수료 스캐너',
    name_en: 'Casino Rake Scanner',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '📡',
    class: 'Item',
    tier: 'T1',
    price: 3200,
    desc_ko: '프로모션 중인 카지노 정보를 수집하여 수수료 부담을 덜어줍니다.',
    desc_en: 'Collects casino promotion information to reduce rake overhead.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.BLIND_DISCOUNT)]
  },
  {
    id: ITEM_ID.BROKEN_COMPASS,
    name_ko: '수익 추적 칩셋',
    name_en: 'PnL Tracker Chipset',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🧭',
    class: 'Item',
    tier: 'T1',
    price: 1100,
    editable: false,
    desc_ko: '북쪽 대신 돈이 있는 곳을 가리킨다는 소문이 있는 탐지 칩셋입니다.',
    desc_en: 'Rumored to point towards money instead of North.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.SESSION_PROFIT_BONUS)]
  },
  {
    id: ITEM_ID.OLD_VHS_TAPE,
    name_ko: '유휴 연산 데이터 셀',
    name_en: 'Idle Compute Data Cell',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '📼',
    class: 'Item',
    tier: 'T1',
    price: 2800,
    editable: false,
    desc_ko: '여기에 데이터를 담는다구요? 구형 셀을 가동하여 LT 회복을 돕습니다.',
    desc_en: 'You store data on this? Deploys backup compute to speed up LT recovery.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.LT_RECOVERY)]
  },
  {
    id: ITEM_ID.SYNTHETIC_COFFEE,
    name_ko: '합성 카페인 유닛',
    name_en: 'Synthetic Caffeine Unit',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '☕',
    class: 'Item',
    tier: 'T1',
    price: 1200,
    editable: false,
    desc_ko: '진짜 커피콩은 아니지만 에이전트의 스태미나 재생률을 강화합니다.',
    desc_en: 'Not made with real coffee beans, but boosts stamina regeneration.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.STAMINA_REGEN)]
  },
  {
    id: ITEM_ID.OLD_STOPWATCH,
    name_ko: '타임뱅크 딜레이 모듈',
    name_en: 'Time-Bank Delay Module',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '⏱️',
    class: 'Item',
    tier: 'T1',
    price: 1000,
    editable: false,
    desc_ko: '의사결정 연산 시간을 확장해 주는 타이머 모듈입니다.',
    desc_en: 'Looks like it can buy you a little more decision time.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.TIME_BANK_PLUS)]
  },
  {
    id: ITEM_ID.CRYPTO_COIN_REPLICA,
    name_ko: '암호화폐 절상 칩셋',
    name_en: 'Crypto Rounding Chipset',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '₿',
    class: 'Item',
    tier: 'T1',
    price: 1250,
    desc_ko: '한때 누군가의 인생을 구원했던 상징물입니다. 잔여 칩을 정돈해 줍니다.',
    desc_en: 'A plastic replica that auto-rounds fraction chips.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.CHIP_ROUNDING)]
  },
  {
    id: ITEM_ID.SAD_EYES,
    name_ko: '손실 환급 디바이스',
    name_en: 'Loss Refund Device',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🥺',
    class: 'Item',
    tier: 'T1',
    price: 1750,
    editable: false,
    desc_ko: '쇼다운 패배 시 수습 뱅크롤 일부를 환급해 주는 디바이스입니다.',
    desc_en: 'Refunds a portion of lost bankroll upon showdown loss.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.SHOWDOWN_LOSE_REFUND)]
  },
  {
    id: ITEM_ID.SMOKE_BREAK,
    name_ko: '스태미나 쿨링 팩',
    name_en: 'Stamina Cooling Pack',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🚬',
    class: 'Item',
    tier: 'T1',
    price: 2500,
    editable: false,
    desc_ko: '에이전트 과열을 정지시키고 스태미나를 즉시 냉각시킵니다.',
    desc_en: 'Pauses system overheating to cool down agent stamina.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.SMOKE_BREAK)]
  },
  {
    id: ITEM_ID.FAILURE_PHILOSOPHY,
    name_ko: '패배 분석 데이터베이스',
    name_en: 'Loss Analysis Database',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '📚',
    class: 'Item',
    tier: 'T1',
    price: 4500,
    desc_ko: '패배의 쓴맛을 경험치로 승화시키는 분석 데이터베이스입니다.',
    desc_en: 'Database that sublimates the bitter taste of defeat into XP.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.FAILURE_IS_MOTHER_OF_SUCCESS)]
  },
  {
    id: ITEM_ID.RUSTY_PAIR_PENDANT,
    name_ko: '원페어 오버클럭 펜던트',
    name_en: 'One-Pair Overclock Pendant',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '⛓️',
    class: 'Item',
    tier: 'T1',
    price: 3200,
    desc_ko: '원페어 완성 시 승률 연산 가산점을 부여하는 하드웨어 장치입니다.',
    desc_en: 'A relic for those who bet on one pair, boosting equity calculation.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.PAIR_MASTER)]
  },

  // --- T2 Modules & Hardware ---
  {
    id: ITEM_ID.HOLO_PROJECTED_FLOWER,
    name_ko: '홀로그램 멘탈 쿨러',
    name_en: 'Holo-Projected Mental Cooler',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🌸',
    class: 'Item',
    tier: 'T2',
    price: 9000,
    desc_ko: '안정화 홀로그램을 투영하여 LT 재생률을 향상시킵니다.',
    desc_en: 'Projects stabilizing holograms to ease mind and boost LT regen.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.LT_REGEN_PLUS)]
  },
  {
    id: ITEM_ID.TAX_EVASION_MANUAL,
    name_ko: '하우스 절세 알고리즘',
    name_en: 'House Tax Bypass Algorithm',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '📄',
    class: 'Item',
    tier: 'T2',
    price: 7500,
    desc_ko: '하우스의 수수료 징수 루틴을 우회하는 절세 코드입니다.',
    desc_en: 'Contains ingenious ways to save on the House\'s rake.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.RAKE_REDUCTION)]
  },
  {
    id: ITEM_ID.LIQUID_NITROGEN_COOLING,
    name_ko: '액체 질소 수냉 디바이스',
    name_en: 'Liquid Nitrogen Cooling Unit',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '❄️',
    class: 'Item',
    tier: 'T2',
    price: 10000,
    desc_ko: '극저온 수냉 디바이스로 연패의 열기를 식혀줍니다.',
    desc_en: 'Cools down the heat of defeat with cryogenic cooling.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.COOLER)]
  },
  {
    id: ITEM_ID.UNDERGROUND_BAR_INVITE,
    name_ko: '지하 서브넷 접속 키카드',
    name_en: 'Underground Subnet Access Keycard',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '📒',
    class: 'Item',
    tier: 'T2',
    price: 10000,
    isConsumable: true,
    isAccessKey: true,
    desc_ko: '지하 불법 구역 홀덤 바 입장을 허가하는 키카드입니다.',
    desc_en: 'Access keycard granting entry into underground holdem bar venues.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.UNDERGROUND_BAR_INVITE)]
  },
  {
    id: ITEM_ID.CLUB_MEMBERSHIP,
    name_ko: '네온 라운지 VIP 암호 키',
    name_en: 'Neon Lounge VIP Cipher Key',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🆔',
    class: 'Item',
    tier: 'T3',
    price: 25000,
    isConsumable: true,
    isAccessKey: true,
    desc_ko: '상위 클럽 구역의 게이트웨이를 해킹하여 입장 패스를 생성합니다.',
    desc_en: 'Encrypted cipher key generating entry passes into neon clubs.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.CLUB_MEMBERSHIP)]
  },
  {
    id: ITEM_ID.THE_BUNKER_KEY,
    name_ko: '"더 벙커" 복제 열쇠',
    name_en: 'Duplicate Key to "The Bunker"',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🔑',
    class: 'Item',
    tier: 'T4',
    price: 50000,
    isConsumable: true,
    isAccessKey: true,
    desc_ko: 'KBT 조직 전용 차단막을 우회하는 복제 열쇠입니다.',
    desc_en: 'Originally a key held by KBT syndicate members, duplicated for black market.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.THE_BUNKER_KEY)]
  },
  {
    id: ITEM_ID.HOLDEM_HOUSE_MEMBERSHIP,
    name_ko: '프로 하우스 회원 뱃지',
    name_en: 'Pro House Membership Badge',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '⚜️',
    class: 'Item',
    tier: 'T5',
    price: 100000,
    isConsumable: true,
    isAccessKey: true,
    desc_ko: '하이롤러 하우스 카지노 전용 회원 인증 뱃지 모듈입니다.',
    desc_en: 'Membership badge certifying access to high-roller holdem houses.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.HOLDEM_HOUSE_MEMBERSHIP)]
  },
  {
    id: ITEM_ID.ROYAL_ROOM_INVITE,
    name_ko: '로열 VIP 라운지 뱃지',
    name_en: 'Royal VIP Lounge Badge',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🔱',
    class: 'Item',
    tier: 'T6',
    price: 250000,
    isConsumable: true,
    isAccessKey: true,
    desc_ko: '최고 VVIP 카드룸 진입을 허가하는 암호화 인장 뱃지입니다.',
    desc_en: 'Royal membership badge permitting entry into VVIP cardrooms.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.ROYAL_ROOM_INVITE)]
  },
  {
    id: ITEM_ID.EMERGENCY_RESERVES,
    name_ko: '비상 예비금 세이프',
    name_en: 'Emergency Reserve Safe',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '📦',
    class: 'Item',
    tier: 'T2',
    price: 10000,
    desc_ko: '파산 직전 위험 상황에서 가동되는 비상 자금 세이프입니다.',
    desc_en: 'A hidden stash of emergency funds for when things get dangerous.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.EMERGENCY_FUND)]
  },
  {
    id: ITEM_ID.OLD_PHONE,
    name_ko: '암시장 직통 폰',
    name_en: 'Darknet Comms Phone',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '☎️',
    class: 'Item',
    tier: 'T2',
    price: 12500,
    editable: false,
    desc_ko: '암상인에 연결되는 직통 통신 전화를 개설해 출품수를 늘려줍니다.',
    desc_en: 'Establishes direct link to dealer to expand black market stock.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.LOYALTY_CARD)]
  },
  {
    id: ITEM_ID.BACKUP_BATTERY_SET,
    name_ko: '백업 배터리 팩',
    name_en: 'Backup Battery Pack',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🪫',
    class: 'Item',
    tier: 'T2',
    price: 8000,
    desc_ko: '메인 전원 셧다운 시 시스템을 보호하는 백업 배터리입니다.',
    desc_en: 'A solid backup power policy for when main power goes out.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.LAST_STAND)]
  },
  {
    id: ITEM_ID.QUICK_FOLD_MANUAL,
    name_ko: '퀀텀 폴드 엔진',
    name_en: 'Quantum Fold Engine',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '📖',
    class: 'Item',
    tier: 'T2',
    price: 11000,
    desc_ko: '손실을 사전에 차단하는 쾌속 폴드 연산 지침 모듈입니다.',
    desc_en: 'Fast fold calculation manual preventing capital loss.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.QUANTUM_FOLD)]
  },
  {
    id: ITEM_ID.BLACKJACK_SEAL,
    name_ko: '블랙잭 하드웨어 인장',
    name_en: 'Blackjack Hardware Seal',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '♠',
    class: 'Item',
    tier: 'T2',
    price: 9000,
    desc_ko: 'A-J 조합 연산 특화 마이크로 인장 칩셋입니다.',
    desc_en: 'Experience the thrill of A and J combination calculation.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.BLACKJACK_MASTER)]
  },
  {
    id: ITEM_ID.VICTORY_STREAK_FLAG,
    name_ko: '연승 모멘텀 깃발',
    name_en: 'Win Streak Momentum Flag',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🚩',
    class: 'Item',
    tier: 'T2',
    price: 12500,
    desc_ko: '연승 기세를 유지하도록 에이전트 성장을 가속합니다.',
    desc_en: 'Accelerates growth to ensure your winning momentum isn\'t broken.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.WINNER_MASTER)]
  },
  {
    id: ITEM_ID.BLACK_CONSUMER,
    name_ko: '딜러 시스템 교란 봇',
    name_en: 'Dealer Disruption Bot',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🤑',
    class: 'Item',
    tier: 'T2',
    price: 20000,
    isConsumable: true,
    desc_ko: '암상인 네트워크 교란 스팸을 살포하여 리프레시 수수료를 다듬습니다.',
    desc_en: 'Made relationship with dealer worst to scramble refresh cost.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.BLACK_CONSUMER)]
  },
  {
    id: ITEM_ID.LUCK_OF_THE_DRAW_COIN,
    name_ko: '퀀텀 드로우 동전',
    name_en: 'Quantum Draw Coin',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🪙',
    class: 'Item',
    tier: 'T2',
    price: 15000,
    desc_ko: '극소 확률의 아웃츠를 연산하여 역전 승률을 유도합니다.',
    desc_en: 'Makes a seemingly impossible draw victory yours.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.QUANTUM_LUCK)]
  },
  {
    id: ITEM_ID.DOUBLE_BUY_IN_TICKET,
    name_ko: '더블 바이인 패스',
    name_en: 'Double Buy-in Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🎫',
    class: 'Item',
    tier: 'T3',
    price: 15000,
    desc_ko: '테이블 최대 바이인 한도를 2배로 즐기는 VIP 권한 패스입니다.',
    desc_en: 'Enjoy double buy-in limits while receiving VIP treatment.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.BUY_IN_MULTIPLY)]
  },
  {
    id: ITEM_ID.ALLIN_INSURANCE_PLUS,
    name_ko: '올인 세이프 가드 플러스',
    name_en: 'All-In Safe Guard Plus',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🛡️',
    class: 'Item',
    tier: 'T3',
    price: 40000,
    desc_ko: '올인 쇼다운 손실 위험을 정밀 보장해 주는 프리미엄 쉴드 모듈입니다.',
    desc_en: 'Premium guard module that guarantees a wider range of losses.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.ALLIN_INSURANCE), (ITEM_EFFECT_ID.ALLIN_INSURANCE)]
  },
  {
    id: ITEM_ID.OLIVE_BRANCH,
    name_ko: '의심도 초기화 패치',
    name_en: 'Suspicion Reset Patch',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    icon: '🌿',
    class: 'Item',
    tier: 'T3',
    price: 25000,
    isConsumable: true,
    desc_ko: '카지노 구역 내 축적된 의심도를 초기화해 주는 정화 패치입니다.',
    desc_en: 'System patch that purifies accumulated suspicion in sectors.',
    get desc() { return store.settings.language === 'en' ? this.desc_en : this.desc_ko; },
    effects: [(ITEM_EFFECT_ID.OLIVE_BRANCH)]
  }
];

export const hydrateStoreItems = () => {
  if (!store.ownedItems) store.ownedItems = [];
  store.ownedItems = store.ownedItems.map(item => {
    const fullItemData = ITEM_DATA.find(i => i.id === item.id);
    if (fullItemData) {
      return { ...fullItemData, ...item };
    }
    return item;
  });
};
