export const ITEM_EFFECT_DATA = [
  {
    icon: '☕',
    id: 'stemina_regen',
    name: '스태미나 회복',
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 20,
    trigger: ['round_start'],
    editable: false,
    get desc() { return `라운드 시작시 스테미나 회복 +${this.value} (쿨타임 ${this.maxCooldown} 라운드)` },
    value: 5,
    isStackable: true
  },
  {
    icon: '💊',
    id: 'dopamine_addiction',
    name: '도파민 중독',
    rarity: 'Rare',
    cooldown: 0,
    maxCooldown: 60,
    trigger: ['winAtShowdownWithAllIn', 'loseAtShowdownWithAllIn'],
    editable: false,
    get desc() { return `올인 쇼다운에서 승리 또는 패배시 스테미나 +${this.value} (쿨타임 ${this.maxCooldown} 라운드)` },
    value: 50,
    isStackable: true
  },
  {
    icon: '📒',
    id: 'underground_bar_invite',
    name: '입장 권한',
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return `구매시 "지하 바" 이용가능.` },
    effect_name: 'underground_bar_invite',
    value: 1,
    isStackable: true
  },
  {
    icon: '🚀',
    id: 'orbit_tour',
    name: '입장 권한',
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return `구매시 "오르빗" 이용가능.` },
    effect_name: 'orbit_tour',
    value: 1,
    isStackable: true
  },
  {
    icon: '🆔',
    id: 'club_membership',
    name: '입장권한',
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return `구매시 "H.B.D 클럽" 이용가능.` },
    effect_name: 'club_membership',
    value: 1,
    isStackable: true
  },
  {
    icon: '🤑',
    id: 'black_consumer',
    name: '블랙 컨슈머',
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return `구매시 암상인 뇌물 레벨이 ${this.value}가 됩니다.(1회성)` },
    effect_name: 'black_consumer',
    value: -5,
    isStackable: true
  },
  {
    icon: '🔑',
    id: 'the_bunker_key',
    name: '입장권한',
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return `구매시 "더 벙커" 이용가능.` },
    effect_name: 'the_bunker_key',
    value: 1,
    isStackable: true
  },
  {
    icon: '⚜️',
    id: 'holdem_house_membership',
    name: '입장권한',
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return `구매시 "홀덤 하우스" 이용가능.` },
    effect_name: 'holdem_house_membership',
    value: 1,
    isStackable: true
  },
  {
    icon: '🔱',
    id: 'royal_room_invite',
    name: '입장권한',
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return `구매시 "로얄 프라이빗 룸" 이용가능.` },
    effect_name: 'royal_room_invite',
    value: 1,
    isStackable: true
  },
  {
    icon: '⚡',
    id: 'xp_boost',
    name: '경험치 부스트',
    rarity: 'Common',
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return `승리시 경험치 +${Math.floor(this.value * 100)}%` },
    effect_name: 'xp_boost',
    value: .1,
    isStackable: true
  },

  {
    icon: '🪬',
    id: 'showdown_lose_refund',
    name: '손실 보존',
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 20,
    editable: false,
    trigger: ['loseAtShowdown', 'loseAtShowdownWithAllIn'],
    get desc() { return `쇼다운 패배 시 손실액 ${Math.floor(this.value * 100)} % 환급 (쿨타임: ${this.maxCooldown} 라운드)` },
    value: .1,
    isStackable: true
  },
  {
    icon: '💾',
    id: 'lt_recovery',
    name: 'LT 회복',
    rarity: 'Common',
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return `승리시 LT +${this.value}` },
    value: 1,
    isStackable: true
  },
  {
    icon: '⏱️',
    id: 'time_bank_plus',
    name: '타임 뱅크 추가',
    rarity: 'Common',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return `생각 시간 +${this.value}초` },
    value: 10,
    isStackable: true
  },
  {
    icon: '👛',
    id: 'chip_rounding',
    name: '잔돈 모으기',
    rarity: 'Common',
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return `승리 시 본인 배팅 총액을 ${Math.pow(10, this.value)}단위로 올림하여 획득합니다.` },
    value: 1,
    isStackable: true
  },
  {
    icon: '💵',
    id: 'initial_bankroll_bonus',
    name: '초기 자금 보너스',
    rarity: 'Uncommon',
    maxCooldown: 300,
    cooldown: 0,
    trigger: ['bankrupt'],
    editable: false,
    get desc() { return `파산 시 다음 초기 자금 +${Math.floor(this.value * 100)}% (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 1.0,
    isStackable: true
  },
  {
    icon: '✂️',
    id: 'rake_reduction',
    name: '수수료 감면',
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return `카지노 레이크 수수료 -${Math.floor(this.value * 100)}%` },
    value: .25,
    isStackable: true
  },
  {
    icon: '✨',
    id: 'lt_regen_plus',
    name: 'LT 회복량 증가',
    rarity: 'Uncommon',
    cooldown: 0,
    maxCooldown: 5,
    trigger: ['round_start'],
    editable: false,
    get desc() { return `라운드시 시작시 LT +${Math.floor(this.value)} 회복 (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 1,
    isStackable: true
  },
  {
    icon: '⛃',
    id: 'buy_in_multiply',
    name: '바이인 배수',
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return `바이인 배수 +${Math.floor(this.value * 100)}%` },
    value: 1,
    isStackable: true
  },
  {
    icon: '🏷️',
    id: 'blind_discount',
    name: '블라인드 할인',
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['blind_pay'],
    editable: false,
    get desc() { return `블라인드 비용 -${Math.floor(this.value * 100)}%` },
    value: .3,
    isStackable: true
  },
  {
    icon: '💳',
    id: 'loyalty_card',
    name: '단골 우대',
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['purchase'],
    editable: false,
    get desc() { return `암상인 취급 최대 물품수 +${Math.floor(this.value)}` },
    value: 1,
    isStackable: true
  },
  {
    icon: '💰',
    id: 'pot_bonus',
    name: '보너스 배당',
    rarity: 'Common',
    maxCooldown: 10,
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return `승리 시 본인 지분의 ${Math.floor(this.value * 100)}% 만큼 뱅크롤로 입금 (쿨타임: ${this.maxCooldown} 라운드)` },
    value: .05,
    isStackable: true
  },
  {
    icon: '🪽',
    id: 'allin_insurance',
    name: '인슈어런스',
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['showdownLoseWithAllIn', 'winAtShowdownWithAllIn'],
    editable: false,
    get desc() { return `올인 쇼다운 시점 승률이 75% 이상일때, 패배시 승률의 ${Math.floor(this.value * 100)}% 만큼 CR 보전` },
    value: .3,
    isStackable: true
  },
  {
    icon: '🖐️',
    id: 'golden_touch',
    name: '마이더스의 손',
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['gainXP'],
    editable: false,
    get desc() { return `획득하는 경험치의 ${Math.floor(this.value * 100)}% 만큼의 CR이 뱅크롤에 추가됩니다.` },
    value: 1,
    isStackable: true
  },
  {
    icon: '🍀',
    id: 'quantum_luck',
    name: '양자 행운',
    rarity: 'Rare',
    maxCooldown: 100,
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdownWithAllIn'],
    get desc() { return `올인 쇼다운 시점 승률이 50% 미만일때 발동되며, 승리시 부족한 승률 만큼의 팟 보너스 ${Math.floor(this.value * 100)}% (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 1.0,
    isStackable: true
  },
  {
    icon: '♦️',
    id: 'diamond_collector',
    name: '다이아 수집가',
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 다이아 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♥️',
    id: 'heart_collector',
    name: '하트 수집가',
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 하트 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♠️',
    id: 'spade_collector',
    name: '스페이드 수집가',
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 스페이드 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♣️',
    id: 'club_collector',
    name: '클럽 수집가',
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 클럽 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '7️⃣',
    id: 'lucky_7_collector',
    name: '럭키 7 수집가',
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 7의 개수)% (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 0.1,
    isStackable: false
  },
  {
    icon: '6️⃣',
    id: 'omen',
    name: '징조',
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['lose'],
    get desc() { return `패배시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 6의 개수)% (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 0.1,
    isStackable: false
  },
  {
    icon: '🚽',
    id: 'flush_master',
    name: '플러시 전문가',
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    trigger: ['win'],
    get desc() { return `플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: 2,
    isStackable: true
  },
  {
    icon: '🏠',
    id: 'full_house_master',
    name: '풀 옵션 펜트하우스',
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return `풀하우스로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: 3,
    isStackable: true
  },
  {
    icon: '🌊',
    id: 'straight_flush_master',
    name: '스트레이트 플러시 전문가',
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return `스트레이트 플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: 9,
    isStackable: true
  },
  {
    icon: '4️⃣',
    id: 'four_of_a_kind_master',
    name: '포카드 전문가',
    rarity: 'Epic',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return `포 카드로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: 5,
    isStackable: true
  },
  {
    icon: '👑',
    id: 'royal_flush_master',
    name: '왕의 물내림',
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return `로열 플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: 25,
    isStackable: true
  },
  {
    icon: '🃏',
    id: 'blackjack_master',
    name: '블랙잭 전문가',
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win', 'lose'],
    get desc() { return `내 핸드가 AJ인 경우, 다음 승리시 까지 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: 0.21,
    isStackable: true
  },
  {
    icon: '👯',
    id: 'pair_master',
    name: '페어 전문가',
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return `원페어 또는 투페어로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: .1,
    isStackable: true
  },
  {
    icon: '👨‍👨‍👦',
    id: 'sets_master',
    name: '세트 메뉴',
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return `세트로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: .3,
    isStackable: true
  },
  {
    icon: '🥶',
    id: 'cooler',
    name: '쿨러',
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    trigger: ['loseAtShowdown'],
    get desc() { return `쇼다운에서 풀하우스 이상의 족보로 패배시, 다음 승리 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: 3,
    isStackable: true
  },
  {
    icon: '🛼',
    id: 'outkicked',
    name: '아, 킥커 차이..',
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['loseAtShowdown'],
    get desc() { return `쇼다운에서 같은 족보로 패배시, 다음 승리 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: .5,
    isStackable: true
  },
  {
    icon: '📉',
    id: 'failure_is_mother_of_success',
    name: '실패는 성공의 어머니',
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdown', 'winAtShowdownWithAllIn', 'lose'],
    get desc() { return `쇼다운에서 승리시 경험치 보너스 +${Math.floor(this.value * (this.stack + 1) * 100)}%\n(이 효과는 쇼다운에서 패배할 때마다 누적되며, 승리할때 초기화.)` },
    value: .2,
    stack: 0,
    isStackable: true
  },
  {
    icon: '🤯',
    id: 'tilt_recovery',
    name: '틸트 회복',
    rarity: 'Uncommon',
    cooldown: 0,
    // maxCooldown: 10,
    editable: false,
    trigger: ['loseAtShowdown', 'loseAtShowdownWithAllIn'],
    get desc() { return `쇼다운 패배 시 스테미나 +${this.value}` },
    value: 5,
    isStackable: true
  },
  {
    icon: '🎲',
    id: 'double_down',
    name: '더블 다운',
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    trigger: ['win'],
    get desc() { return `스트레이트 족보로 승리 시 경험치 보너스 +${Math.floor(this.value * 100)}%` },
    value: 0.5,
    isStackable: true
  },
  {
    icon: '👻',
    id: 'ghost_bet',
    name: '유령 배팅',
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    trigger: ['bet'],
    get desc() { return `배팅 시 ${Math.floor(this.value * 100)}% 확률로 배팅 금액을 환급` },
    value: 0.15,
    isStackable: false
  },
  {
    icon: '😃',
    id: 'joy_of_victory',
    name: '승리의 기쁨',
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdown', 'winAtShowdownWithAllIn'],
    get desc() { return `쇼다운에서 승리시 스테미나 +${this.value}` },
    value: 2,
    isStackable: true
  },
  {
    icon: '🚨',
    id: 'last_stand',
    name: '배수의 진',
    rarity: 'Uncommon',
    cooldown: 0,
    // maxCooldown: 0,
    editable: false,
    trigger: ['round_start'],
    get desc() { return `라운드 시작시, 보유 칩이 25BB 이하일 때 LT +${this.value} 회복` },
    value: 1,
    isStackable: true
  },
  {
    icon: '🏆',
    id: 'winner_master',
    name: '연승 마스터',
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['win', 'lose'],
    get desc() { return `승리할때 마다 경험치 보너스 +${Math.floor(this.value * (this.stack + 1) * 100)}% (이 효과는 승리할때 마다 누적되며, 쇼다운 패배시 초기화.)` },
    value: 0.03,
    stack: 0,
    isStackable: true
  },
  // {
  //   icon: '🔨',
  //   id: 'blind_sabotage',
  //   name: '블라인드 사보타주',
  //   rarity: 'Rare',
  //   cooldown: 0,
  //   editable: false,
  //   trigger: ['win'],
  //   get desc() { return `승리 시 다음 라운드 상대들의 블라인드 비용 ${this.value * 100}% 증가` },
  //   value: 1,
  //   isStackable: true
  // },
  {
    icon: '⚛️',
    id: 'quantum_fold',
    name: '양자 폴드',
    rarity: 'Uncommon',
    cooldown: 0,
    maxCooldown: 25,
    editable: false,
    trigger: ['fold'],
    get desc() { return `프리플랍에서 폴드 시 배팅한 칩의 ${Math.floor(this.value * 100)}% 환급 (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 0.25,
    isStackable: true
  },
  {
    icon: '🧠',
    id: 'synapse_reading',
    name: '시냅스 리딩',
    rarity: 'Unique',
    maxCooldown: 60,
    cooldown: 0,
    isActivated: false,
    editable: false,
    trigger: ['round_start'],
    get desc() { return `해당 라운드에서 CPU 플레이어들의 생각을 훔쳐볼 수 있다. (쿨타임: ${this.maxCooldown} 라운드)` },
    value: 1,
    isStackable: false
  },
];

export const getItemEffect = (id) => {
  return ITEM_EFFECT_DATA.find(item => item.id === id);
}

export const getRndItemBucket = () => {
  const rnd = Math.random();
  if (rnd < 0.4) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Common').sort(() => Math.random() - 0.5)[0];
  } else if (rnd < 0.7) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Uncommon').sort(() => Math.random() - 0.5)[0];
  } else if (rnd < 0.9) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Rare').sort(() => Math.random() - 0.5)[0];
  } else {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Epic').sort(() => Math.random() - 0.5)[0];
  }
}