import { store } from './store.js';
export const ITEM_EFFECT_DATA = [
  {
    icon: '🌿',
    id: 'olive_branch',
    name_ko: '화해의 나뭇가지',
    name_en: 'Olive Branch',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() {
      return store.settings.language === 'en' ?
        `Upon purchase, increases relationship with partners who have 25 or lower affinity by ${this.value}-${this.valMax}. (One-time use)`
        : `구매시 관계도가 25이하인 파트너들과의 관계 +${this.value}~${this.valMax} (1회성)`;
    },
    effect_name: 'olive_branch',
    valMax: 25,
    value: 5,
    isStackable: true
  },
  {
    icon: '☕',
    id: 'stemina_regen',
    name_ko: '스태미나 회복',
    name_en: 'Stamina Regen',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 20,
    trigger: ['round_start'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Restores Stamina +${this.value} at round start (Cooldown: ${this.maxCooldown} rounds)` : `라운드 시작시 스테미나 회복 +${this.value} (쿨타임 ${this.maxCooldown} 라운드)`; },
    value: 5,
    isStackable: true
  },
  {
    icon: '💊',
    id: 'dopamine_addiction',
    name_ko: '도파민 중독',
    name_en: 'Dopamine Addiction',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    maxCooldown: 60,
    trigger: ['winAtShowdownWithAllIn', 'loseAtShowdownWithAllIn'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} Stamina upon winning or losing an All-In Showdown. (Cooldown: ${this.maxCooldown} rounds)` : `올인 쇼다운에서 승리 또는 패배시 스테미나 +${this.value} (쿨타임 ${this.maxCooldown} 라운드)`; },
    value: 50,
    isStackable: true
  },
  {
    icon: '📒',
    id: 'underground_bar_invite',
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Upon purchase, grants access to the "Underground Bar".` : `구매시 "지하 바" 이용가능.`; },
    effect_name: 'underground_bar_invite',
    value: 1,
    isStackable: true
  },
  {
    icon: '🚀',
    id: 'orbit_tour',
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Upon purchase, grants access to "Orbit".` : `구매시 "오르빗" 이용가능.`; },
    effect_name: 'orbit_tour',
    value: 1,
    isStackable: true
  },
  {
    icon: '🆔',
    id: 'club_membership',
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Upon purchase, grants access to the "H.B.D Club".` : `구매시 "H.B.D 클럽" 이용가능.`; },
    effect_name: 'club_membership',
    value: 1,
    isStackable: true
  },
  {
    icon: '🤑',
    id: 'black_consumer',
    name_ko: '블랙 컨슈머',
    name_en: 'Black Consumer',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Sets Black Market bribe level to ${this.value}. (One-time use)` : `구매시 암상인 뇌물 레벨이 ${this.value}가 됩니다.(1회성)`; },
    effect_name: 'black_consumer',
    value: -5,
    isStackable: true
  },

  {
    icon: '🔑',
    id: 'the_bunker_key',
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Grants access to "The Bunker".` : `구매시 "더 벙커" 이용가능.`; },
    effect_name: 'the_bunker_key',
    value: 1,
    isStackable: true
  },
  {
    icon: '⚜️',
    id: 'holdem_house_membership',
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Grants access to "Hold'em House".` : `구매시 "홀덤 하우스" 이용가능.`; },
    effect_name: 'holdem_house_membership',
    value: 1,
    isStackable: true
  },
  {
    icon: '🔱',
    id: 'royal_room_invite',
    name_ko: '입장 권한',
    name_en: 'Entry Pass',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    trigger: [],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Grants access to "Royal Private Room".` : `구매시 "로얄 프라이빗 룸" 이용가능.`; },
    effect_name: 'royal_room_invite',
    value: 1,
    isStackable: true
  },
  {
    icon: '⚡',
    id: 'xp_boost',
    name_ko: '경험치 부스트',
    name_en: 'XP Boost',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP upon winning` : `승리시 경험치 +${Math.floor(this.value * 100)}%`; },
    effect_name: 'xp_boost',
    value: .1,
    isStackable: true
  },

  {
    icon: '🪬',
    id: 'showdown_lose_refund',
    name_ko: '손실 보존',
    name_en: 'Loss Preservation',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 20,
    editable: false,
    trigger: ['loseAtShowdown', 'loseAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `Refunds ${Math.floor(this.value * 100)}% of lost chips upon losing a Showdown (Cooldown: ${this.maxCooldown} rounds)` : `쇼다운 패배 시 손실액 ${Math.floor(this.value * 100)} % 환급 (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: .1,
    isStackable: true
  },
  {
    icon: '🔋',
    id: 'lt_recovery',
    name_ko: 'LT 회복',
    name_en: 'LT Recovery',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} LT upon winning` : `승리시 LT +${this.value}`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '⏱️',
    id: 'time_bank_plus',
    name_ko: '타임 뱅크 추가',
    name_en: 'Time Bank Expansion',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Increases decision time by +${this.value} seconds` : `생각 시간 +${this.value}초`; },
    value: 10,
    isStackable: true
  },
  {
    icon: '👛',
    id: 'chip_rounding',
    name_ko: '잔돈 모으기',
    name_en: 'Spare Change',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Rounds up your total bet amount to the nearest ${Math.pow(10, this.value)} units when winning.` : `승리 시 본인 배팅 총액을 ${Math.pow(10, this.value)}단위로 올림하여 획득합니다.`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '💵',
    id: 'emergency_fund',
    name_ko: '비상 자금',
    name_en: 'Emergency Fund',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    maxCooldown: 300,
    cooldown: 0,
    trigger: ['bankrupt'],
    editable: false,
    get desc() {
      return store.settings.language === 'en'
        ? `Gain +${this.valueCalc} Bankroll when bankrupt (Effect increases as level goes up, Cooldown: ${this.maxCooldown} rounds)`
        : `파산 시 뱅크롤 +${this.valueCalc} (효과는 레벨이 올라갈수록 증가, 쿨타임: ${this.maxCooldown} 라운드)`;
    },
    get valueCalc() {
      return store.level * this.value;
    },
    value: 1000,
    isStackable: true
  },
  {
    icon: '✂️',
    id: 'rake_reduction',
    name_ko: '수수료 감면',
    name_en: 'Rake Reduction',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Reduces casino rake by -${Math.floor(this.value * 100)}%` : `카지노 레이크 수수료 -${Math.floor(this.value * 100)}%`; },
    value: .25,
    isStackable: true
  },
  {
    icon: '✨',
    id: 'lt_regen_plus',
    name_ko: 'LT 회복량 증가',
    name_en: 'Enhanced LT Regen',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    maxCooldown: 5,
    trigger: ['round_start'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Restores +${Math.floor(this.value)} LT at the start of a round (Cooldown: ${this.maxCooldown} rounds)` : `라운드시 시작시 LT +${Math.floor(this.value)} 회복 (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '⛃',
    id: 'buy_in_multiply',
    name_ko: '바이인 배수',
    name_en: 'Buy-In Multiplier',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['passive'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Increases buy-in multiplier by +${Math.floor(this.value * 100)}%` : `바이인 배수 +${Math.floor(this.value * 100)}%`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '⛁',
    id: 'blind_discount',
    name_ko: '블라인드 할인',
    name_en: 'Blind Discount',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    trigger: ['blind_pay'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Reduces blind cost by -${Math.floor(this.value * 100)}%` : `블라인드 비용 -${Math.floor(this.value * 100)}%`; },
    value: .3,
    isStackable: true
  },
  {
    icon: '🚬',
    id: 'smoke_break',
    name_ko: '담배 한 대',
    name_en: 'Smoke Break',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    maxCooldown: 15,
    trigger: ['round_start'],
    editable: false,
    get desc() {
      return store.settings.language === 'en'
        ? `Start of round: stamina +${this.value}, LT -${this.value} (Cooldown: ${this.maxCooldown} rounds)`
        : `라운드 시작시 스테미너가 ${this.value}만큼 회복됩니다. 대신 LT가 ${-this.value} 감소합니다. (쿨타임: ${this.maxCooldown} 라운드)`;
    },
    value: 8,
    isStackable: true
  },
  {
    icon: '💳',
    id: 'loyalty_card',
    name_ko: '단골 우대',
    name_en: 'Loyalty Card',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    trigger: ['purchase'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Increases the max number of items offered by Black Market by +${Math.floor(this.value)}` : `암상인 취급 최대 물품수 +${Math.floor(this.value)}`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '💰',
    id: 'pot_bonus',
    name_ko: '보너스 배당',
    name_en: 'Pot Bonus',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    maxCooldown: 10,
    cooldown: 0,
    trigger: ['win'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Deposits ${Math.floor(this.value * 100)}% of your pot share into your bankroll on win (Cooldown: ${this.maxCooldown} rounds)` : `승리 시 본인 지분의 ${Math.floor(this.value * 100)}% 만큼 뱅크롤로 입금 (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: .05,
    isStackable: true
  },
  {
    icon: '🪽',
    id: 'allin_insurance',
    name_ko: '인슈어런스',
    name_en: 'Insurance',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['showdownLoseWithAllIn', 'winAtShowdownWithAllIn'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Refunds CR equal to ${Math.floor(this.value * 100)}% of your equity if you lose an All-In Showdown with >75% equity.` : `올인 쇼다운 시점 승률이 75% 이상일때, 패배시 승률의 ${Math.floor(this.value * 100)}% 만큼 CR 보전`; },
    value: .3,
    isStackable: true
  },
  {
    icon: '🖐️',
    id: 'golden_touch',
    name_ko: '마이더스의 손',
    name_en: 'Midas Touch',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    trigger: ['gainXP'],
    editable: false,
    get desc() { return store.settings.language === 'en' ? `Adds CR equivalent to ${Math.floor(this.value * 100)}% of the XP you gain to your bankroll.` : `획득하는 경험치의 ${Math.floor(this.value * 100)}% 만큼의 CR이 뱅크롤에 추가됩니다.`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '🍀',
    id: 'quantum_luck',
    name_ko: '양자 행운',
    name_en: 'Quantum Luck',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    maxCooldown: 100,
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `If you win an All-In Showdown with <50% equity, grants a pot bonus of ${Math.floor(this.value * 100)}% (Cooldown: ${this.maxCooldown} rounds)` : `올인 쇼다운 시점 승률이 50% 미만일때 발동되며, 승리시 부족한 승률 만큼의 팟 보너스 ${Math.floor(this.value * 100)}% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 1.0,
    isStackable: true
  },
  {
    icon: '♦️',
    id: 'diamond_collector',
    name_ko: '다이아 수집가',
    name_en: 'Diamond Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of Diamonds)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 다이아 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♥️',
    id: 'heart_collector',
    name_ko: '하트 수집가',
    name_en: 'Heart Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of Hearts)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 하트 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♠️',
    id: 'spade_collector',
    name_ko: '스페이드 수집가',
    name_en: 'Spade Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of Spades)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 스페이드 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '♣️',
    id: 'club_collector',
    name_ko: '클럽 수집가',
    name_en: 'Club Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of Clubs)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 클럽 문양 수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.05,
    isStackable: false
  },
  {
    icon: '7️⃣',
    id: 'lucky_7_collector',
    name_ko: '럭키 7 수집가',
    name_en: 'Lucky 7 Collector',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Pot bonus: ${Math.floor(this.value * 100)} * (Number of 7s)% on win (Cooldown: ${this.maxCooldown} rounds)` : `승리시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 7의 개수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.1,
    isStackable: false
  },
  {
    icon: '6️⃣',
    id: 'omen',
    name_ko: '징조',
    name_en: 'The Omen',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    maxCooldown: 20,
    cooldown: 0,
    unique: true,
    editable: false,
    trigger: ['lose'],
    get desc() { return store.settings.language === 'en' ? `Pot refund: ${Math.floor(this.value * 100)} * (Number of 6s)% on loss (Cooldown: ${this.maxCooldown} rounds)` : `패배시 본인 지분의 팟 보너스 ${Math.floor(this.value * 100)} * (보드+핸드 6의 개수)% (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.1,
    isStackable: false
  },
  {
    icon: '🚽',
    id: 'flush_master',
    name_ko: '플러시 전문가',
    name_en: 'Flush Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Flush.` : `플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 2,
    isStackable: true
  },
  {
    icon: '🏠',
    id: 'full_house_master',
    name_ko: '풀 옵션 펜트하우스',
    name_en: 'Full Option Penthouse',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Full House.` : `풀하우스로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 3,
    isStackable: true
  },
  {
    icon: '🌊',
    id: 'straight_flush_master',
    name_ko: '스트레이트 플러시 전문가',
    name_en: 'Straight Flush Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Straight Flush.` : `스트레이트 플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 9,
    isStackable: true
  },
  {
    icon: '4️⃣',
    id: 'four_of_a_kind_master',
    name_ko: '포카드 전문가',
    name_en: 'Quads Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Epic',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with Four of a Kind.` : `포 카드로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 5,
    isStackable: true
  },
  {
    icon: '👑',
    id: 'royal_flush_master',
    name_ko: '왕의 물내림',
    name_en: 'Royal Execution',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Royal Flush.` : `로열 플러시로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 25,
    isStackable: true
  },
  {
    icon: '🃏',
    id: 'blackjack_master',
    name_ko: '블랙잭 전문가',
    name_en: 'Blackjack Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win', 'lose'],
    get desc() { return store.settings.language === 'en' ? `If your hand is AJ, grants +${Math.floor(this.value * 100)}% XP bonus that persists until your next win.` : `내 핸드가 AJ인 경우, 다음 승리시 까지 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 0.21,
    isStackable: true
  },
  {
    icon: '👯',
    id: 'pair_master',
    name_ko: '페어 전문가',
    name_en: 'Pair Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with One Pair or Two Pair.` : `원페어 또는 투페어로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: .1,
    isStackable: true
  },
  {
    icon: '👨‍👨‍👦',
    id: 'sets_master',
    name_ko: '세트 메뉴',
    name_en: 'Combo Menu',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    unique: true,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Set.` : `세트로 승리시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: .3,
    isStackable: true
  },
  {
    icon: '🥶',
    id: 'cooler',
    name_ko: '쿨러',
    name_en: 'Cooler',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    trigger: ['loseAtShowdown'],
    get desc() { return store.settings.language === 'en' ? `If you lose a Showdown with a Full House+, grants +${Math.floor(this.value * 100)}% XP bonus on your next win.` : `쇼다운에서 풀하우스 이상의 족보로 패배시, 다음 승리 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 3,
    isStackable: true
  },
  {
    icon: '🛼',
    id: 'outkicked',
    name_ko: '아, 킥커 차이..',
    name_en: 'Outkicked...',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['loseAtShowdown'],
    get desc() { return store.settings.language === 'en' ? `If you lose a Showdown to the same rank (kicked out), grants +${Math.floor(this.value * 100)}% XP bonus on your next win.` : `쇼다운에서 같은 족보로 패배시, 다음 승리 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: .5,
    isStackable: true
  },
  {
    icon: '📉',
    id: 'failure_is_mother_of_success',
    name_ko: '실패는 성공의 어머니',
    name_en: 'Failure is the Mother of Success',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdown', 'winAtShowdownWithAllIn', 'lose'],
    get desc() {
      return store.settings.language === 'en' ?
        `Grants +${Math.floor(this.value * 100)}% XP bonus upon winning a Showdown. (Current total: +${this.stackPerValue}%. This effect accumulates upon losing, resets on valid win.)` :
        `쇼다운에서 승리시 경험치 보너스 +${this.value * 100}% (현재 누적량: ${this.stackPerValue}%. 이 효과는 쇼다운에서 패배할 때마다 누적되며, 승리할때 초기화.)`;
    },
    value: .2,
    stack: 0,
    get stackPerValue() { return this.value * this.stack * 100; },
    isStackable: true
  },
  {
    icon: '🤯',
    id: 'tilt_recovery',
    name_ko: '틸트 회복',
    name_en: 'Tilt Recovery',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    // maxCooldown: 10,
    editable: false,
    trigger: ['loseAtShowdown', 'loseAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} Stamina upon losing a Showdown.` : `쇼다운 패배 시 스테미나 +${this.value}`; },
    value: 5,
    isStackable: true
  },
  {
    icon: '🎲',
    id: 'double_down',
    name_ko: '더블 다운',
    name_en: 'Double Down',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    trigger: ['win'],
    get desc() { return store.settings.language === 'en' ? `Grants +${Math.floor(this.value * 100)}% XP bonus when winning with a Straight.` : `스트레이트 족보로 승리 시 경험치 보너스 +${Math.floor(this.value * 100)}%`; },
    value: 0.5,
    isStackable: true
  },
  {
    icon: '👻',
    id: 'ghost_bet',
    name_ko: '유령 배팅',
    name_en: 'Ghost Bet',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    cooldown: 0,
    editable: false,
    trigger: ['bet'],
    get desc() { return store.settings.language === 'en' ? `Grants a ${Math.floor(this.value * 100)}% chance to refund your bet amount.` : `배팅 시 ${Math.floor(this.value * 100)}% 확률로 배팅 금액을 환급`; },
    value: 0.15,
    isStackable: false
  },
  {
    icon: '😃',
    id: 'joy_of_vitality',
    name_ko: '승리의 활력',
    name_en: 'Joy of Vitality',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    editable: false,
    trigger: ['winAtShowdown', 'winAtShowdownWithAllIn'],
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} Stamina upon winning a Showdown.` : `쇼다운에서 승리시 스테미나 +${this.value}`; },
    value: 2,
    isStackable: true
  },
  {
    icon: '🚨',
    id: 'last_stand',
    name_ko: '배수의 진',
    name_en: 'Last Stand',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    // maxCooldown: 0,
    editable: false,
    trigger: ['round_start'],
    get desc() { return store.settings.language === 'en' ? `Restores +${this.value} LT at round start if your stack is <= 25BB.` : `라운드 시작시, 보유 칩이 25BB 이하일 때 LT +${this.value} 회복`; },
    value: 1,
    isStackable: true
  },
  {
    icon: '🏆',
    id: 'winner_master',
    name_ko: '연승 마스터',
    name_en: 'Streak Master',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Common',
    cooldown: 0,
    editable: false,
    trigger: ['win', 'lose'],
    get desc() {
      return store.settings.language === 'en' ?
        `Grants +${this.value * 100}% XP bonus per win. (Current total: +${this.stackPerValue}%. This effect accumulates with wins and resets upon losing a Showdown.)` :
        `승리할때 마다 경험치 보너스 +${this.value * 100}% (현재 누적량: +${this.stackPerValue}%. 이 효과는 승리할때 마다 누적되며, 쇼다운 패배시 초기화.)`;
    },
    value: .03,
    stack: 0,
    get stackPerValue() { return this.value * this.stack * 100; },
    isStackable: true
  },
  {
    icon: '⏳',
    id: 'cooldown_reduction',
    name_ko: '쿨타임 감소',
    name_en: 'Cooldown Reduction',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Rare',
    cooldown: 0,
    editable: false,
    trigger: ['round_start'],
    get desc() {
      return store.settings.language === 'en' ?
        `Reduces cooldown of other effects by ${this.value}.` :
        `다른 효과들의 쿨타임을 ${this.value} 감소.`;
    },
    value: 2,
    isStackable: true
  },
  {
    icon: '⚛️',
    id: 'quantum_fold',
    name_ko: '양자 폴드',
    name_en: 'Quantum Fold',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Uncommon',
    cooldown: 0,
    maxCooldown: 25,
    editable: false,
    trigger: ['fold'],
    get desc() { return store.settings.language === 'en' ? `Refunds ${Math.floor(this.value * 100)}% of your wagered chips when folding Pre-Flop. (Cooldown: ${this.maxCooldown} rounds)` : `프리플랍에서 폴드 시 배팅한 칩의 ${Math.floor(this.value * 100)}% 환급 (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 0.25,
    isStackable: true
  },
  {
    icon: '🧠',
    id: 'synapse_reading',
    name_ko: '시냅스 리딩',
    name_en: 'Synapse Reading',
    get name() { return store.settings.language === 'en' ? this.name_en : this.name_ko; },
    rarity: 'Unique',
    maxCooldown: 60,
    cooldown: 0,
    isActivated: false,
    editable: false,
    trigger: ['round_start'],
    get desc() { return store.settings.language === 'en' ? `Allows you to intercept the thoughts of CPU players this round. (Cooldown: ${this.maxCooldown} rounds)` : `해당 라운드에서 CPU 플레이어들의 생각을 훔쳐볼 수 있다. (쿨타임: ${this.maxCooldown} 라운드)`; },
    value: 1,
    isStackable: false
  },
];

export const getItemEffect = (id) => {
  return ITEM_EFFECT_DATA.find(item => item.id === id);
}

export const getRndItemBucket = () => {
  const rnd = Math.random();
  if (rnd < 0.4) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Common').sort(() => Math.random() - 0.5)[0];
  } else if (rnd < 0.7) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Uncommon').sort(() => Math.random() - 0.5)[0];
  } else if (rnd < 0.9) {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Rare').sort(() => Math.random() - 0.5)[0];
  } else {
    return ITEM_EFFECT_DATA.filter(item => item.rarity === 'Epic').sort(() => Math.random() - 0.5)[0];
  }
}