import { store } from './store.js';

const lore_spam_message = [
  {
    "type": "SPAM",
    "sender": "Lucky_777 Bot",
    "title_ko": "⚡ 100% 승률 보장! 화성행 티켓이 눈앞에!",
    "title_en": "⚡ 100% Win Rate Guaranteed! Mars Ticket in Sight!",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "아직도 운에 맡기십니까? 최신 AI 'DeepMind-Z' 해킹 툴이 상대의 패를 꿰뚫어 봅니다. 단돈 5,000 CR! 지금 바로 다운로드하세요! (보안 경고: NetWatch 추적을 피하려면 VPN 필수)",
    "body_en": "Are you still leaving it to luck? The latest AI 'DeepMind-Z' hacking tool sees right through your opponent's hand. Only 5,000 CR! Download now! (Security Warning: VPN required to avoid NetWatch tracking)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.03
  },
  {
    "type": "SPAM",
    "sender": "Prince of Nigeria",
    "title_ko": "[Help] 왕위 계승 자금 지원 요청",
    "title_en": "[Help] Request for Royal Succession Funding",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "친애하는 친구여, 나는 나이지리아의 왕자입니다. 200년 전 냉동된 나의 조상이 깨어났습니다. 그의 계좌 동결을 풀기 위해 1,000 CR만 보내주시면 화성 이주권을 선물로 드리겠습니다.",
    "body_en": "Dear friend, I am a Prince of Nigeria. My ancestor, frozen 200 years ago, has awakened. If you send just 1,000 CR to unfreeze his account, I will gift you a Mars immigration ticket.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.01
  },
  {
    "type": "SPAM",
    "sender": "Adult_Bot_XXX",
    "title_ko": "♥ 외로운 밤, 위로가 필요하신가요?",
    "title_en": "♥ Lonely night, need some comfort?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "최신형 안드로이드 'Pleasure-Model T-800' 대기 중. 다운타운 모텔 304호. 현금(CR)만 받습니다. *경고: 바이러스 감염 주의*",
    "body_en": "Latest Android 'Pleasure-Model T-800' on standby. Downtown Motel Room 304. Cash (CR) only. *Warning: Beware of virus infection*",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "SPAM",
    "sender": "Unknown Sender",
    "title_ko": "I KNOW WHAT YOU DID",
    "title_en": "I KNOW WHAT YOU DID",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "지난 밤, 뒷골목 게임에서 네가 쓴 속임수... 내가 다 봤어. 신고 당하기 싫으면 입금해. 510392-102-4912 (10,000 CR)",
    "body_en": "That trick you pulled in the back-alley game last night... I saw everything. Transfer the money if you don't won't to be reported. 510392-102-4912 (10,000 CR)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.02
  },
  {
    "type": "LORE",
    "sender": "N54 News",
    "title_ko": "[속보] 시냅스(Synapse) 주가 폭락, 왜?",
    "title_en": "[Breaking] Synapse Stock Plummets, Why?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "오늘 아침 시냅스 본사 연구소에서 발생한 '생화학 유출 사고' 루머로 주가가 15% 급락했습니다. 사측은 단순한 시스템 오작동이라 해명했지만, 시민들의 불안은 커지고 있습니다.",
    "body_en": "Stock prices plummeted by 15% due to rumors of a 'biochemical leak accident' at the Synapse headquarters lab this morning. The company explained it as a simple system malfunction, but citizens' anxiety is growing.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 3
  },
  {
    "type": "LORE",
    "sender": "N54 News",
    "title_ko": "[사회] '배급(Rations)' 중단 사태 장기화",
    "title_en": "[Society] Long-term 'Rations' Suspension",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "C구역 슬럼가의 기본소득 배급 시스템이 해킹으로 인해 3일째 마비되었습니다. 옴니 다이내믹스는 폭동 진압용 드론 'Peacemaker'를 해당 구역에 급파했습니다.",
    "body_en": "The basic income ration system in the Sector C slums has been paralyzed for 3 days due to hacking. Omni Dynamics has hastily dispatched riot control drones 'Peacemaker' to the area.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 7
  },
  {
    "type": "LORE",
    "sender": "WNS Weather",
    "title_ko": "[날씨] 강한 산성비 주의보",
    "title_en": "[Weather] Heavy Acid Rain Warning",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "내일은 pH 3.5 수준의 강한 산성비가 내릴 예정입니다. 외출 시 반드시 보호 장비를 착용하시고, 노출된 피부나 크롬 부품은 즉시 중화제로 세척하십시오.",
    "body_en": "Strong acid rain with a pH level of 3.5 is expected tomorrow. Be sure to wear protective gear when going out, and immediately wash exposed skin or chrome parts with a neutralizer.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 10
  },
  {
    "type": "LORE",
    "sender": "Synapse Corp PR",
    "title_ko": "[캠페인] 감정은 통제될 때 아름답습니다.",
    "title_en": "[Campaign] Emotions are beautiful when controlled.",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "불필요한 분노와 슬픔이 당신의 효율성을 떨어뜨리나요? 시냅스의 'Serenity' 감정 조절 모듈을 설치하세요. 언제나 평온한 멘탈이 승리의 지름길입니다.",
    "body_en": "Do unnecessary anger and sadness lower your efficiency? Install Synapse's 'Serenity' emotion control module. A calm mentality at all times is the shortcut to victory.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "SOCIAL",
    "sender": "A.Jones",
    "title_ko": "쓸만한 '그라인더'를 찾고 있어",
    "title_en": "Looking for a useful 'Grinder'",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "소문을 좀 들었네. 자네가 요즘 테이블에서 꽤 짭짤하게 챙긴다고? 내 클라이언트가 조용한 해결사를 원해. 관심 있으면 연락해. - A.Jones",
    "body_en": "I've heard some rumors. Are you making a decent profit at the tables lately? My client wants a quiet fixer. Contact me if interested. - A.Jones",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_rep": 50
  },
  {
    "type": "SOCIAL",
    "sender": "Neon Rats Leader",
    "title_ko": "쥐구멍에도 볕은 든다",
    "title_en": "Every dog has its day",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "다운타운 놈들이 우리 구역 물을 흐리고 있어. 네가 그쪽 카지노에 가서 본떼를 좀 보여줄 수 있나? 우리 정보원들이 놈들의 패 패턴을 좀 흘려줄 수도 있는데 말이야.",
    "body_en": "The downtown bastards are muddying the waters in our district. Can you go to their casino and show them a lesson? Our informants might be able to leak their hand patterns.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_zone": "low_neon_lounge"
  },
  {
    "type": "SOCIAL",
    "sender": "Circuit Breakers",
    "title_ko": "기계 노예가 될 텐가?",
    "title_en": "Are you going to be a machine slave?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "네 몸에 박힌 그 크롬 덩어리들이 널 구원할 거라 믿나? 진정한 인간성은 육체에서 나온다. 시냅스 놈들의 서버를 태워버리는 날, 우리와 함께하자.",
    "body_en": "Do you believe those chunks of chrome embedded in your body will save you? True humanity comes from the flesh. The day we burn the Synapse bastards' servers, join us.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_augment": true
  },
  {
    "sender": "Zenith Financial",
    "title_ko": "[독촉] 신용 등급 하락 경고",
    "title_en": "[Urgent] Credit Rating Drop Warning",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "귀하의 최근 소득 신고 내역이 불투명합니다. 즉시 세금을 납부하지 않으면, 귀하의 계좌가 동결되고 모든 자산이 몰수될 수 있습니다. 이것은 마지막 경고입니다.",
    "body_en": "Your recent income report is opaque. If you do not pay taxes immediately, your account will be frozen and all assets may be confiscated. This is your final warning.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_tax_late": true
  },
  {
    "type": "LORE",
    "sender": "Unknown",
    "title_ko": "...",
    "title_en": "...",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "01001000 01000101 01001100 01010000 00100000 01001101 01000101 (이 메시지는 자동으로 소멸됩니다)",
    "body_en": "01001000 01000101 01001100 01010000 00100000 01001101 01000101 (This message will self-destruct)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.001
  },
  {
    "type": "LORE",
    "sender": "Future Self?",
    "title_ko": "10년 전의 나에게",
    "title_en": "To me from 10 years ago",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "이봐, 2047년 10월 25일 저녁 8시. 퀸스 하이 플러시에 절대 올인하지 마. 그 판은 함정이야. 믿어. 난 이미 후회하고 있으니까.",
    "body_en": "Hey, October 25, 2047, 8:00 PM. Never go all-in on a Queen-high flush. That hand is a trap. Believe me. I'm already regretting it.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
  },
  {
    "type": "SPAM",
    "sender": "Loan_Shark_Bot",
    "title_ko": "급전 필요하신가요? 무담보/무보증!",
    "title_en": "Need quick cash? Unsecured / No Guarantee!",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "신용 등급 9등급도 OK! 장기 담보 대출 승인률 99.9%. 지금 바로 클릭하세요. (연이자 4000%, 신체 포기 각서 자동 서명됨)",
    "body_en": "Credit rating level 9 is OK! Long-term mortgage loan approval rate 99.9%. Click right now. (Annual interest 4000%, physical renunciation memorandum automatically signed)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.04
  },
  {
    "type": "SPAM",
    "sender": "Recall_Notice",
    "title_ko": "[리콜] 옴니 다이내믹스 의수 결함 안내",
    "title_en": "[Recall] Omni Dynamics Prosthetic Arm Defect Notice",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "귀하가 착용한 의수에서 간헐적인 폭력성 제어 실패가 보고되었습니다. 가까운 정비소에서 펌웨어 업데이트를 받으십시오. *미조치 시 발생한 인명 피해에 대해 당사는 책임지지 않습니다.*",
    "body_en": "Intermittent violent control failure has been reported in the prosthetic arm you are wearing. Please get a firmware update at the nearest repair shop. *We are not responsible for casualties caused by failure to take action.*",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.02
  },
  {
    "type": "LORE",
    "sender": "Mars_Immigration_Bureau",
    "title_ko": "[공지] 제 42차 화성 이주권 추첨 결과",
    "title_en": "[Notice] Results of the 42nd Mars Immigration Lottery",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "금번 이주권 로또(Lotus Ticket) 당첨 번호를 안내해 드립니다. 1등: A-4929-X... (더 보기) *낙첨되신 분들은 지구에서 더 나은 삶을 개척하시길 바랍니다.*",
    "body_en": "We are announcing the winning numbers for this time's immigration lotto (Lotus Ticket). 1st place: A-4929-X... (See more) *For those who did not win, we hope you carve out a better life on Earth.*",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 15
  },
  {
    "type": "LORE",
    "sender": "Underground_Gossip",
    "title_ko": "전설의 해커 'Alt'가 돌아왔다?",
    "title_en": "Legendary hacker 'Alt' is back?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "어제 새벽, 딥 웹의 올드 서버 하나가 털렸어. 남겨진 시그니처가 50년 전 그 전설이랑 똑같다던데... 기업 놈들 지금 비상 걸렸음. ㅋㅋ",
    "body_en": "Early yesterday morning, an old server on the deep web was hacked. The left signature is exactly the same as that legend from 50 years ago... The corporate bastards are on high alert right now. lol",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_rep": 30
  },
  {
    "type": "SOCIAL",
    "sender": "Synapse_Recruiter",
    "title_ko": "임상 실험 아르바이트 모집",
    "title_en": "Clinical Trial Part-time Job Recruitment",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "신약 'Euphoria-X'의 베타 테스터를 모집합니다. 간단한 투약 후 포커를 치시면서 감정 변화만 기록하면 됩니다. 보수: 500 CR + 의료비 지원(필요 시).",
    "body_en": "We are recruiting beta testers for the new drug 'Euphoria-X'. After a simple administration, just record your emotional changes while playing poker. Compensation: 500 CR + medical expenses support (if necessary).",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_zone": "low_neon_lounge"
  },

  {
    "type": "SOCIAL",
    "sender": "Mom",
    "title_ko": "잘 지내니?",
    "title_en": "How are you doing?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "뉴스에서 또 폭동이 났다더라. 넌 괜찮은 거지? 배급표가 또 줄었어. 이번 달엔 약 보내주기 힘들 것 같아. 미안하다. 사랑한다 아들.",
    "body_en": "I heard on the news there was another riot. Are you okay? The ration tickets have been reduced again. It might be hard to send you medicine this month. I'm sorry. Love you, son.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 20
  },
  {
    "type": "SOCIAL",
    "sender": "Ex-Girlfriend",
    "title_ko": "돈 갚아",
    "title_en": "Pay me back",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "너 내 크레딧 카드 들고 튄 지 벌써 1년이야. 화성 갈 거라고 큰소리치더니, 아직도 그 시궁창에서 도박이나 하고 있니? 당장 안 갚으면 경찰에 신고할거야.",
    "body_en": "It's already been a year since you ran off with my credit card. You talked big about going to Mars, but are you still gambling in that gutter? If you don't pay me back right now, I'm calling the police.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_rep": 10
  },
  {
    "type": "SPAM",
    "sender": "Religious_Fanatic",
    "title_ko": "종말이 다가옵니다!",
    "title_en": "The apocalypse is approaching!",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "기술은 악마의 유혹입니다! 당신의 눈, 팔, 심장을 기계로 바꾸고도 인간이라 할 수 있습니까? 순수함으로 돌아가십시오. '자연 회귀 교단'이 당신을 기다립니다.",
    "body_en": "Technology is the devil's temptation! Can you still call yourself human after replacing your eyes, arms, and heart with machines? Return to purity. The 'Order of Natural Regression' awaits you.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.03
  },
  {
    "type": "LORE",
    "sender": "System_Admin",
    "title_ko": "Debug Message",
    "title_en": "Debug Message",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "Error: NPC 'Fish_04' logic loop detected. Resetting behavior module... (이 메시지는 플레이어에게 보여지면 안 됩니다)",
    "body_en": "Error: NPC 'Fish_04' logic loop detected. Resetting behavior module... (This message should not be visible to players)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.0001
  },
  {
    "type": "SOCIAL",
    "sender": "PokerBuddy_Mike",
    "title_ko": "야 어제 중계 봤냐?",
    "title_en": "Hey, did you see the broadcast yesterday?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "와씨 그 할배 플레이 봤어? 리버에 2, 7 들고 블러핑 치는데 지리더라 ㅋㅋ 내 멘탈이었으면 벌써 나갔음.",
    "body_en": "Wow, did you see that old man's play? Bluffing with a 2, 7 on the river was insane lol. If it were my mentality, I would've snapped already.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 5
  },
  {
    "type": "SOCIAL",
    "sender": "Gamble_Addict",
    "title_ko": "오늘 다운타운 물 좋다",
    "title_en": "The waters are good downtown today",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "지금 네온 라운지에 피쉬(Fish)들 떼거지로 몰려옴. 빨리 와라. 자리 없을 수도 있음. 난 벌써 5만 크레딧 땡김 ㅋㅋ",
    "body_en": "Flocks of Fish are swarming the Neon Lounge right now. Hurry up and come. There might not be seats. I already pulled in 50k credits lol",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_zone": "low_neon_lounge"
  },
  {
    "type": "SOCIAL",
    "sender": "Tilt_Master",
    "title_ko": "아니 이게 말이 되냐고",
    "title_en": "Like, does this make any sense?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "AA 들고 프리플랍 올인 박았는데, 상대가 7, 2 들고 콜 받더니 풀하우스 띄움. 이거 게임 조작 아님? 고객센터 신고한다 ㅡㅡ",
    "body_en": "I shoved all-in preflop with AA, and the opponent called with 7, 2 and flopped a full house. Isn't this game rigged? Reporting to customer service ugh",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_loss": true
  },
  {
    "type": "SOCIAL",
    "sender": "Rich_Wannabe",
    "title_ko": "화성 티켓 찌라시",
    "title_en": "Mars Ticket Rumors",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "야, 이번에 화성 이주권 암시장 시세 떴는데 10억 크레딧이라더라. 우리 같은 놈들은 평생 쳐도 못 가 ㅋㅋ 그냥 여기서 놀다 죽자.",
    "body_en": "Hey, the black market price for Mars immigration tickets is out, I heard it's 1 billion credits. Bastards like us could play for a lifetime and never go lol Just let's play here until we die.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 10
  },
  {
    "type": "SOCIAL",
    "sender": "PokerBuddy_Sarah",
    "title_ko": "너 어제 그 콜 뭐임?",
    "title_en": "What was with that call yesterday?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "리플레이 돌려봤는데, 거기서 3번째 넛으로 콜을 따? 미쳤냐 ㅋㅋ 너 혹시 상대 패 보이는 해킹 툴 쓰냐? 조심해라 밴 당한다.",
    "body_en": "I watched the replay, you called there with the 3rd nut? Are you crazy lol Are you using a hacking tool that sees the opponent's hand? Be careful, you'll get banned.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_win_big": true
  },
  {
    "type": "SOCIAL",
    "sender": "Loan_Beggar",
    "title_ko": "형님 제발 한 번만",
    "title_en": "Please lend me just once",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "진짜 딱 500 크레딧만 빌려주십쇼. 이번 판 느낌 진짜 좋습니다. 따면 바로 2배로 갚겠습니다. 저번에 빌린 건... 다음 주에 꼭...",
    "body_en": "Please lend me just 500 credits. I have a really good feeling about this game. I'll pay you back double if I win. About the money I borrowed last time... I'll definitely... next week...",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_rep": 20
  },
  {
    "type": "SOCIAL",
    "sender": "Strategy_Nerd",
    "title_ko": "요즘 메타 분석",
    "title_en": "Meta Analysis",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "요즘 그라인더들 죄다 GTO(Game Theory Optimal) 흉내 낸다고 난리네. 그래봤자 봇한테는 안 되는데 ㅋㅋ 우린 그냥 익스플로잇(Exploit)이나 파자.",
    "body_en": "These days, grinders are all the rage, pretending to be GTO (Game Theory Optimal). But they can't beat the bots lol Let's just exploit them.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_rep": 40
  },
  {
    "type": "SOCIAL",
    "sender": "Newbie_01",
    "title_ko": "질문 좀요 ㅠㅠ",
    "title_en": "I have a question",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "형님들, '팟 오즈'가 뭐예요? 이거 모르면 호구라던데... 족보 외우기도 힘들어 죽겠네요.",
    "body_en": "Hey bros, what's 'Pot Odds'? I heard you're a sucker if you don't know this... It's hard enough just memorizing the hand rankings.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_level": 1
  },
  {
    "type": "SOCIAL",
    "sender": "Old_Timer",
    "title_ko": "라떼는 말이야",
    "title_en": "Back in my day",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "옛날엔 패 까보면 다 뻥카였어. 요즘 애들은 너무 소심해. 레이즈를 못 쳐, 레이즈를. 낭만이 없어 낭만이.",
    "body_en": "In the old days, when you opened your hand, it was all a bluff. Kids these days are too timid. They can't raise, can't raise. There's no romance, no romance.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 30
  },
  {
    "type": "SOCIAL",
    "sender": "Anon_Hacker",
    "title_ko": "[정보] 카지노 보안 허점",
    "title_en": "[Info] Casino Security Flaw",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "다운타운 구형 카지노, 밤 10시부터 11시 사이에 난수 생성기(RNG) 루틴이 단순해진다. 믿거나 말거나. 난 이미 한탕 하고 빠짐. ㅋ",
    "body_en": "Downtown old casinos, the RNG routine becomes simpler between 10 PM and 11 PM. Believe it or not. I already made a killing and left. lol",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 44
  },
  {
    "type": "SOCIAL",
    "sender": "Drunk_Guy",
    "title_ko": "야, 술이나 한잔해",
    "title_en": "Hey, let's have a drink",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "돈 다 잃었다... 오늘따라 술맛이 쓰네. 너도 털렸냐? 리지스 바로 와라. 내가 산다. (거짓말임)",
    "body_en": "I lost all my money... The drinks taste bitter today. Did you get wiped out too? Come to Lizzie's right away. I'll buy. (Just kidding)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
  },
  {
    "type": "SOCIAL",
    "sender": "Conspiracy_Theorist",
    "title_ko": "이거 다 가짜야",
    "title_en": "This is all fake",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "우리가 진짜 카드를 치는 게 아니라, 시냅스 기업 놈들이 우리 뇌파 가지고 실험하는 거라니까? 너도 가끔 머리아프지 않냐?",
    "body_en": "We're not really playing cards, the Synapse Corp guys are experimenting with our brainwaves, I'm telling you? Don't you get headaches sometimes?",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.01
  },
  {
    "type": "SOCIAL",
    "sender": "Rage_Quitter",
    "title_ko": "접는다 ㅂㅂ",
    "title_en": "Quitting lol",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "이 망겜 안 함. 밸런스 꼬라지 봐라. 내일 다시 온다.",
    "body_en": "I'm quitting this damn game. Look at this balance. I'll be back tomorrow.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
  },
  {
    "type": "SOCIAL",
    "sender": "Lucky_Strike",
    "title_ko": "오늘의 운세",
    "title_en": "Today's Fortune",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "오늘 행운의 숫자는 7, 그리고 J야. 잭팟 터질 느낌? 믿고 올인 박아보자고!",
    "body_en": "Today's lucky numbers are 7 and J. I have a feeling a jackpot will hit? Let's bet it all with faith!",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
  },
  {
    "type": "SOCIAL",
    "sender": "Bad_Beat_Bob",
    "title_ko": "로그 깠다",
    "title_en": "Checked the Logs",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "방금 판 로그 보는데, 턴에 넛 플러시였던 놈이 리버에 풀하우스 된 거 실화냐? 확률 2%도 안 되는 걸 띄우네. 망겜 수준 ㅉㅉ",
    "body_en": "I checked the logs from the last game, and the guy who had the nut flush on the turn actually made a full house on the river? That's less than a 2% chance. This game is rigged lol",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
  },
  {
    "type": "SOCIAL",
    "sender": "Crypto_Bro",
    "title_ko": "VITECOIN 떡상!",
    "title_en": "VITECOIN Rocket!",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "야, 내가 뭐랬냐? 비트코인 지금 50% 올랐다. 포커 접고 코인이나 해라. 아직 저점이다. 지금이라도 타라.",
    "body_en": "Told ya! Vitecoin is up 50% right now. Quit poker and buy crypto. It's still early. Get in now.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 8
  },
  {
    "type": "SOCIAL",
    "sender": "GTO_Slave",
    "title_ko": "솔버 결과 공유함",
    "title_en": "Sharing solver results",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "방금 그 상황 솔버 돌려봤는데, 거기서 3벳은 실수임. 콜로 끊고 턴을 봤어야지. 공부 좀 해라.",
    "body_en": "Just ran that situation through the solver, a 3-bet there is a mistake. Should've just called and seen the turn. Study some more.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
  },
  {
    "type": "SOCIAL",
    "sender": "Hustler_J",
    "title_ko": "중고 칩 팝니다",
    "title_en": "Selling used chips",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "급전 필요해서 1만 크레딧 칩 9000에 팝니다. 쿨거래 시 네온 라운지 입장권 덤으로 드림. 쪽지 주세요.",
    "body_en": "Need quick cash, selling 10k credit chips for 9000. Will throw in a Neon Lounge entry ticket for a cool deal. DM me.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_zone": "low_neon_lounge"
  },
  {
    "type": "SOCIAL",
    "sender": "Paranoid_Pat",
    "title_ko": "딜러 로봇 눈빛 봤냐?",
    "title_en": "Did you see the dealer robot's eyes?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "아까 그 딜러 봇, 내가 패 쪼을 때 눈이 빨갛게 빛나던데? 내 패 스캔한 거 아님? 이따가 끝나고 뒷골목에서 확인해본다.",
    "body_en": "That dealer bot earlier, its eyes flashed red when I was squeezing my cards. Didn't it scan my hand? I'm gonna check it out in the back alley after this.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.02
  },
  {
    "type": "SOCIAL",
    "sender": "Tournament_Grinder",
    "title_ko": "주말 토너먼트 파티 구함",
    "title_en": "Looking for a weekend tournament party",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "이번 주말 '새터데이 나이트 피버' 토너먼트 지분 투자자 구합니다. ROI 20% 보장. 전적 검색 해보셈. 아이디: Ace_Killer",
    "body_en": "Looking for stakers for this weekend's 'Saturday Night Fever' tournament. 20% ROI guaranteed. Check my stats. ID: Ace_Killer",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 6
  },
  {
    "type": "SPAM",
    "sender": "Mars_Real_Estate",
    "title_ko": "화성 돔(Dome) 입주권 특별 분양",
    "title_en": "Mars Dome Residency Special Pre-sale",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "지구에서의 삶이 지겨우신가요? 화성 '뉴 에덴' 돔의 쾌적한 공기를 마시며 여생을 보내세요. 지금 계약하시면 산소 발생기 무료 업그레이드!",
    "body_en": "Are you tired of life on Earth? Spend the rest of your life breathing the fresh air of the Mars 'New Eden' Dome. Free oxygen generator upgrade if you sign now!",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.03
  },
  {
    "type": "SPAM",
    "sender": "Cyber_Church",
    "title_ko": "당신의 영혼을 백업하십시오",
    "title_en": "Backup your soul",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "육체는 썩어 문드러지지만, 데이터는 영원합니다. '이터널 클라우드(Eternal Cloud)' 장례 서비스. 당신의 의식을 서버에 업로드하세요.",
    "body_en": "The flesh rots away, but data is eternal. 'Eternal Cloud' funeral service. Upload your consciousness to the server.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.02
  },
  {
    "type": "SPAM",
    "sender": "Hot_Androids",
    "title_ko": "근처에 외로운 안드로이드가 있습니다",
    "title_en": "There are lonely androids nearby",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "당신의 1km 반경 내에 주인을 기다리는 안드로이드가 3기 있습니다. [프로필 보기] *성인 인증 필요*",
    "body_en": "There are 3 androids waiting for an owner within a 1km radius of you. [View Profile] *Adult verification required*",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "SPAM",
    "sender": "Brain_Hack_Tool",
    "title_ko": "상대의 생각을 읽고 싶나요?",
    "title_en": "Do you want to read your opponent's thoughts?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "최신형 '마인드 리더' 해킹 툴 불법 유출본! 상대의 동공 확장, 심박수 변화를 분석하여 블러핑을 99.9% 감지합니다. 다운로드 링크 -> click.here",
    "body_en": "Illegally leaked version of the latest 'Mind Reader' hacking tool! Analyzes the opponent's pupil dilation and heart rate changes to detect bluffs with 99.9% accuracy. Download link -> click.here",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.04
  },
  {
    "type": "LORE",
    "sender": "City_Admin",
    "title_ko": "[공지] 통행 금지 시간 안내",
    "title_en": "[Notice] Curfew Time Guide",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "최근 갱단 간의 총격전 빈발로 인해 다운타운 구역 통행 금지 시간이 변경되었습니다. 22:00 ~ 06:00 위반 시 즉결 처형될 수 있습니다.",
    "body_en": "Due to the recent frequent shootouts between gangs, the curfew time for the downtown area has been changed. 22:00 ~ 06:00. Violators may be summarily executed.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 18
  },
  {
    "type": "LORE",
    "sender": "WNS News",
    "title_ko": "[경제] 물값 폭등, 시민들 반발",
    "title_en": "[Economy] Water Price Surge, Citizens Backlash",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "정수 플랜트 오염으로 인해 생수 가격이 전주 대비 300% 폭등했습니다. 시민들은 빗물 정수 필터를 구하기 위해 암시장으로 몰리고 있습니다.",
    "body_en": "Due to the contamination of the water purification plant, the price of bottled water has surged by 300% compared to last week. Citizens are flocking to the black market to get rainwater purification filters.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 25
  },

  {
    "type": "LORE",
    "sender": "Gossip_Girl_2077",
    "title_ko": "유명 포커 프로 A씨, 사실은 AI?",
    "title_en": "Famous Poker Pro Mr. A, actually an AI?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "최근 연승 행진을 달리는 프로 포커 플레이어 'X'가 사실은 완벽하게 위장된 안드로이드라는 소문이 돌고 있어. 밥 먹는 걸 본 사람이 아무도 없다는데?",
    "body_en": "Rumor has it that pro poker player 'X', who is currently on a winning streak, is actually a perfectly disguised android. They say no one has ever seen him eat?",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
  },
  {
    "type": "SOCIAL",
    "sender": "Militech_HR",
    "title_ko": "보안 요원 채용 (경력직)",
    "title_en": "Security Personnel Hiring (Experienced)",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "신체 개조율 70% 이상, 전투 모듈 장착자 우대. 주요 업무: 기업 자산 보호 및 '불순분자' 제거. 연봉: 협의 가능 + 탄약 무제한 지급.",
    "body_en": "Body modification rate 70% or higher, preference for those equipped with combat modules. Main duties: Corporate asset protection and elimination of 'impure elements'. Annual salary: Negotiable + unlimited ammunition provided.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_augment": true
  },
  {
    "type": "SOCIAL",
    "sender": "Old_Friend",
    "title_ko": "야, 살아있냐?",
    "title_en": "Hey, you alive?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "너 소식 끊긴 지 꽤 됐다? 죽은 줄 알고 장례식 치를 뻔했잖아. 이번에 크게 한탕 했다며? 술이나 한번 사라.",
    "body_en": "It's been a while since I've heard from you? Thought you were dead, almost held a funeral. Heard you hit it big this time? Buy me a drink sometime.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_win_big": true
  },
  {
    "type": "SOCIAL",
    "sender": "Landlord",
    "title_ko": "[경고] 소음 공해 민원 접수",
    "title_en": "[Warning] Noise Pollution Complaint Received",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "당신 방에서 밤마다 고성방가(비명?)가 들린다는 민원이 들어왔습니다. 한 번만 더 신고 들어오면 퇴실 조치합니다. *샷건 소리는 자제해주세요.*",
    "body_en": "Received a complaint that loud singing (screaming?) is heard from your room every night. One more report and you will be evicted. *Please refrain from shotgun noises.*",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "SOCIAL",
    "sender": "Noob_Killer",
    "title_ko": "뉴비들 귀엽네 ㅋㅋ",
    "title_en": "Noobs are cute lol",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "마이크로 스테이크 양민 학살 꿀잼. 림프하고 하는 거 보면 암 걸릴 것 같은데 돈은 잘 벌림. 다들 얼른 와서 빨대 꽂으셈.",
    "body_en": "Slaughtering peasants at micro stakes is so fun. Watching them limp gives me cancer but the money is good. Everyone hurry up and stick your straws in.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_zone": "micro_street_shop"
  },
  {
    "type": "SOCIAL",
    "sender": "Variance_Victim",
    "title_ko": "다운스윙 20바이인 째...",
    "title_en": "Downswing for 20 buy-ins...",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "나 진짜 포커 신한테 저주받았나 봐. AK가 AQ한테 10번 연속 넘어가네. 이게 확률적으로 말이 되냐? 뛰어내리고 싶다!!!",
    "body_en": "I must be really cursed by the poker gods. AK losing to AQ 10 times in a row. Does this make sense probabilistically? I wanna jump out!!!",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_loss": true
  },
  {
    "type": "SOCIAL",
    "sender": "Bluff_King",
    "title_ko": "72o으로 쿼즈 띄움 ㅋㅋㅋ",
    "title_en": "Hit quads with 72o lol",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "상대 표정 썩는 거 봤어야 되는데. 이 맛에 포커 치지. 근데 다음 판에 AA 들고 넘어감 ㅠ",
    "body_en": "You should've seen the opponent's face rotting. This is why I play poker. But then I lost with AA on the next hand T.T",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "SOCIAL",
    "sender": "Table_Sheriff",
    "title_ko": "매너 좀 챙겨라",
    "title_en": "Mind your manners",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "야, 칩 던지는 놈 누구냐? 딜러 봇 인식 오류 난다고. 기본 예절은 좀 지키면서 게임하자.",
    "body_en": "Hey, who's the guy throwing chips? It's causing recognition errors for the dealer bot. Let's play the game with some basic etiquette.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "id": "SPAM_014",
    "type": "SPAM",
    "sender": "Organ_Dealer",
    "title_ko": "신선한 신장 삽니다",
    "title_en": "Buying fresh kidneys",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "A급 신장, 간, 안구 최고가 매입. 수술비 무료, 1시간 내 입금. 급전 필요하신 분 연락주세요. (비밀 보장)",
    "body_en": "Top price purchase for A-grade kidneys, livers, and eyes. Free surgery cost, transfer within 1 hour. Contact us if you need quick cash. (Confidentiality guaranteed)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.03
  },
  {
    "type": "SPAM",
    "sender": "Fake_Police",
    "title_ko": "[출석 요구서] 귀하는 도박법 위반 혐의로...",
    "title_en": "[Subpoena] You are charged with violating gambling laws...",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "신고가 접수되었습니다. 24시간 내에 아래 링크로 벌금을 납부하지 않으면 체포 영장이 발부됩니다. [납부하기 (바이러스 포함)]",
    "body_en": "A report has been filed. If you do not pay the fine via the link below within 24 hours, an arrest warrant will be issued. [Pay (Includes virus)]",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.02
  },
  {
    "type": "LORE",
    "sender": "History_Channel",
    "title_ko": "오늘의 역사: 2020년 팬데믹",
    "title_en": "Today in History: The 2020 Pandemic",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "오늘은 2020년 대유행의 시작일로부터 37년째 되는 날입니다. 그때는 마스크만 쓰면 살 수 있었죠. 지금은 방독면이 없으면 5분도 못 버티는데 말입니다.",
    "body_en": "Today marks the 37th anniversary of the start of the 2020 pandemic. Back then, you could live just by wearing a mask. Now, you can't even last 5 minutes without a gas mask.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 40
  },
  {
    "type": "SOCIAL",
    "sender": "Coffee_Addict",
    "title_ko": "카페인 수혈 시급",
    "title_en": "Urgent need for caffeine transfusion",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "24시간째 그라인딩 중. 에너지 드링크 추천 좀 해줘. '블루베어' 먹었다가 심장 터질 뻔함.",
    "body_en": "Grinding for 24 hours straight. Give me some energy drink recommendations. Almost had a heart attack after drinking 'Blue Bear'.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.1
  },
  {
    "type": "SOCIAL",
    "sender": "Pattern_Analyst",
    "title_ko": "Fish_03 얘 봇 아님?",
    "title_en": "Isn't Fish_03 a bot?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "배팅 사이즈가 너무 일정한데? 프리플랍 2.5BB 오픈, 림프엔 4BB 레이즈. 딱 봐도 매크로 돌리는 봇이다. 운영자 뭐하냐?",
    "body_en": "The bet sizes are too consistent. 2.5BB open preflop, 4BB raise against limps. Obvious macro bot. What is the admin doing?",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_zone": "micro_warehouse"
  },
  {
    "type": "SOCIAL",
    "sender": "Pro_Watcher",
    "title_ko": "와, 네임드 프로 봤음",
    "title_en": "Wow, saw a named pro",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "High Stakes 테이블 관전하는데 'Isildur_Clone' 있더라. 칩 스택이 내 전재산의 100배임 ㄷㄷ 숨만 쉬어도 돈 벌겠네 부럽다.",
    "body_en": "Watching the High Stakes table and saw 'Isildur_Clone'. Chip stack is 100 times my net worth wtf. They'd make money just breathing, so jealous.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_rep": 50
  },
  {
    "type": "SOCIAL",
    "sender": "Rake_Hater",
    "title_ko": "레이크 실화냐?",
    "title_en": "Is this rake real?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "카지노 놈들 레이크(Rake) 10% 떼가는 거 너무한 거 아님? 우리가 호구도 아니고... 이래서 다들 불법 하우스 가나 봄.",
    "body_en": "The casino bastards taking 10% rake is too much, isn't it? We're not suckers... I guess this is why everyone goes to illegal houses.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "SOCIAL",
    "sender": "Late_Reg_King",
    "title_ko": "토너먼트 레이트 레지 됨?",
    "title_en": "Can I late reg the tournament?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "지금 일어났는데 토너 참가 가능? 블라인드 이미 많이 올랐으려나. 에라 모르겠다 숏스택 운영 간다.",
    "body_en": "Just woke up, can I join the tournament? Blinds must have gone up a lot already. Whatever, gonna go with short stack plays.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "LORE",
    "sender": "Developer",
    "title_ko": "Hello World",
    "title_en": "Hello World",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "System.out.println(\"이 메시지를 발견하다니 운이 좋군요.\"); // TODO: 여기에 히든 보상 추가하기",
    "body_en": "System.out.println(\"You are lucky to have found this message.\"); // TODO: Add hidden reward here",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.0001
  },
  {
    "type": "SPAM",
    "sender": "Time_Traveler",
    "title_ko": "미래에서 왔습니다",
    "title_en": "I am from the future",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "저는 2077년에서 왔습니다. 내일 모레 시냅스 주식 사세요. 100배 오릅니다. 수수료는 나중에 10%만 주시면 됩니다.",
    "body_en": "I am from 2077. Buy Synapse stock the day after tomorrow. It goes up 100x. You only have to give me a 10% commission later.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.01
  },
  {
    "type": "SOCIAL",
    "sender": "Bad_Beat_Barry",
    "title_ko": "리버 억까 레전드",
    "title_en": "River Bad Beat Legend",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "플랍 셋(Set)이었는데 리버에 상대 원카드 스트레이트 완성됨. 키보드 부셨다. 추천 키보드 받는다...",
    "body_en": "I had a Set on the flop, but the river gave my opponent a straight with one card. I broke my keyboard. Send me keyboard recommendations...",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_loss": true
  },
  {
    "type": "SOCIAL",
    "sender": "Happy_Grinder",
    "title_ko": "오늘 일당 벌었다",
    "title_en": "Earned today's daily wage",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "3시간 쳐서 20,000 크레딧 멘징함. 오늘 저녁은 합성 영양 죽 말고 진짜 고기 먹으러 간다. 부럽냐? ㅋㅋ",
    "body_en": "3 hours of playing and broke even at 20,000 credits. Going to eat real meat tonight instead of synthetic nutrient gruel. Jealous? lol",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_win_big": true
  },
  {
    "type": "SOCIAL",
    "sender": "Lounge_Rat",
    "title_ko": "오르빗 라운지 썰 푼다",
    "title_en": "Telling a story about Orbit Lounge",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "아는 형이 오르빗 라운지 웨이터로 일하는데, 거기선 팁으로 1,000,000 크레딧 칩 던져준대. 우리도 언젠간 갈 수 있겠지?",
    "body_en": "A guy I know works as a waiter at Orbit Lounge, they say tips there are thrown in 1,000,000 credit chips. We'll be able to go there someday, right?",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_rep": 80
  },
  {
    "type": "SOCIAL",
    "sender": "Fold_Master",
    "title_ko": "포커는 인내심이다",
    "title_en": "Poker is patience",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "1시간 동안 패 안 들어와서 폴드만 함. 블라인드 때문에 칩 다 녹겠다. 언제까지 참아야 하냐...",
    "body_en": "Folded for an hour straight because I didn't get any hands. My chips are melting away from blinds. How long do I have to wait...",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.1
  },
  {
    "type": "SOCIAL",
    "sender": "Shark_Bait",
    "title_ko": "형들 나 호구임?",
    "title_en": "Guys, am I a sucker?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "방금 판 상대가 첵-레이즈 하길래 올인 박았는데 넛(Nut) 들고 있었네... 이거 뻔한 패턴이었음? ㅠㅠ",
    "body_en": "The opponent check-raised last hand so I shoved all-in, turned out they had the Nut... Was this an obvious pattern? T.T",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "SOCIAL",
    "sender": "City_Drifter",
    "title_ko": "비 온다",
    "title_en": "It's raining",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "산성비 오지게 오네. 오늘은 그냥 집에서 온라인 포커나 쳐야겠다. 너네도 괜히 나갔다가 피부 녹지 마라.",
    "body_en": "It's pouring acid rain. Guess I should just stay home and play online poker today. Don't go out for nothing and let your skin melt off.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_day": 10
  },
  {
    "type": "LORE",
    "sender": "Synapse_HR",
    "title_ko": "[의무] 직원 행복도 조사",
    "title_en": "[Mandatory] Employee Happiness Survey",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "모든 시민은 의무적으로 월 1회 행복도 조사를 받아야 합니다. 당신의 행복 수치가 50 미만일 경우, 강제 심리 치료가 진행될 수 있습니다. *웃으세요. 시냅스가 지켜보고 있습니다.*",
    "body_en": "All citizens must undergo a mandatory happiness survey once a month. If your happiness level is under 50, forced psychological treatment may proceed. *Smile. Synapse is watching.*",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "SOCIAL",
    "sender": "Slow_Roll_Hater",
    "title_ko": "슬로우 롤(Slow Roll) 하는 새끼들",
    "title_en": "Those bastards who Slow Roll",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "아니 넛 들고 왜 고민하는 척함? 시간 끄는 거 비매너 아님? 진짜 손가락 잘라버리고 싶네.",
    "body_en": "Why act like you're hesitating when you hold the nut? Isn't wasting time bad manners? I really wanna cut their fingers off.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_loss": true
  },
  {
    "type": "SOCIAL",
    "sender": "High_Roller_Wannabe",
    "title_ko": "나도 마바리 탈출한다",
    "title_en": "I'm escaping the fish bowl too",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "오늘 잭팟 터져서 시드머니 10배 불림. 이제 마이크로 스테이크 졸업하고 로우(Low) 간다. 가서 털리고 다시 올게 ㅋㅋ",
    "body_en": "Hit the jackpot today and multiplied my seed money by 10. Graduating from micro stakes and going to Low. I'll go get busto and come back lol",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_win_big": true
  },
  {
    "type": "SPAM",
    "sender": "Pet_Clone_Service",
    "title_ko": "죽은 강아지를 다시 만나세요",
    "title_en": "Meet your dead dog again",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "당신의 소중한 반려동물, 클로닝 기술로 완벽하게 복원해 드립니다. 기억 이식 옵션 포함. 지금 예약 시 털 색상 변경 무료.",
    "body_en": "We will perfectly restore your precious pet with cloning technology. Memory transplant option included. Free fur color change when you book now.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.02
  },
  {
    "type": "SOCIAL",
    "sender": "NetWatch_Agent",
    "title_ko": "[경고] 불법 맥주소 탐지됨",
    "title_en": "[Warning] Illegal MAC Address Detected",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "귀하의 접속 로그에서 인가되지 않은 VPN 사용 흔적이 발견되었습니다. 즉시 중단하지 않을 경우, 접속 차단 및 위치 추적이 개시됩니다.",
    "body_en": "Traces of unauthorized VPN use have been detected in your access logs. If not stopped immediately, connection blocking and location tracking will be initiated.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.01
  },
  {
    "type": "SOCIAL",
    "sender": "Blind_Stealer",
    "title_ko": "블라인드 스틸 개꿀",
    "title_en": "Blind Steal is sweet",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "버튼에서 아무거나 들고 레이즈하면 다 죽네 ㅋㅋㅋ 니들 패 안 보고 치지? 오늘도 공짜 밥 먹고 갑니다~",
    "body_en": "Everything folds when I raise with any two cards on the button lol You guys don't even look at your cards right? Eating a free meal today again~",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_win_big": true
  },
  {
    "type": "SOCIAL",
    "sender": "River_Rat",
    "title_ko": "리버는 나의 편",
    "title_en": "The River is on my side",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "플랍, 턴 다 지고 있었는데 리버에 역전함. 역시 포커는 운빨망겜이다. 꼬우면 니들도 기도해라.",
    "body_en": "Was losing on the flop and turn but hit a reversal on the river. Poker really is a luck-based trash game. Pray too if you're upset.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_win_big": true
  },
  {
    "type": "LORE",
    "sender": "Space_Tour_Agency",
    "title_ko": "달 기지 관광 패키지",
    "title_en": "Moon Base Tour Package",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "지구의 중력에서 벗어나세요! 3박 4일 달 기지 투어 특가 세일. *우주복 대여료 별도*",
    "body_en": "Break free from Earth's gravity! Special sale on a 3-night, 4-day Moon Base Tour. *Spacesuit rental fee not included*",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.03
  },
  {
    "type": "SOCIAL",
    "sender": "Bot_Hunter",
    "title_ko": "봇 구분법 알려줌",
    "title_en": "Telling you how to spot a bot",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "1. 채팅 안 침 2. 벳 사이즈가 기계적임 3. 틸트가 없음 근데 3번은 나도 해당 안 되네... 젠장.",
    "body_en": "1. No chatting 2. Bet sizes are mechanical 3. No tilt But #3 doesn't apply to me... damn.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "trigger_level": 5
  },
  {
    "type": "LORE",
    "sender": "Red_Pill",
    "title_ko": "진실을 원해?",
    "title_en": "You want the truth?",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "만약 이 모든 게 시뮬레이션이라면? 네가 낀 썬글라스... 아니 VR 고글을 벗어봐. 현실은 훨씬 더 시궁창일 테니까.",
    "body_en": "What if all of this is a simulation? Take off the sunglasses... no, the VR goggles you're wearing. Reality will be much more of a gutter.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.001
  },
  {
    "type": "LORE",
    "sender": "Omni_Dynamics_PR",
    "title_ko": "[공시] 'Peacemaker' 드론 2.0 소프트웨어 업데이트",
    "title_en": "[Notice] 'Peacemaker' Drone 2.0 Software Update",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "신규 '감정 감지' 알고리즘이 탑재되었습니다. 이제 드론들이 시민들의 얼굴에서 '불생산적인 분노'를 감지하면 즉시 진정제를 살포합니다. 평화로운 거리를 위해 협조해 주십시오.",
    "body_en": "Equipped with a new 'emotion detection' algorithm. Drones will now immediately spray sedatives when they detect 'unproductive anger' on citizens' faces. Please cooperate for a peaceful street.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.04
  },
  {
    "type": "SPAM",
    "sender": "Black_Market_Express",
    "title_ko": "준신분급 화성 이주권",
    "title_en": "Semi-Identity Grade Mars Ticket",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "취소된 예약자의 티켓을 세척하여 재판매합니다! 정상가의 1/10 가격! 신분 세탁 옵션 포함. 추적 방지를 위해 암호화폐(CR) 송금만 받습니다. 서두르세요!",
    "body_en": "Washed and resold tickets from cancelled reservations! 1/10th the normal price! Identity laundering option included. Only cryptocurrency (CR) transfers accepted to avoid tracking. Hurry up!",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.02
  },
  {
    "type": "LORE",
    "sender": "The_Grinder_Forum",
    "title_ko": "[필독] 왜 AI는 우리의 포커를 이해하지 못하는가",
    "title_en": "[Must Read] Why AI can't understand our poker",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "알고리즘은 확률을 계산하지만, 죽음을 앞둔 인간의 '절박한 기만'은 계산하지 못합니다. 지하 룸은 단순한 도박장이 아닙니다. 기계의 차가운 논리를 이길 수 있는 마지막 성역입니다.",
    "body_en": "Algorithms calculate probabilities, but they cannot calculate the 'desperate deception' of a human facing death. The underground room is not just a gambling den. It's the last sanctuary where we can beat the cold logic of machines.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.03
  },
  {
    "type": "SPAM",
    "sender": "Synapse_Enhance_Bot",
    "title_ko": "포커 승률 +15% 증가! 'Focus-Max' 임플란트",
    "title_en": "Poker Win Rate +15% INCREASE! 'Focus-Max' Implant",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "카드 패턴을 초당 1,000회 분석하는 뇌 보조 연산 장치. 법적 제재를 피하는 '스텔스 모드' 탑재. 1,000,000 CR로 당신의 미래를 바꾸세요. (부작용: 단기 기억 상실)",
    "body_en": "Brain auxiliary computing device that analyzes card patterns 1,000 times per second. Equipped with a 'stealth mode' to avoid legal sanctions. Change your future with 1,000,000 CR. (Side effect: Short-term memory loss)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.04
  },
  {
    "type": "LORE",
    "sender": "N54_Data_Analytics",
    "title_ko": "[보고서] '잉여 인간' 지수 사상 최고치 기록",
    "title_en": "[Report] 'Surplus Human' Index Reaches All-Time High",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "AI 자동화로 인해 '가치 없음'으로 분류된 인구가 전체의 92%를 넘어섰습니다. 시냅스 사는 이를 해결하기 위해 저소득층을 위한 '영구 가상현실 이주' 사업을 검토 중이라고 밝혔습니다.",
    "body_en": "Due to AI automation, the population classified as 'valueless' has exceeded 92%. Synapse Corp announced that it is reviewing a 'Permanent Virtual Reality Migration' project for the low-income class to solve this.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.03
  },
  {
    "type": "SPAM",
    "sender": "Debt_Freedom_Solution",
    "title_ko": "도박 빚? 신체 일부로 상환 가능합니다!",
    "title_en": "Gambling debt? Repayable with body parts!",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "추심원들이 문을 두드리고 있습니까? 걱정 마세요. 안 쓰는 장기나 눈을 기증하고 신용 등급을 회복하세요. 지금 신청 시 마취제 50% 할인 쿠폰 증정!",
    "body_en": "Are debt collectors knocking on your door? Don't worry. Donate an unused organ or eye and restore your credit rating. Apply now and get a 50% discount coupon for anesthesia!",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "LORE",
    "sender": "Citizen_Watch",
    "title_ko": "[경보] 하늘의 색을 확인하십시오",
    "title_en": "[Alarm] Check the color of the sky",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "오늘 저녁 스모그 농도가 '치명적'으로 격상되었습니다. 기업들의 공장 가열로 인해 하늘이 황금색으로 빛나고 있습니다. 아름답지만 치명적입니다. 절대 숨을 깊게 쉬지 마십시오.",
    "body_en": "Smog density has been upgraded to 'FATAL' this evening. The sky is glowing golden due to the heating of corporate factories. It's beautiful but deadly. Never take a deep breath.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.02
  },
  {
    "type": "LORE",
    "sender": "The_Deep_Web",
    "title_ko": "방치된 서버실에 숨겨진 '바이너리 성소'",
    "title_en": "The 'Binary Sanctuary' hidden in an abandoned server room",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "구형 기업 서버실 지하에 아무도 모르는 포커 룸이 있다는 소문이 있어. 거기선 칩 대신 정보(Data)를 걸고 게임을 한다던데... 입장 코드를 아는 사람?",
    "body_en": "There's a rumor that there's a poker room underneath an old corporate server room that no one knows about. I heard they gamble with Information (Data) instead of chips there... Anyone know the entry code?",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.01
  },
  {
    "type": "SPAM",
    "sender": "Waifu_AI_2057",
    "title_ko": "당신만을 위한 완법한 연인, '미카'",
    "title_en": "Perfect lover just for you, 'Mika'",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "외로우신가요? 당신의 뇌파에 동기화되는 AI 연인을 다운로드하세요. 누구보다 당신을 잘 이해합니다. (주의: 설치 시 개인 정보 및 뱅킹 데이터 접근 권한이 필요합니다)",
    "body_en": "Are you lonely? Download an AI lover that synchronizes with your brainwaves. Understands you better than anyone. (Note: Requires access to personal information and banking data upon installation)",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.05
  },
  {
    "type": "LORE",
    "sender": "Old_Man_Rick",
    "title_ko": "특이점이 온다더니, 지옥이 왔어",
    "title_en": "They said Singularity was coming, but Hell arrived",
    get title() { return store.settings.language === 'en' ? this.title_en : this.title_ko; },
    "body_ko": "20년 전엔 모두가 기계가 일을 대신하면 낙원이 올 거라 믿었지. 하지만 기계는 쉬지 않고 일하고, 우린 쉬지 않고 굶게 됐어. 이 포커 칩만이 내가 인간임을 느끼게 해주는 유일한 증표네.",
    "body_en": "20 years ago, everyone believed that if machines did the work for us, paradise would come. But the machines work without rest, and we starve without rest. These poker chips are the only evidence that lets me feel like a human.",
    get body() { return store.settings.language === 'en' ? this.body_en : this.body_ko; },
    "probability": 0.03
  }
]

export const getRndLoreSpamMessage = () => {
  const rndIndex = Math.round(Math.random() * (lore_spam_message.length - 1));
  return lore_spam_message[rndIndex];
}